// Auto-generated by scripts/generate-confusable-weights.js
// Source: confusable-vision confusable-weights.json (903 pairs)
// Generated: 2026-02-25T18:41:50.128Z
//
// DO NOT EDIT MANUALLY. Regenerate with:
//   node scripts/generate-confusable-weights.js

import type { ConfusableWeight, ConfusableWeights } from "./index";

/**
 * Measured visual similarity weights for 903 confusable pairs
 * (110 TR39 + 793 novel discoveries).
 *
 * Scored across macos-m1-system-230fonts using SSIM.
 * Each weight includes danger (max SSIM), stableDanger (p95 SSIM), cost (1 - stableDanger),
 * and identifier property flags (xidContinue, idnaPvalid, tr39Allowed).
 *
 * Import from "namespace-guard/confusable-weights" to use with confusableDistance().
 */
export const CONFUSABLE_WEIGHTS: ConfusableWeights = {
  "|": {
    "l": {danger:1,stableDanger:0.9153,cost:0.0847,idnaPvalid:true},
  },
  "\u00d7": {
    "x": {danger:1,stableDanger:0.7019,cost:0.2981,idnaPvalid:true},
  },
  "\u00ec": {
    "i": {danger:0.9335,stableDanger:0.8873,cost:0.1127,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u00ed": {
    "i": {danger:0.9392,stableDanger:0.9206,cost:0.0794,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u012b": {
    "i": {danger:0.8945,stableDanger:0.8669,cost:0.1331,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0130": {
    "i": {danger:0.9678,stableDanger:0.9171,cost:0.0829,xidContinue:true,tr39Allowed:true},
    "l": {danger:0.9699,stableDanger:0.938,cost:0.062,xidContinue:true,tr39Allowed:true},
  },
  "\u0131": {
    "i": {danger:1,stableDanger:0.9053,cost:0.0947,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u013a": {
    "l": {danger:1,stableDanger:0.8905,cost:0.1095,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u013c": {
    "l": {danger:0.9296,stableDanger:0.8773,cost:0.1227,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0142": {
    "l": {danger:0.9441,stableDanger:0.855,cost:0.145,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0167": {
    "t": {danger:0.8876,stableDanger:0.8751,cost:0.1249,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u017f": {
    "f": {danger:1,stableDanger:0.7756,cost:0.2244,xidContinue:true},
  },
  "\u0183": {
    "b": {danger:0.94,stableDanger:0.9362,cost:0.0638,xidContinue:true,idnaPvalid:true},
  },
  "\u018c": {
    "d": {danger:0.9386,stableDanger:0.9358,cost:0.0642,xidContinue:true,idnaPvalid:true},
  },
  "\u0196": {
    "l": {danger:1,stableDanger:1,cost:0,xidContinue:true},
  },
  "\u0199": {
    "k": {danger:0.9634,stableDanger:0.9508,cost:0.0492,xidContinue:true,idnaPvalid:true},
  },
  "\u019a": {
    "l": {danger:0.8302,stableDanger:0.8217,cost:0.1783,xidContinue:true,idnaPvalid:true},
  },
  "\u01ad": {
    "f": {danger:0.9281,stableDanger:0.925,cost:0.075,xidContinue:true,idnaPvalid:true},
  },
  "\u01ae": {
    "l": {danger:0.8208,stableDanger:0.8199,cost:0.1801,xidContinue:true},
  },
  "\u01b6": {
    "z": {danger:0.9311,stableDanger:0.8388,cost:0.1612,xidContinue:true,idnaPvalid:true},
  },
  "\u01bb": {
    "2": {danger:0.8071,stableDanger:0.8007,cost:0.1993,xidContinue:true,idnaPvalid:true},
  },
  "\u01bc": {
    "5": {danger:1,stableDanger:0.9313,cost:0.0687,xidContinue:true},
  },
  "\u01c0": {
    "l": {danger:0.9932,stableDanger:0.9176,cost:0.0824,xidContinue:true,idnaPvalid:true},
  },
  "\u01c3": {
    "i": {danger:0.8866,stableDanger:0.8468,cost:0.1532,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.9447,stableDanger:0.9008,cost:0.0992,xidContinue:true,idnaPvalid:true},
  },
  "\u01cf": {
    "i": {danger:0.9031,stableDanger:0.8909,cost:0.1091,xidContinue:true,tr39Allowed:true},
  },
  "\u01d0": {
    "i": {danger:0.9001,stableDanger:0.8723,cost:0.1277,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u020b": {
    "i": {danger:0.8966,stableDanger:0.8247,cost:0.1753,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0237": {
    "j": {danger:0.9206,stableDanger:0.9047,cost:0.0953,xidContinue:true,idnaPvalid:true},
  },
  "\u0249": {
    "j": {danger:0.8298,stableDanger:0.8289,cost:0.1711,xidContinue:true,idnaPvalid:true},
  },
  "\u024f": {
    "y": {danger:0.8842,stableDanger:0.8741,cost:0.1259,xidContinue:true,idnaPvalid:true},
  },
  "\u0251": {
    "a": {danger:1,stableDanger:0.4918,cost:0.5082,xidContinue:true,idnaPvalid:true},
  },
  "\u0261": {
    "g": {danger:1,stableDanger:0.8133,cost:0.1867,xidContinue:true,idnaPvalid:true},
  },
  "\u0266": {
    "h": {danger:0.9618,stableDanger:0.9482,cost:0.0518,xidContinue:true,idnaPvalid:true},
  },
  "\u0268": {
    "i": {danger:0.9384,stableDanger:0.9065,cost:0.0935,xidContinue:true,idnaPvalid:true},
  },
  "\u0283": {
    "i": {danger:0.8125,stableDanger:0.8066,cost:0.1934,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.8501,stableDanger:0.8465,cost:0.1535,xidContinue:true,idnaPvalid:true},
  },
  "\u0285": {
    "l": {danger:0.8682,stableDanger:0.8507,cost:0.1493,xidContinue:true,idnaPvalid:true},
  },
  "\u02b0": {
    "b": {danger:0.8513,stableDanger:0.8254,cost:0.1746,xidContinue:true},
  },
  "\u02b2": {
    "j": {danger:0.9731,stableDanger:0.9685,cost:0.0315,xidContinue:true},
  },
  "\u02b3": {
    "r": {danger:0.9426,stableDanger:0.9214,cost:0.0786,xidContinue:true},
  },
  "\u02b7": {
    "w": {danger:0.9698,stableDanger:0.9638,cost:0.0362,xidContinue:true},
  },
  "\u02b8": {
    "y": {danger:0.9735,stableDanger:0.972,cost:0.028,xidContinue:true},
  },
  "\u02e1": {
    "i": {danger:0.9218,stableDanger:0.9159,cost:0.0841,xidContinue:true},
    "l": {danger:0.982,stableDanger:0.9666,cost:0.0334,xidContinue:true},
  },
  "\u02e2": {
    "s": {danger:0.9376,stableDanger:0.9364,cost:0.0636,xidContinue:true},
  },
  "\u02e3": {
    "x": {danger:0.9513,stableDanger:0.9333,cost:0.0667,xidContinue:true},
  },
  "\u0391": {
    "a": {danger:1,stableDanger:0.2639,cost:0.7361,xidContinue:true,tr39Allowed:true},
  },
  "\u0392": {
    "b": {danger:1,stableDanger:0.4781,cost:0.5219,xidContinue:true,tr39Allowed:true},
  },
  "\u0396": {
    "z": {danger:1,stableDanger:0.7817,cost:0.2183,xidContinue:true,tr39Allowed:true},
  },
  "\u0397": {
    "h": {danger:1,stableDanger:0.3337,cost:0.6663,xidContinue:true,tr39Allowed:true},
  },
  "\u039a": {
    "k": {danger:1,stableDanger:0.3981,cost:0.6019,xidContinue:true,tr39Allowed:true},
  },
  "\u039c": {
    "m": {danger:1,stableDanger:0.1881,cost:0.8119,xidContinue:true,tr39Allowed:true},
  },
  "\u039d": {
    "n": {danger:1,stableDanger:0.375,cost:0.625,xidContinue:true,tr39Allowed:true},
  },
  "\u039f": {
    "o": {danger:1,stableDanger:0.8118,cost:0.1882,xidContinue:true,tr39Allowed:true},
  },
  "\u03a1": {
    "p": {danger:1,stableDanger:0.6236,cost:0.3764,xidContinue:true,tr39Allowed:true},
  },
  "\u03a4": {
    "t": {danger:1,stableDanger:0.6494,cost:0.3506,xidContinue:true,tr39Allowed:true},
  },
  "\u03a5": {
    "y": {danger:1,stableDanger:0.6965,cost:0.3035,xidContinue:true,tr39Allowed:true},
  },
  "\u03a7": {
    "x": {danger:1,stableDanger:0.8154,cost:0.1846,xidContinue:true,tr39Allowed:true},
  },
  "\u03b1": {
    "a": {danger:1,stableDanger:0.4232,cost:0.5768,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u03b9": {
    "i": {danger:1,stableDanger:0.8363,cost:0.1637,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u03bd": {
    "v": {danger:1,stableDanger:0.7899,cost:0.2101,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u03bf": {
    "o": {danger:1,stableDanger:0.8834,cost:0.1166,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u03c1": {
    "p": {danger:1,stableDanger:0.7963,cost:0.2037,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u03f2": {
    "c": {danger:1,stableDanger:1,cost:0,xidContinue:true},
  },
  "\u03f3": {
    "j": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\u0405": {
    "s": {danger:1,stableDanger:0.7724,cost:0.2276,xidContinue:true,tr39Allowed:true},
  },
  "\u0410": {
    "a": {danger:1,stableDanger:0.2523,cost:0.7477,xidContinue:true,tr39Allowed:true},
  },
  "\u0412": {
    "b": {danger:1,stableDanger:0.4804,cost:0.5196,xidContinue:true,tr39Allowed:true},
  },
  "\u0417": {
    "3": {danger:1,stableDanger:0.7579,cost:0.2421,xidContinue:true,tr39Allowed:true},
  },
  "\u041c": {
    "m": {danger:1,stableDanger:0.2143,cost:0.7857,xidContinue:true,tr39Allowed:true},
  },
  "\u041d": {
    "h": {danger:1,stableDanger:0.4957,cost:0.5043,xidContinue:true,tr39Allowed:true},
  },
  "\u041e": {
    "o": {danger:1,stableDanger:0.8139,cost:0.1861,xidContinue:true,tr39Allowed:true},
  },
  "\u0420": {
    "p": {danger:1,stableDanger:0.6398,cost:0.3602,xidContinue:true,tr39Allowed:true},
  },
  "\u0421": {
    "c": {danger:1,stableDanger:0.7335,cost:0.2665,xidContinue:true,tr39Allowed:true},
  },
  "\u0422": {
    "t": {danger:1,stableDanger:0.6546,cost:0.3454,xidContinue:true,tr39Allowed:true},
  },
  "\u0425": {
    "x": {danger:1,stableDanger:0.7816,cost:0.2184,xidContinue:true,tr39Allowed:true},
  },
  "\u0430": {
    "a": {danger:1,stableDanger:0.8627,cost:0.1373,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0435": {
    "e": {danger:1,stableDanger:0.9299,cost:0.0701,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u043e": {
    "o": {danger:1,stableDanger:0.9623,cost:0.0377,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u043f": {
    "n": {danger:1,stableDanger:0.9751,cost:0.0249,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0440": {
    "p": {danger:1,stableDanger:0.9266,cost:0.0734,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0441": {
    "c": {danger:1,stableDanger:0.9066,cost:0.0934,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0443": {
    "y": {danger:1,stableDanger:0.9319,cost:0.0681,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0445": {
    "x": {danger:1,stableDanger:0.9404,cost:0.0596,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0448": {
    "w": {danger:1,stableDanger:0.2486,cost:0.7514,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0455": {
    "s": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0456": {
    "i": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0457": {
    "i": {danger:0.8837,stableDanger:0.8837,cost:0.1163,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0458": {
    "j": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0473": {
    "o": {danger:0.9116,stableDanger:0.8916,cost:0.1084,xidContinue:true,idnaPvalid:true},
  },
  "\u048f": {
    "p": {danger:0.9661,stableDanger:0.9124,cost:0.0876,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u04ae": {
    "y": {danger:1,stableDanger:0.8728,cost:0.1272,xidContinue:true,tr39Allowed:true},
  },
  "\u04af": {
    "y": {danger:1,stableDanger:0.9201,cost:0.0799,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u04bb": {
    "h": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u04c0": {
    "l": {danger:1,stableDanger:0.9646,cost:0.0354,xidContinue:true,tr39Allowed:true},
  },
  "\u04cf": {
    "l": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u04e9": {
    "o": {danger:0.9711,stableDanger:0.8618,cost:0.1382,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u04ff": {
    "x": {danger:0.9656,stableDanger:0.8123,cost:0.1877,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0501": {
    "d": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\u051b": {
    "q": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u051d": {
    "w": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u05c0": {
    "l": {danger:0.9971,stableDanger:0.9945,cost:0.0055,idnaPvalid:true},
  },
  "\u0622": {
    "i": {danger:0.8124,stableDanger:0.804,cost:0.196,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
    "l": {danger:0.891,stableDanger:0.8717,cost:0.1283,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0623": {
    "i": {danger:0.8422,stableDanger:0.8353,cost:0.1647,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
    "l": {danger:0.8449,stableDanger:0.8425,cost:0.1575,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0625": {
    "i": {danger:0.8177,stableDanger:0.8129,cost:0.1871,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
    "l": {danger:0.8994,stableDanger:0.8831,cost:0.1169,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0627": {
    "l": {danger:0.9394,stableDanger:0.935,cost:0.065,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0671": {
    "i": {danger:0.819,stableDanger:0.8164,cost:0.1836,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
    "l": {danger:0.8552,stableDanger:0.8442,cost:0.1558,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0672": {
    "l": {danger:0.8225,stableDanger:0.815,cost:0.185,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0673": {
    "l": {danger:0.8685,stableDanger:0.8493,cost:0.1507,xidContinue:true,idnaPvalid:true},
  },
  "\u0719": {
    "i": {danger:0.7206,stableDanger:0.7206,cost:0.2794,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.7036,stableDanger:0.7036,cost:0.2964,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.7541,stableDanger:0.7541,cost:0.2459,xidContinue:true,idnaPvalid:true},
  },
  "\u074d": {
    "v": {danger:0.777,stableDanger:0.777,cost:0.223,xidContinue:true,idnaPvalid:true},
  },
  "\u07c5": {
    "t": {danger:0.7613,stableDanger:0.7613,cost:0.2387,xidContinue:true,idnaPvalid:true},
  },
  "\u07c6": {
    "h": {danger:0.7317,stableDanger:0.7317,cost:0.2683,xidContinue:true,idnaPvalid:true},
  },
  "\u07ca": {
    "l": {danger:0.9994,stableDanger:0.9994,cost:0.0006,xidContinue:true,idnaPvalid:true},
  },
  "\u07cb": {
    "o": {danger:0.7743,stableDanger:0.7743,cost:0.2257,xidContinue:true,idnaPvalid:true},
  },
  "\u07cd": {
    "a": {danger:0.7872,stableDanger:0.7872,cost:0.2128,xidContinue:true,idnaPvalid:true},
  },
  "\u07ce": {
    "n": {danger:0.7241,stableDanger:0.7241,cost:0.2759,xidContinue:true,idnaPvalid:true},
    "u": {danger:0.9162,stableDanger:0.9162,cost:0.0838,xidContinue:true,idnaPvalid:true},
  },
  "\u07d5": {
    "b": {danger:0.9216,stableDanger:0.9216,cost:0.0784,xidContinue:true,idnaPvalid:true},
    "h": {danger:0.7615,stableDanger:0.7615,cost:0.2385,xidContinue:true,idnaPvalid:true},
  },
  "\u07d7": {
    "i": {danger:0.8238,stableDanger:0.8238,cost:0.1762,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.7086,stableDanger:0.7086,cost:0.2914,xidContinue:true,idnaPvalid:true},
  },
  "\u07e0": {
    "i": {danger:0.8104,stableDanger:0.8104,cost:0.1896,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.79,stableDanger:0.79,cost:0.21,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.7584,stableDanger:0.7584,cost:0.2416,xidContinue:true,idnaPvalid:true},
    "t": {danger:0.8236,stableDanger:0.8236,cost:0.1764,xidContinue:true,idnaPvalid:true},
  },
  "\u080b": {
    "2": {danger:0.7553,stableDanger:0.7553,cost:0.2447,xidContinue:true,idnaPvalid:true},
  },
  "\u0846": {
    "i": {danger:0.8513,stableDanger:0.8513,cost:0.1487,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.8976,stableDanger:0.8976,cost:0.1024,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.9035,stableDanger:0.9035,cost:0.0965,xidContinue:true,idnaPvalid:true},
    "t": {danger:0.7401,stableDanger:0.7401,cost:0.2599,xidContinue:true,idnaPvalid:true},
  },
  "\u084b": {
    "j": {danger:0.7952,stableDanger:0.7952,cost:0.2048,xidContinue:true,idnaPvalid:true},
  },
  "\u084d": {
    "v": {danger:0.8003,stableDanger:0.8003,cost:0.1997,xidContinue:true,idnaPvalid:true},
  },
  "\u09f7": {
    "i": {danger:0.9344,stableDanger:0.9281,cost:0.0719,idnaPvalid:true},
    "j": {danger:0.926,stableDanger:0.9219,cost:0.0781,idnaPvalid:true},
    "l": {danger:0.9792,stableDanger:0.9756,cost:0.0244,idnaPvalid:true},
    "t": {danger:0.7686,stableDanger:0.768,cost:0.232,idnaPvalid:true},
  },
  "\u09f9": {
    "o": {danger:0.8597,stableDanger:0.859,cost:0.141,idnaPvalid:true},
  },
  "\u0b72": {
    "i": {danger:0.9366,stableDanger:0.9285,cost:0.0715,idnaPvalid:true},
    "j": {danger:0.9001,stableDanger:0.8998,cost:0.1002,idnaPvalid:true},
    "l": {danger:0.9765,stableDanger:0.9695,cost:0.0305,idnaPvalid:true},
    "t": {danger:0.7583,stableDanger:0.7568,cost:0.2432,idnaPvalid:true},
  },
  "\u0c79": {
    "i": {danger:0.9157,stableDanger:0.9157,cost:0.0843,idnaPvalid:true},
    "j": {danger:0.8724,stableDanger:0.8724,cost:0.1276,idnaPvalid:true},
    "l": {danger:0.9692,stableDanger:0.9692,cost:0.0308,idnaPvalid:true},
    "t": {danger:0.7307,stableDanger:0.7307,cost:0.2693,idnaPvalid:true},
  },
  "\u1090": {
    "n": {danger:0.7402,stableDanger:0.7402,cost:0.2598,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
    "u": {danger:0.7013,stableDanger:0.7013,cost:0.2987,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u1099": {
    "8": {danger:0.7173,stableDanger:0.7173,cost:0.2827,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u10b6": {
    "n": {danger:0.7497,stableDanger:0.7497,cost:0.2503,xidContinue:true},
  },
  "\u10bd": {
    "s": {danger:0.7286,stableDanger:0.7286,cost:0.2714,xidContinue:true},
  },
  "\u10d5": {
    "8": {danger:0.8252,stableDanger:0.8182,cost:0.1818,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u10d8": {
    "o": {danger:0.7948,stableDanger:0.7926,cost:0.2074,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u10dc": {
    "6": {danger:0.7864,stableDanger:0.7846,cost:0.2154,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u10fc": {
    "6": {danger:0.7449,stableDanger:0.7404,cost:0.2596,xidContinue:true},
  },
  "\u10fd": {
    "8": {danger:0.7233,stableDanger:0.7225,cost:0.2775,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u10ff": {
    "o": {danger:0.8575,stableDanger:0.8531,cost:0.1469,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u12d8": {
    "u": {danger:0.7153,stableDanger:0.7153,cost:0.2847,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u12db": {
    "h": {danger:0.7038,stableDanger:0.7038,cost:0.2962,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u1340": {
    "6": {danger:0.7531,stableDanger:0.7531,cost:0.2469,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u1350": {
    "i": {danger:0.7272,stableDanger:0.7272,cost:0.2728,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
    "j": {danger:0.7192,stableDanger:0.7192,cost:0.2808,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
    "l": {danger:0.7027,stableDanger:0.7027,cost:0.2973,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
    "t": {danger:0.7604,stableDanger:0.7604,cost:0.2396,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u1352": {
    "t": {danger:0.7199,stableDanger:0.7199,cost:0.2801,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u13a5": {
    "i": {danger:0.8967,stableDanger:0.8733,cost:0.1267,xidContinue:true,idnaPvalid:true},
  },
  "\u13be": {
    "e": {danger:0.7715,stableDanger:0.7618,cost:0.2382,xidContinue:true,idnaPvalid:true},
  },
  "\u1424": {
    "o": {danger:0.8559,stableDanger:0.8549,cost:0.1451,xidContinue:true,idnaPvalid:true},
  },
  "\u144a": {
    "i": {danger:0.8308,stableDanger:0.8241,cost:0.1759,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.8115,stableDanger:0.8044,cost:0.1956,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.8699,stableDanger:0.8637,cost:0.1363,xidContinue:true,idnaPvalid:true},
  },
  "\u14ab": {
    "l": {danger:0.8369,stableDanger:0.8236,cost:0.1764,xidContinue:true,idnaPvalid:true},
  },
  "\u14b3": {
    "j": {danger:0.7905,stableDanger:0.7883,cost:0.2117,xidContinue:true,idnaPvalid:true},
  },
  "\u14b5": {
    "j": {danger:0.7928,stableDanger:0.7921,cost:0.2079,xidContinue:true,idnaPvalid:true},
  },
  "\u14bc": {
    "c": {danger:0.8412,stableDanger:0.8382,cost:0.1618,xidContinue:true,idnaPvalid:true},
  },
  "\u14bd": {
    "j": {danger:0.8159,stableDanger:0.8136,cost:0.1864,xidContinue:true,idnaPvalid:true},
  },
  "\u14d1": {
    "u": {danger:0.8458,stableDanger:0.8436,cost:0.1564,xidContinue:true,idnaPvalid:true},
  },
  "\u1506": {
    "s": {danger:0.7342,stableDanger:0.7333,cost:0.2667,xidContinue:true,idnaPvalid:true},
  },
  "\u1601": {
    "v": {danger:0.8497,stableDanger:0.8366,cost:0.1634,xidContinue:true,idnaPvalid:true},
  },
  "\u1627": {
    "c": {danger:0.796,stableDanger:0.7948,cost:0.2052,xidContinue:true,idnaPvalid:true},
  },
  "\u1633": {
    "c": {danger:0.8818,stableDanger:0.8788,cost:0.1212,xidContinue:true,idnaPvalid:true},
  },
  "\u1646": {
    "z": {danger:0.9176,stableDanger:0.9043,cost:0.0957,xidContinue:true,idnaPvalid:true},
  },
  "\u16bd": {
    "i": {danger:0.8221,stableDanger:0.8172,cost:0.1828,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.867,stableDanger:0.8612,cost:0.1388,xidContinue:true,idnaPvalid:true},
  },
  "\u16c2": {
    "i": {danger:0.8195,stableDanger:0.8172,cost:0.1828,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.8636,stableDanger:0.8602,cost:0.1398,xidContinue:true,idnaPvalid:true},
  },
  "\u16cc": {
    "i": {danger:0.8342,stableDanger:0.8309,cost:0.1691,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.8096,stableDanger:0.8007,cost:0.1993,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.8748,stableDanger:0.8721,cost:0.1279,xidContinue:true,idnaPvalid:true},
  },
  "\u16d9": {
    "i": {danger:0.8254,stableDanger:0.8211,cost:0.1789,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.8745,stableDanger:0.87,cost:0.13,xidContinue:true,idnaPvalid:true},
  },
  "\u16e7": {
    "i": {danger:0.8321,stableDanger:0.8289,cost:0.1711,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.808,stableDanger:0.7995,cost:0.2005,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.8742,stableDanger:0.8714,cost:0.1286,xidContinue:true,idnaPvalid:true},
  },
  "\u172a": {
    "7": {danger:0.7802,stableDanger:0.7802,cost:0.2198,xidContinue:true,idnaPvalid:true},
  },
  "\u176a": {
    "o": {danger:0.7996,stableDanger:0.7996,cost:0.2004,xidContinue:true,idnaPvalid:true},
  },
  "\u17f2": {
    "i": {danger:0.8931,stableDanger:0.8915,cost:0.1085,idnaPvalid:true},
    "j": {danger:0.8528,stableDanger:0.8523,cost:0.1477,idnaPvalid:true},
    "l": {danger:0.949,stableDanger:0.9469,cost:0.0531,idnaPvalid:true},
    "t": {danger:0.7383,stableDanger:0.737,cost:0.263,idnaPvalid:true},
  },
  "\u17f4": {
    "v": {danger:0.9536,stableDanger:0.951,cost:0.049,idnaPvalid:true},
  },
  "\u18d8": {
    "r": {danger:0.8439,stableDanger:0.8399,cost:0.1601,xidContinue:true,idnaPvalid:true},
  },
  "\u18f3": {
    "l": {danger:0.7518,stableDanger:0.7504,cost:0.2496,xidContinue:true,idnaPvalid:true},
  },
  "\u18f4": {
    "r": {danger:0.8152,stableDanger:0.8142,cost:0.1858,xidContinue:true,idnaPvalid:true},
  },
  "\u1901": {
    "z": {danger:0.7641,stableDanger:0.7641,cost:0.2359,xidContinue:true,idnaPvalid:true},
  },
  "\u190f": {
    "z": {danger:0.7139,stableDanger:0.7139,cost:0.2861,xidContinue:true,idnaPvalid:true},
  },
  "\u191a": {
    "q": {danger:0.7218,stableDanger:0.7218,cost:0.2782,xidContinue:true,idnaPvalid:true},
  },
  "\u1946": {
    "o": {danger:0.8254,stableDanger:0.8254,cost:0.1746,xidContinue:true,idnaPvalid:true},
  },
  "\u1949": {
    "s": {danger:0.8115,stableDanger:0.8115,cost:0.1885,xidContinue:true,idnaPvalid:true},
  },
  "\u194a": {
    "x": {danger:0.7677,stableDanger:0.7677,cost:0.2323,xidContinue:true,idnaPvalid:true},
  },
  "\u194e": {
    "v": {danger:0.7619,stableDanger:0.7619,cost:0.2381,xidContinue:true,idnaPvalid:true},
  },
  "\u1952": {
    "n": {danger:0.7959,stableDanger:0.7959,cost:0.2041,xidContinue:true,idnaPvalid:true},
  },
  "\u1959": {
    "n": {danger:0.703,stableDanger:0.703,cost:0.297,xidContinue:true,idnaPvalid:true},
    "u": {danger:0.7903,stableDanger:0.7903,cost:0.2097,xidContinue:true,idnaPvalid:true},
  },
  "\u195d": {
    "o": {danger:0.7337,stableDanger:0.7337,cost:0.2663,xidContinue:true,idnaPvalid:true},
  },
  "\u1963": {
    "f": {danger:0.7518,stableDanger:0.7518,cost:0.2482,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.7361,stableDanger:0.7361,cost:0.2639,xidContinue:true,idnaPvalid:true},
  },
  "\u1974": {
    "c": {danger:0.766,stableDanger:0.766,cost:0.234,xidContinue:true,idnaPvalid:true},
  },
  "\u1985": {
    "o": {danger:0.8649,stableDanger:0.8649,cost:0.1351,xidContinue:true,idnaPvalid:true},
  },
  "\u1986": {
    "6": {danger:0.7222,stableDanger:0.7222,cost:0.2778,xidContinue:true,idnaPvalid:true},
  },
  "\u199e": {
    "o": {danger:0.7292,stableDanger:0.7292,cost:0.2708,xidContinue:true,idnaPvalid:true},
  },
  "\u19a2": {
    "c": {danger:0.7194,stableDanger:0.7194,cost:0.2806,xidContinue:true,idnaPvalid:true},
    "o": {danger:0.8512,stableDanger:0.8512,cost:0.1488,xidContinue:true,idnaPvalid:true},
  },
  "\u19b1": {
    "o": {danger:0.7188,stableDanger:0.7188,cost:0.2812,xidContinue:true,idnaPvalid:true},
  },
  "\u19c9": {
    "e": {danger:0.7315,stableDanger:0.7315,cost:0.2685,xidContinue:true,idnaPvalid:true},
  },
  "\u19d0": {
    "o": {danger:0.7292,stableDanger:0.7292,cost:0.2708,xidContinue:true,idnaPvalid:true},
  },
  "\u19d1": {
    "o": {danger:0.7188,stableDanger:0.7188,cost:0.2812,xidContinue:true,idnaPvalid:true},
  },
  "\u19d2": {
    "j": {danger:0.759,stableDanger:0.759,cost:0.241,xidContinue:true,idnaPvalid:true},
  },
  "\u1a24": {
    "6": {danger:0.7461,stableDanger:0.7461,cost:0.2539,xidContinue:true,idnaPvalid:true},
  },
  "\u1a37": {
    "o": {danger:0.8066,stableDanger:0.8066,cost:0.1934,xidContinue:true,idnaPvalid:true},
  },
  "\u1a92": {
    "r": {danger:0.7403,stableDanger:0.7403,cost:0.2597,xidContinue:true,idnaPvalid:true},
  },
  "\u1b50": {
    "c": {danger:0.7488,stableDanger:0.7488,cost:0.2512,xidContinue:true,idnaPvalid:true},
    "o": {danger:0.8102,stableDanger:0.8102,cost:0.1898,xidContinue:true,idnaPvalid:true},
  },
  "\u1c17": {
    "o": {danger:0.7246,stableDanger:0.7246,cost:0.2754,xidContinue:true,idnaPvalid:true},
  },
  "\u1c1e": {
    "x": {danger:0.8103,stableDanger:0.8103,cost:0.1897,xidContinue:true,idnaPvalid:true},
  },
  "\u1c40": {
    "o": {danger:0.7219,stableDanger:0.7219,cost:0.2781,xidContinue:true,idnaPvalid:true},
  },
  "\u1c50": {
    "d": {danger:0.7171,stableDanger:0.7171,cost:0.2829,xidContinue:true,idnaPvalid:true},
  },
  "\u1c5b": {
    "o": {danger:0.719,stableDanger:0.719,cost:0.281,xidContinue:true,idnaPvalid:true},
  },
  "\u1c60": {
    "b": {danger:0.7172,stableDanger:0.7172,cost:0.2828,xidContinue:true,idnaPvalid:true},
  },
  "\u1c67": {
    "q": {danger:0.772,stableDanger:0.772,cost:0.228,xidContinue:true,idnaPvalid:true},
  },
  "\u1c95": {
    "8": {danger:0.8264,stableDanger:0.8172,cost:0.1828,xidContinue:true,tr39Allowed:true},
  },
  "\u1cab": {
    "d": {danger:0.7418,stableDanger:0.7407,cost:0.2593,xidContinue:true,tr39Allowed:true},
  },
  "\u1cae": {
    "b": {danger:0.7558,stableDanger:0.7525,cost:0.2475,xidContinue:true,tr39Allowed:true},
  },
  "\u1cbd": {
    "s": {danger:0.8398,stableDanger:0.8383,cost:0.1617,xidContinue:true,tr39Allowed:true},
  },
  "\u1cbf": {
    "o": {danger:0.8222,stableDanger:0.8186,cost:0.1814,xidContinue:true,tr39Allowed:true},
  },
  "\u1d04": {
    "c": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\u1d09": {
    "i": {danger:0.9019,stableDanger:0.8923,cost:0.1077,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.9436,stableDanger:0.9427,cost:0.0573,xidContinue:true,idnaPvalid:true},
  },
  "\u1d0f": {
    "o": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\u1d11": {
    "o": {danger:1,stableDanger:0.7038,cost:0.2962,xidContinue:true,idnaPvalid:true},
  },
  "\u1d20": {
    "v": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\u1d21": {
    "w": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\u1d22": {
    "z": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\u1d35": {
    "l": {danger:0.9557,stableDanger:0.9502,cost:0.0498,xidContinue:true},
  },
  "\u1d3c": {
    "o": {danger:0.9265,stableDanger:0.9125,cost:0.0875,xidContinue:true},
  },
  "\u1d42": {
    "w": {danger:0.9051,stableDanger:0.8856,cost:0.1144,xidContinue:true},
  },
  "\u1d43": {
    "a": {danger:0.9712,stableDanger:0.9504,cost:0.0496,xidContinue:true},
  },
  "\u1d47": {
    "b": {danger:0.9589,stableDanger:0.9589,cost:0.0411,xidContinue:true},
    "h": {danger:0.8964,stableDanger:0.8632,cost:0.1368,xidContinue:true},
  },
  "\u1d48": {
    "d": {danger:0.9589,stableDanger:0.9445,cost:0.0555,xidContinue:true},
  },
  "\u1d49": {
    "e": {danger:0.9369,stableDanger:0.9361,cost:0.0639,xidContinue:true},
  },
  "\u1d4d": {
    "g": {danger:0.9313,stableDanger:0.9307,cost:0.0693,xidContinue:true},
  },
  "\u1d4e": {
    "l": {danger:0.9245,stableDanger:0.9243,cost:0.0757,xidContinue:true,idnaPvalid:true},
  },
  "\u1d4f": {
    "k": {danger:0.9694,stableDanger:0.966,cost:0.034,xidContinue:true},
  },
  "\u1d50": {
    "m": {danger:0.9324,stableDanger:0.9323,cost:0.0677,xidContinue:true},
  },
  "\u1d52": {
    "o": {danger:0.9556,stableDanger:0.9525,cost:0.0475,xidContinue:true},
  },
  "\u1d56": {
    "p": {danger:0.9098,stableDanger:0.8985,cost:0.1015,xidContinue:true},
  },
  "\u1d57": {
    "t": {danger:0.9468,stableDanger:0.9427,cost:0.0573,xidContinue:true},
  },
  "\u1d58": {
    "u": {danger:0.944,stableDanger:0.9331,cost:0.0669,xidContinue:true},
  },
  "\u1d5b": {
    "v": {danger:0.9464,stableDanger:0.941,cost:0.059,xidContinue:true},
  },
  "\u1d62": {
    "i": {danger:0.9734,stableDanger:0.9663,cost:0.0337,xidContinue:true},
    "l": {danger:0.9303,stableDanger:0.9198,cost:0.0802,xidContinue:true},
  },
  "\u1d63": {
    "r": {danger:0.9648,stableDanger:0.9472,cost:0.0528,xidContinue:true},
  },
  "\u1d64": {
    "u": {danger:0.9443,stableDanger:0.9413,cost:0.0587,xidContinue:true},
  },
  "\u1d65": {
    "v": {danger:0.9593,stableDanger:0.9501,cost:0.0499,xidContinue:true},
  },
  "\u1d74": {
    "s": {danger:0.8869,stableDanger:0.8819,cost:0.1181,xidContinue:true,idnaPvalid:true},
  },
  "\u1d85": {
    "l": {danger:0.8517,stableDanger:0.8332,cost:0.1668,xidContinue:true,idnaPvalid:true},
  },
  "\u1d88": {
    "p": {danger:0.9104,stableDanger:0.9052,cost:0.0948,xidContinue:true,idnaPvalid:true},
  },
  "\u1d9c": {
    "c": {danger:0.9553,stableDanger:0.942,cost:0.058,xidContinue:true},
  },
  "\u1da0": {
    "f": {danger:0.9434,stableDanger:0.9386,cost:0.0614,xidContinue:true},
  },
  "\u1da4": {
    "i": {danger:0.8702,stableDanger:0.8702,cost:0.1298,xidContinue:true},
  },
  "\u1da8": {
    "j": {danger:0.9213,stableDanger:0.9213,cost:0.0787,xidContinue:true},
  },
  "\u1daa": {
    "l": {danger:0.8617,stableDanger:0.8509,cost:0.1491,xidContinue:true},
  },
  "\u1db4": {
    "i": {danger:0.8442,stableDanger:0.8266,cost:0.1734,xidContinue:true},
    "l": {danger:0.8574,stableDanger:0.8572,cost:0.1428,xidContinue:true},
  },
  "\u1dbb": {
    "z": {danger:0.9286,stableDanger:0.925,cost:0.075,xidContinue:true},
  },
  "\u1e2d": {
    "i": {danger:0.8402,stableDanger:0.8155,cost:0.1845,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u1e37": {
    "i": {danger:0.8888,stableDanger:0.8632,cost:0.1368,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
    "l": {danger:0.9303,stableDanger:0.9184,cost:0.0816,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u1e39": {
    "l": {danger:0.9126,stableDanger:0.8651,cost:0.1349,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u1e3b": {
    "l": {danger:0.9255,stableDanger:0.9165,cost:0.0835,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u1e3d": {
    "l": {danger:0.9185,stableDanger:0.8793,cost:0.1207,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u1ec8": {
    "i": {danger:0.9103,stableDanger:0.9103,cost:0.0897,xidContinue:true,tr39Allowed:true},
    "l": {danger:0.924,stableDanger:0.924,cost:0.076,xidContinue:true,tr39Allowed:true},
  },
  "\u1ec9": {
    "i": {danger:0.9395,stableDanger:0.9281,cost:0.0719,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
    "l": {danger:0.9331,stableDanger:0.8931,cost:0.1069,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u1eca": {
    "l": {danger:0.958,stableDanger:0.946,cost:0.054,xidContinue:true,tr39Allowed:true},
  },
  "\u1ecb": {
    "i": {danger:0.8914,stableDanger:0.8914,cost:0.1086,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
    "l": {danger:0.9343,stableDanger:0.8864,cost:0.1136,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u1ef5": {
    "y": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u2071": {
    "i": {danger:0.9401,stableDanger:0.9398,cost:0.0602,xidContinue:true},
    "l": {danger:0.8899,stableDanger:0.8805,cost:0.1195,xidContinue:true},
  },
  "\u2074": {
    "4": {danger:0.9614,stableDanger:0.9306,cost:0.0694},
  },
  "\u2075": {
    "5": {danger:0.9414,stableDanger:0.907,cost:0.093},
  },
  "\u2076": {
    "6": {danger:0.9507,stableDanger:0.9221,cost:0.0779},
  },
  "\u2077": {
    "7": {danger:0.9434,stableDanger:0.9312,cost:0.0688},
  },
  "\u2078": {
    "8": {danger:0.9531,stableDanger:0.9312,cost:0.0688},
  },
  "\u2079": {
    "9": {danger:0.9429,stableDanger:0.905,cost:0.095},
  },
  "\u207f": {
    "n": {danger:0.9927,stableDanger:0.9248,cost:0.0752,xidContinue:true},
  },
  "\u2084": {
    "4": {danger:0.9358,stableDanger:0.9358,cost:0.0642},
  },
  "\u2085": {
    "5": {danger:0.9224,stableDanger:0.9224,cost:0.0776},
  },
  "\u2086": {
    "6": {danger:0.9196,stableDanger:0.8885,cost:0.1115},
  },
  "\u2087": {
    "7": {danger:0.9614,stableDanger:0.9455,cost:0.0545},
  },
  "\u2088": {
    "8": {danger:0.9332,stableDanger:0.9031,cost:0.0969},
  },
  "\u2089": {
    "9": {danger:0.9438,stableDanger:0.8824,cost:0.1176},
  },
  "\u2090": {
    "a": {danger:0.9361,stableDanger:0.9156,cost:0.0844,xidContinue:true},
  },
  "\u2091": {
    "e": {danger:0.9672,stableDanger:0.9399,cost:0.0601,xidContinue:true},
  },
  "\u2092": {
    "o": {danger:0.9683,stableDanger:0.9661,cost:0.0339,xidContinue:true},
  },
  "\u2093": {
    "x": {danger:0.9759,stableDanger:0.9472,cost:0.0528,xidContinue:true},
  },
  "\u212a": {
    "k": {danger:1,stableDanger:0.4605,cost:0.5395,xidContinue:true},
  },
  "\u2164": {
    "v": {danger:1,stableDanger:0.8086,cost:0.1914,xidContinue:true},
  },
  "\u2169": {
    "x": {danger:1,stableDanger:0.7901,cost:0.2099,xidContinue:true},
  },
  "\u216c": {
    "l": {danger:1,stableDanger:0.4866,cost:0.5134,xidContinue:true},
  },
  "\u216d": {
    "c": {danger:1,stableDanger:0.7519,cost:0.2481,xidContinue:true},
  },
  "\u216e": {
    "d": {danger:1,stableDanger:0.387,cost:0.613,xidContinue:true},
  },
  "\u216f": {
    "m": {danger:1,stableDanger:0.2644,cost:0.7356,xidContinue:true},
  },
  "\u2170": {
    "i": {danger:1,stableDanger:0.9623,cost:0.0377,xidContinue:true},
  },
  "\u2174": {
    "v": {danger:1,stableDanger:0.9518,cost:0.0482,xidContinue:true},
  },
  "\u2179": {
    "x": {danger:1,stableDanger:0.9483,cost:0.0517,xidContinue:true},
  },
  "\u217c": {
    "l": {danger:1,stableDanger:1,cost:0,xidContinue:true},
  },
  "\u217d": {
    "c": {danger:1,stableDanger:1,cost:0,xidContinue:true},
  },
  "\u217e": {
    "d": {danger:1,stableDanger:1,cost:0,xidContinue:true},
  },
  "\u217f": {
    "m": {danger:1,stableDanger:1,cost:0,xidContinue:true},
  },
  "\u2223": {
    "l": {danger:0.9642,stableDanger:0.9084,cost:0.0916,idnaPvalid:true},
  },
  "\u2228": {
    "v": {danger:1,stableDanger:0.7397,cost:0.2603,idnaPvalid:true},
  },
  "\u23fd": {
    "l": {danger:0.9949,stableDanger:0.9359,cost:0.0641,idnaPvalid:true},
  },
  "\u2c0f": {
    "m": {danger:0.8639,stableDanger:0.8639,cost:0.1361,xidContinue:true},
  },
  "\u2c13": {
    "b": {danger:0.7759,stableDanger:0.7759,cost:0.2241,xidContinue:true},
  },
  "\u2c22": {
    "o": {danger:0.7314,stableDanger:0.7314,cost:0.2686,xidContinue:true},
  },
  "\u2c2c": {
    "j": {danger:0.7361,stableDanger:0.7361,cost:0.2639,xidContinue:true},
  },
  "\u2c43": {
    "b": {danger:0.7944,stableDanger:0.7944,cost:0.2056,xidContinue:true,idnaPvalid:true},
  },
  "\u2c7a": {
    "o": {danger:0.7229,stableDanger:0.7209,cost:0.2791,xidContinue:true,idnaPvalid:true},
  },
  "\u2c8f": {
    "h": {danger:0.7928,stableDanger:0.7928,cost:0.2072,xidContinue:true,idnaPvalid:true},
  },
  "\u2c91": {
    "e": {danger:0.8968,stableDanger:0.8968,cost:0.1032,xidContinue:true,idnaPvalid:true},
    "o": {danger:0.7017,stableDanger:0.7017,cost:0.2983,xidContinue:true,idnaPvalid:true},
  },
  "\u2c92": {
    "l": {danger:0.9836,stableDanger:0.9667,cost:0.0333,xidContinue:true},
  },
  "\u2c93": {
    "i": {danger:0.8616,stableDanger:0.8336,cost:0.1664,xidContinue:true,idnaPvalid:true},
  },
  "\u2c9b": {
    "n": {danger:0.7174,stableDanger:0.7174,cost:0.2826,xidContinue:true,idnaPvalid:true},
  },
  "\u2ca1": {
    "n": {danger:0.7961,stableDanger:0.7961,cost:0.2039,xidContinue:true,idnaPvalid:true},
  },
  "\u2cad": {
    "x": {danger:0.925,stableDanger:0.925,cost:0.075,xidContinue:true,idnaPvalid:true},
  },
  "\u2cc5": {
    "3": {danger:0.7918,stableDanger:0.7918,cost:0.2082,xidContinue:true,idnaPvalid:true},
  },
  "\u2cc6": {
    "7": {danger:0.7509,stableDanger:0.7509,cost:0.2491,xidContinue:true},
  },
  "\u2cc7": {
    "7": {danger:0.7482,stableDanger:0.7482,cost:0.2518,xidContinue:true,idnaPvalid:true},
  },
  "\u2cd8": {
    "u": {danger:0.7676,stableDanger:0.7676,cost:0.2324,xidContinue:true},
  },
  "\u2cd9": {
    "u": {danger:0.8717,stableDanger:0.8717,cost:0.1283,xidContinue:true,idnaPvalid:true},
  },
  "\u2cdf": {
    "r": {danger:0.7261,stableDanger:0.7261,cost:0.2739,xidContinue:true,idnaPvalid:true},
  },
  "\u2d30": {
    "o": {danger:0.8317,stableDanger:0.8317,cost:0.1683,xidContinue:true,idnaPvalid:true},
  },
  "\u2d31": {
    "e": {danger:0.7142,stableDanger:0.7142,cost:0.2858,xidContinue:true,idnaPvalid:true},
  },
  "\u2d33": {
    "x": {danger:0.8153,stableDanger:0.8153,cost:0.1847,xidContinue:true,idnaPvalid:true},
  },
  "\u2d34": {
    "x": {danger:0.8136,stableDanger:0.8136,cost:0.1864,xidContinue:true,idnaPvalid:true},
  },
  "\u2d35": {
    "x": {danger:0.7868,stableDanger:0.7868,cost:0.2132,xidContinue:true,idnaPvalid:true},
  },
  "\u2d36": {
    "i": {danger:0.7002,stableDanger:0.7002,cost:0.2998,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.7211,stableDanger:0.7211,cost:0.2789,xidContinue:true,idnaPvalid:true},
  },
  "\u2d42": {
    "i": {danger:0.8087,stableDanger:0.8087,cost:0.1913,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.7954,stableDanger:0.7954,cost:0.2046,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.792,stableDanger:0.792,cost:0.208,xidContinue:true,idnaPvalid:true},
  },
  "\u2d4a": {
    "l": {danger:0.7842,stableDanger:0.7842,cost:0.2158,xidContinue:true,idnaPvalid:true},
    "t": {danger:0.834,stableDanger:0.834,cost:0.166,xidContinue:true,idnaPvalid:true},
  },
  "\u2d4f": {
    "l": {danger:0.9861,stableDanger:0.9677,cost:0.0323,xidContinue:true,idnaPvalid:true},
  },
  "\u2d51": {
    "i": {danger:0.8321,stableDanger:0.8321,cost:0.1679,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.8326,stableDanger:0.8326,cost:0.1674,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.875,stableDanger:0.875,cost:0.125,xidContinue:true,idnaPvalid:true},
    "t": {danger:0.7075,stableDanger:0.7075,cost:0.2925,xidContinue:true,idnaPvalid:true},
  },
  "\u2d61": {
    "u": {danger:0.8309,stableDanger:0.8309,cost:0.1691,xidContinue:true,idnaPvalid:true},
  },
  "\ua4d5": {
    "i": {danger:0.7979,stableDanger:0.7978,cost:0.2022,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.861,stableDanger:0.8606,cost:0.1394,xidContinue:true,idnaPvalid:true},
  },
  "\ua4f2": {
    "l": {danger:0.9804,stableDanger:0.9644,cost:0.0356,xidContinue:true,idnaPvalid:true},
  },
  "\ua4f5": {
    "n": {danger:0.7434,stableDanger:0.7399,cost:0.2601,xidContinue:true,idnaPvalid:true},
  },
  "\ua50b": {
    "i": {danger:0.8141,stableDanger:0.8141,cost:0.1859,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.8424,stableDanger:0.8424,cost:0.1576,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.7183,stableDanger:0.7183,cost:0.2817,xidContinue:true,idnaPvalid:true},
    "t": {danger:0.8045,stableDanger:0.8045,cost:0.1955,xidContinue:true,idnaPvalid:true},
  },
  "\ua543": {
    "6": {danger:0.7562,stableDanger:0.7562,cost:0.2438,xidContinue:true,idnaPvalid:true},
  },
  "\ua544": {
    "6": {danger:0.7032,stableDanger:0.7032,cost:0.2968,xidContinue:true,idnaPvalid:true},
  },
  "\ua56f": {
    "i": {danger:0.722,stableDanger:0.722,cost:0.278,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.7297,stableDanger:0.7297,cost:0.2703,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.7714,stableDanger:0.7714,cost:0.2286,xidContinue:true,idnaPvalid:true},
    "t": {danger:0.8301,stableDanger:0.8301,cost:0.1699,xidContinue:true,idnaPvalid:true},
  },
  "\ua576": {
    "8": {danger:0.7654,stableDanger:0.7654,cost:0.2346,xidContinue:true,idnaPvalid:true},
    "s": {danger:0.7129,stableDanger:0.7129,cost:0.2871,xidContinue:true,idnaPvalid:true},
  },
  "\ua5cf": {
    "8": {danger:0.7141,stableDanger:0.7141,cost:0.2859,xidContinue:true,idnaPvalid:true},
  },
  "\ua621": {
    "i": {danger:0.8973,stableDanger:0.8973,cost:0.1027,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.8703,stableDanger:0.8703,cost:0.1297,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.9627,stableDanger:0.9627,cost:0.0373,xidContinue:true,idnaPvalid:true},
    "t": {danger:0.7258,stableDanger:0.7258,cost:0.2742,xidContinue:true,idnaPvalid:true},
  },
  "\ua628": {
    "8": {danger:0.7265,stableDanger:0.7265,cost:0.2735,xidContinue:true,idnaPvalid:true},
  },
  "\ua6c9": {
    "z": {danger:0.7724,stableDanger:0.7724,cost:0.2276,xidContinue:true,idnaPvalid:true},
  },
  "\ua6d6": {
    "b": {danger:0.7809,stableDanger:0.7809,cost:0.2191,xidContinue:true,idnaPvalid:true},
  },
  "\ua6ec": {
    "j": {danger:0.7103,stableDanger:0.7103,cost:0.2897,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.7812,stableDanger:0.7812,cost:0.2188,xidContinue:true,idnaPvalid:true},
  },
  "\ua731": {
    "s": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\ua743": {
    "k": {danger:0.8592,stableDanger:0.8592,cost:0.1408,xidContinue:true,idnaPvalid:true},
  },
  "\ua749": {
    "i": {danger:0.7409,stableDanger:0.7409,cost:0.2591,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.786,stableDanger:0.786,cost:0.214,xidContinue:true,idnaPvalid:true},
  },
  "\ua76c": {
    "f": {danger:0.7236,stableDanger:0.7236,cost:0.2764,xidContinue:true},
  },
  "\ua76e": {
    "9": {danger:0.964,stableDanger:0.964,cost:0.036,xidContinue:true},
  },
  "\ua76f": {
    "9": {danger:0.9583,stableDanger:0.9583,cost:0.0417,xidContinue:true,idnaPvalid:true},
  },
  "\ua770": {
    "9": {danger:0.8288,stableDanger:0.8288,cost:0.1712,xidContinue:true},
  },
  "\ua771": {
    "d": {danger:0.985,stableDanger:0.985,cost:0.015,xidContinue:true,idnaPvalid:true},
  },
  "\ua779": {
    "o": {danger:0.7814,stableDanger:0.7814,cost:0.2186,xidContinue:true},
  },
  "\ua781": {
    "i": {danger:0.9222,stableDanger:0.9222,cost:0.0778,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.9856,stableDanger:0.9856,cost:0.0144,xidContinue:true,idnaPvalid:true},
  },
  "\ua78b": {
    "l": {danger:0.7822,stableDanger:0.7796,cost:0.2204,xidContinue:true},
  },
  "\ua7a1": {
    "g": {danger:0.8138,stableDanger:0.8138,cost:0.1862,xidContinue:true,idnaPvalid:true},
  },
  "\ua7a5": {
    "n": {danger:0.7087,stableDanger:0.7087,cost:0.2913,xidContinue:true,idnaPvalid:true},
  },
  "\ua7a9": {
    "s": {danger:0.7327,stableDanger:0.7327,cost:0.2673,xidContinue:true,idnaPvalid:true},
  },
  "\ua7fe": {
    "i": {danger:0.935,stableDanger:0.935,cost:0.065,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.9983,stableDanger:0.9983,cost:0.0017,xidContinue:true,idnaPvalid:true},
  },
  "\ua830": {
    "i": {danger:0.8849,stableDanger:0.8849,cost:0.1151,idnaPvalid:true},
    "j": {danger:0.859,stableDanger:0.8576,cost:0.1424,idnaPvalid:true},
    "l": {danger:0.9225,stableDanger:0.9225,cost:0.0775,idnaPvalid:true},
    "t": {danger:0.7469,stableDanger:0.7449,cost:0.2551,idnaPvalid:true},
  },
  "\ua872": {
    "f": {danger:0.7115,stableDanger:0.7115,cost:0.2885,xidContinue:true,idnaPvalid:true},
    "t": {danger:0.7039,stableDanger:0.7039,cost:0.2961,xidContinue:true,idnaPvalid:true},
  },
  "\ua89d": {
    "o": {danger:0.7454,stableDanger:0.7454,cost:0.2546,xidContinue:true,idnaPvalid:true},
  },
  "\ua900": {
    "c": {danger:0.7243,stableDanger:0.7243,cost:0.2757,xidContinue:true,idnaPvalid:true},
  },
  "\ua902": {
    "v": {danger:0.7094,stableDanger:0.7094,cost:0.2906,xidContinue:true,idnaPvalid:true},
  },
  "\ua908": {
    "u": {danger:0.7527,stableDanger:0.7527,cost:0.2473,xidContinue:true,idnaPvalid:true},
  },
  "\ua909": {
    "u": {danger:0.7801,stableDanger:0.7801,cost:0.2199,xidContinue:true,idnaPvalid:true},
  },
  "\ua90d": {
    "c": {danger:0.7531,stableDanger:0.7531,cost:0.2469,xidContinue:true,idnaPvalid:true},
  },
  "\ua91a": {
    "n": {danger:0.7017,stableDanger:0.7017,cost:0.2983,xidContinue:true,idnaPvalid:true},
  },
  "\ua91b": {
    "m": {danger:0.7167,stableDanger:0.7167,cost:0.2833,xidContinue:true,idnaPvalid:true},
  },
  "\ua9d0": {
    "c": {danger:0.7385,stableDanger:0.7385,cost:0.2615,xidContinue:true,idnaPvalid:true},
    "o": {danger:0.9577,stableDanger:0.9577,cost:0.0423,xidContinue:true,idnaPvalid:true},
  },
  "\uaa50": {
    "c": {danger:0.7011,stableDanger:0.7011,cost:0.2989,xidContinue:true,idnaPvalid:true},
    "o": {danger:0.9016,stableDanger:0.9016,cost:0.0984,xidContinue:true,idnaPvalid:true},
  },
  "\uaa92": {
    "n": {danger:0.7569,stableDanger:0.7569,cost:0.2431,xidContinue:true,idnaPvalid:true},
  },
  "\uaab1": {
    "i": {danger:0.7884,stableDanger:0.7884,cost:0.2116,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.7633,stableDanger:0.7633,cost:0.2367,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.8237,stableDanger:0.8237,cost:0.1763,xidContinue:true,idnaPvalid:true},
  },
  "\uab75": {
    "i": {danger:0.7844,stableDanger:0.7844,cost:0.2156,xidContinue:true},
  },
  "\uab83": {
    "w": {danger:0.9116,stableDanger:0.9074,cost:0.0926,xidContinue:true},
  },
  "\uab8e": {
    "e": {danger:0.8676,stableDanger:0.8559,cost:0.1441,xidContinue:true},
  },
  "\uab93": {
    "z": {danger:0.9782,stableDanger:0.9693,cost:0.0307,xidContinue:true},
  },
  "\uaba5": {
    "s": {danger:0.7848,stableDanger:0.7774,cost:0.2226,xidContinue:true},
  },
  "\uaba9": {
    "v": {danger:0.9483,stableDanger:0.9473,cost:0.0527,xidContinue:true},
  },
  "\uabaa": {
    "s": {danger:0.9046,stableDanger:0.8942,cost:0.1058,xidContinue:true},
  },
  "\uabaf": {
    "c": {danger:0.8631,stableDanger:0.8569,cost:0.1431,xidContinue:true},
  },
  "\uabf0": {
    "o": {danger:0.7863,stableDanger:0.7863,cost:0.2137,xidContinue:true,idnaPvalid:true},
  },
  "\ufb50": {
    "i": {danger:0.8189,stableDanger:0.8164,cost:0.1836,xidContinue:true},
    "l": {danger:0.8552,stableDanger:0.8442,cost:0.1558,xidContinue:true},
  },
  "\ufe81": {
    "l": {danger:0.891,stableDanger:0.8678,cost:0.1322,xidContinue:true},
  },
  "\ufe83": {
    "i": {danger:0.8422,stableDanger:0.8339,cost:0.1661,xidContinue:true},
    "l": {danger:0.8449,stableDanger:0.842,cost:0.158,xidContinue:true},
  },
  "\ufe87": {
    "i": {danger:0.8411,stableDanger:0.8341,cost:0.1659,xidContinue:true},
    "l": {danger:0.9002,stableDanger:0.9,cost:0.1,xidContinue:true},
  },
  "\ufe8d": {
    "l": {danger:0.9555,stableDanger:0.9191,cost:0.0809,xidContinue:true},
  },
  "\uff14": {
    "4": {danger:0.9269,stableDanger:0.9269,cost:0.0731,xidContinue:true},
  },
  "\uff15": {
    "5": {danger:0.9866,stableDanger:0.95,cost:0.05,xidContinue:true},
  },
  "\uff16": {
    "6": {danger:0.924,stableDanger:0.8993,cost:0.1007,xidContinue:true},
  },
  "\uff17": {
    "7": {danger:0.9872,stableDanger:0.9758,cost:0.0242,xidContinue:true},
  },
  "\uff18": {
    "8": {danger:0.9127,stableDanger:0.8884,cost:0.1116,xidContinue:true},
  },
  "\uff19": {
    "9": {danger:0.9069,stableDanger:0.9006,cost:0.0994,xidContinue:true},
  },
  "\uff36": {
    "v": {danger:0.9099,stableDanger:0.9094,cost:0.0906,xidContinue:true},
  },
  "\uff42": {
    "b": {danger:0.9999,stableDanger:0.9639,cost:0.0361,xidContinue:true},
  },
  "\uff44": {
    "d": {danger:0.9719,stableDanger:0.9573,cost:0.0427,xidContinue:true},
  },
  "\uff46": {
    "f": {danger:0.961,stableDanger:0.9269,cost:0.0731,xidContinue:true},
  },
  "\uff49": {
    "i": {danger:0.9811,stableDanger:0.9215,cost:0.0785,xidContinue:true},
  },
  "\uff4c": {
    "l": {danger:0.9892,stableDanger:0.9576,cost:0.0424,xidContinue:true},
  },
  "\uff4e": {
    "n": {danger:0.9606,stableDanger:0.9376,cost:0.0624,xidContinue:true},
  },
  "\uff52": {
    "r": {danger:0.9872,stableDanger:0.9183,cost:0.0817,xidContinue:true},
  },
  "\uff54": {
    "t": {danger:0.985,stableDanger:0.8935,cost:0.1065,xidContinue:true},
  },
  "\uff55": {
    "u": {danger:0.9571,stableDanger:0.9309,cost:0.0691,xidContinue:true},
  },
  "\uff57": {
    "w": {danger:0.9539,stableDanger:0.9371,cost:0.0629,xidContinue:true},
  },
  "\uff5a": {
    "z": {danger:1,stableDanger:0.9685,cost:0.0315,xidContinue:true},
  },
  "\ud800\udc05": {
    "f": {danger:0.7462,stableDanger:0.7462,cost:0.2538,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\udc2b": {
    "l": {danger:0.7163,stableDanger:0.7163,cost:0.2837,xidContinue:true,idnaPvalid:true},
    "t": {danger:0.7596,stableDanger:0.7596,cost:0.2404,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\udc35": {
    "t": {danger:0.7397,stableDanger:0.7397,cost:0.2603,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\udc4c": {
    "b": {danger:0.7037,stableDanger:0.7037,cost:0.2963,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\udd52": {
    "h": {danger:0.7242,stableDanger:0.7242,cost:0.2758,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\ude8a": {
    "l": {danger:0.9691,stableDanger:0.9486,cost:0.0514,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\udec1": {
    "x": {danger:0.7915,stableDanger:0.7861,cost:0.2139,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\udeea": {
    "l": {danger:0.8023,stableDanger:0.8023,cost:0.1977,idnaPvalid:true},
  },
  "\ud800\udf09": {
    "l": {danger:0.987,stableDanger:0.9709,cost:0.0291,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\udf20": {
    "l": {danger:0.9983,stableDanger:0.9983,cost:0.0017,idnaPvalid:true},
  },
  "\ud800\udf34": {
    "e": {danger:0.7105,stableDanger:0.7105,cost:0.2895,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\udf36": {
    "z": {danger:0.8838,stableDanger:0.8838,cost:0.1162,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\udf39": {
    "i": {danger:0.8577,stableDanger:0.8577,cost:0.1423,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.8222,stableDanger:0.8222,cost:0.1778,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.8952,stableDanger:0.8952,cost:0.1048,xidContinue:true,idnaPvalid:true},
    "t": {danger:0.7123,stableDanger:0.7123,cost:0.2877,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\udf44": {
    "i": {danger:0.7467,stableDanger:0.7467,cost:0.2533,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.7227,stableDanger:0.7227,cost:0.2773,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.7559,stableDanger:0.7559,cost:0.2441,xidContinue:true,idnaPvalid:true},
    "t": {danger:0.8468,stableDanger:0.8468,cost:0.1532,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\udf45": {
    "y": {danger:0.714,stableDanger:0.714,cost:0.286,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\udf47": {
    "x": {danger:0.9407,stableDanger:0.9407,cost:0.0593,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\udf4a": {
    "j": {danger:0.7451,stableDanger:0.7451,cost:0.2549,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.7527,stableDanger:0.7527,cost:0.2473,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\udf58": {
    "i": {danger:0.8756,stableDanger:0.8756,cost:0.1244,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.8396,stableDanger:0.8396,cost:0.1604,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.929,stableDanger:0.929,cost:0.071,xidContinue:true,idnaPvalid:true},
    "t": {danger:0.7229,stableDanger:0.7229,cost:0.2771,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\udf6d": {
    "i": {danger:0.9085,stableDanger:0.9085,cost:0.0915,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.9387,stableDanger:0.9387,cost:0.0613,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.9524,stableDanger:0.9524,cost:0.0476,xidContinue:true,idnaPvalid:true},
    "t": {danger:0.7804,stableDanger:0.7804,cost:0.2196,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\udf6e": {
    "x": {danger:0.7748,stableDanger:0.7748,cost:0.2252,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\udf82": {
    "i": {danger:0.7985,stableDanger:0.7985,cost:0.2015,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.8058,stableDanger:0.8058,cost:0.1942,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.8361,stableDanger:0.8361,cost:0.1639,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\udf83": {
    "i": {danger:0.7224,stableDanger:0.7224,cost:0.2776,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.7063,stableDanger:0.7063,cost:0.2937,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.7548,stableDanger:0.7548,cost:0.2452,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\udf87": {
    "i": {danger:0.7719,stableDanger:0.7719,cost:0.2281,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.7674,stableDanger:0.7674,cost:0.2326,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.8215,stableDanger:0.8215,cost:0.1785,xidContinue:true,idnaPvalid:true},
    "t": {danger:0.7672,stableDanger:0.7672,cost:0.2328,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\udf92": {
    "y": {danger:0.7407,stableDanger:0.7407,cost:0.2593,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\udfd1": {
    "i": {danger:0.7941,stableDanger:0.7941,cost:0.2059,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.8008,stableDanger:0.8008,cost:0.1992,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.8301,stableDanger:0.8301,cost:0.1699,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\udfd2": {
    "i": {danger:0.7647,stableDanger:0.7647,cost:0.2353,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.7623,stableDanger:0.7623,cost:0.2377,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.8127,stableDanger:0.8127,cost:0.1873,xidContinue:true,idnaPvalid:true},
  },
  "\ud801\udc1d": {
    "8": {danger:0.833,stableDanger:0.8234,cost:0.1766,xidContinue:true},
  },
  "\ud801\udc1e": {
    "6": {danger:0.9969,stableDanger:0.9795,cost:0.0205,xidContinue:true},
  },
  "\ud801\udc47": {
    "b": {danger:1,stableDanger:0.9999,cost:0.0001,xidContinue:true,idnaPvalid:true},
  },
  "\ud801\udc53": {
    "j": {danger:0.7754,stableDanger:0.7751,cost:0.2249,xidContinue:true,idnaPvalid:true},
  },
  "\ud801\udc66": {
    "i": {danger:0.8117,stableDanger:0.8092,cost:0.1908,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.8646,stableDanger:0.8622,cost:0.1378,xidContinue:true,idnaPvalid:true},
  },
  "\ud801\udc69": {
    "r": {danger:0.7501,stableDanger:0.746,cost:0.254,xidContinue:true,idnaPvalid:true},
  },
  "\ud801\udc83": {
    "f": {danger:0.7463,stableDanger:0.7463,cost:0.2537,xidContinue:true,idnaPvalid:true},
    "i": {danger:0.8137,stableDanger:0.8137,cost:0.1863,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.7434,stableDanger:0.7434,cost:0.2566,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.844,stableDanger:0.844,cost:0.156,xidContinue:true,idnaPvalid:true},
  },
  "\ud801\udc86": {
    "c": {danger:0.7154,stableDanger:0.7154,cost:0.2846,xidContinue:true,idnaPvalid:true},
    "o": {danger:0.8327,stableDanger:0.8327,cost:0.1673,xidContinue:true,idnaPvalid:true},
  },
  "\ud801\udc98": {
    "9": {danger:0.7733,stableDanger:0.7733,cost:0.2267,xidContinue:true,idnaPvalid:true},
  },
  "\ud801\udcd8": {
    "a": {danger:0.7008,stableDanger:0.7008,cost:0.2992,xidContinue:true,idnaPvalid:true},
  },
  "\ud801\udcda": {
    "a": {danger:0.7139,stableDanger:0.7139,cost:0.2861,xidContinue:true,idnaPvalid:true},
  },
  "\ud801\udce3": {
    "d": {danger:0.7182,stableDanger:0.7182,cost:0.2818,xidContinue:true,idnaPvalid:true},
    "n": {danger:0.8092,stableDanger:0.8092,cost:0.1908,xidContinue:true,idnaPvalid:true},
    "o": {danger:0.7434,stableDanger:0.7434,cost:0.2566,xidContinue:true,idnaPvalid:true},
  },
  "\ud801\udceb": {
    "e": {danger:0.7225,stableDanger:0.7225,cost:0.2775,xidContinue:true,idnaPvalid:true},
    "o": {danger:0.7852,stableDanger:0.7852,cost:0.2148,xidContinue:true,idnaPvalid:true},
  },
  "\ud801\udd07": {
    "z": {danger:0.7872,stableDanger:0.7872,cost:0.2128,xidContinue:true,idnaPvalid:true},
  },
  "\ud801\udd0e": {
    "i": {danger:0.8242,stableDanger:0.8242,cost:0.1758,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.8092,stableDanger:0.8092,cost:0.1908,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.8696,stableDanger:0.8696,cost:0.1304,xidContinue:true,idnaPvalid:true},
    "t": {danger:0.7092,stableDanger:0.7092,cost:0.2908,xidContinue:true,idnaPvalid:true},
  },
  "\ud801\udd17": {
    "d": {danger:0.7273,stableDanger:0.7273,cost:0.2727,xidContinue:true,idnaPvalid:true},
    "u": {danger:0.7518,stableDanger:0.7518,cost:0.2482,xidContinue:true,idnaPvalid:true},
  },
  "\ud801\udd1b": {
    "c": {danger:0.7439,stableDanger:0.7439,cost:0.2561,xidContinue:true,idnaPvalid:true},
  },
  "\ud801\udd21": {
    "b": {danger:0.7135,stableDanger:0.7135,cost:0.2865,xidContinue:true,idnaPvalid:true},
  },
  "\ud801\udd33": {
    "q": {danger:0.717,stableDanger:0.717,cost:0.283,xidContinue:true,idnaPvalid:true},
  },
  "\ud801\udd36": {
    "r": {danger:0.7029,stableDanger:0.7029,cost:0.2971,xidContinue:true,idnaPvalid:true},
  },
  "\ud801\udd3d": {
    "b": {danger:0.7847,stableDanger:0.7847,cost:0.2153,xidContinue:true,idnaPvalid:true},
  },
  "\ud801\udd3f": {
    "i": {danger:0.8181,stableDanger:0.8181,cost:0.1819,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.8144,stableDanger:0.8144,cost:0.1856,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.8692,stableDanger:0.8692,cost:0.1308,xidContinue:true,idnaPvalid:true},
  },
  "\ud801\udd5d": {
    "8": {danger:0.8031,stableDanger:0.8031,cost:0.1969,xidContinue:true,idnaPvalid:true},
  },
  "\ud801\udd5e": {
    "u": {danger:0.8247,stableDanger:0.8247,cost:0.1753,xidContinue:true,idnaPvalid:true},
  },
  "\ud801\ude05": {
    "i": {danger:0.7512,stableDanger:0.7512,cost:0.2488,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.7695,stableDanger:0.7695,cost:0.2305,xidContinue:true,idnaPvalid:true},
    "t": {danger:0.702,stableDanger:0.702,cost:0.298,xidContinue:true,idnaPvalid:true},
  },
  "\ud801\ude6b": {
    "i": {danger:0.7369,stableDanger:0.7369,cost:0.2631,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.7521,stableDanger:0.7521,cost:0.2479,xidContinue:true,idnaPvalid:true},
  },
  "\ud801\udf41": {
    "j": {danger:0.7049,stableDanger:0.7049,cost:0.2951,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.7355,stableDanger:0.7355,cost:0.2645,xidContinue:true,idnaPvalid:true},
  },
  "\ud801\udf46": {
    "l": {danger:0.7454,stableDanger:0.7454,cost:0.2546,xidContinue:true,idnaPvalid:true},
  },
  "\ud801\udf47": {
    "i": {danger:0.7959,stableDanger:0.7959,cost:0.2041,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.8153,stableDanger:0.8153,cost:0.1847,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.7714,stableDanger:0.7714,cost:0.2286,xidContinue:true,idnaPvalid:true},
    "t": {danger:0.7666,stableDanger:0.7666,cost:0.2334,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\udc10": {
    "8": {danger:0.7943,stableDanger:0.7943,cost:0.2057,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\udc18": {
    "x": {danger:0.8688,stableDanger:0.8688,cost:0.1312,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\udc28": {
    "v": {danger:0.7389,stableDanger:0.7389,cost:0.2611,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\udc33": {
    "i": {danger:0.7182,stableDanger:0.7182,cost:0.2818,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.7396,stableDanger:0.7396,cost:0.2604,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.7046,stableDanger:0.7046,cost:0.2954,xidContinue:true,idnaPvalid:true},
    "t": {danger:0.7695,stableDanger:0.7695,cost:0.2305,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\udc46": {
    "i": {danger:0.8638,stableDanger:0.8638,cost:0.1362,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.8709,stableDanger:0.8709,cost:0.1291,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.8979,stableDanger:0.8979,cost:0.1021,xidContinue:true,idnaPvalid:true},
    "t": {danger:0.7544,stableDanger:0.7544,cost:0.2456,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\udc66": {
    "l": {danger:0.7639,stableDanger:0.7639,cost:0.2361,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\udc68": {
    "6": {danger:0.7559,stableDanger:0.7559,cost:0.2441,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\udc79": {
    "j": {danger:0.8524,stableDanger:0.8524,cost:0.1476,idnaPvalid:true},
  },
  "\ud802\udc89": {
    "i": {danger:0.9234,stableDanger:0.9234,cost:0.0766,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.8896,stableDanger:0.8896,cost:0.1104,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.9861,stableDanger:0.9861,cost:0.0139,xidContinue:true,idnaPvalid:true},
    "t": {danger:0.7433,stableDanger:0.7433,cost:0.2567,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\udc91": {
    "i": {danger:0.7333,stableDanger:0.7333,cost:0.2667,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.7454,stableDanger:0.7454,cost:0.2546,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\udca7": {
    "i": {danger:0.8794,stableDanger:0.8794,cost:0.1206,idnaPvalid:true},
    "j": {danger:0.8447,stableDanger:0.8447,cost:0.1553,idnaPvalid:true},
    "l": {danger:0.9366,stableDanger:0.9366,cost:0.0634,idnaPvalid:true},
    "t": {danger:0.7264,stableDanger:0.7264,cost:0.2736,idnaPvalid:true},
  },
  "\ud802\udcab": {
    "x": {danger:0.7434,stableDanger:0.7434,cost:0.2566,idnaPvalid:true},
  },
  "\ud802\udcae": {
    "3": {danger:0.7698,stableDanger:0.7698,cost:0.2302,idnaPvalid:true},
  },
  "\ud802\udce6": {
    "i": {danger:0.8003,stableDanger:0.8003,cost:0.1997,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.7854,stableDanger:0.7854,cost:0.2146,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.8442,stableDanger:0.8442,cost:0.1558,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\udce7": {
    "n": {danger:0.7383,stableDanger:0.7383,cost:0.2617,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\udced": {
    "i": {danger:0.9315,stableDanger:0.9315,cost:0.0685,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.9093,stableDanger:0.9093,cost:0.0907,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.9763,stableDanger:0.9763,cost:0.0237,xidContinue:true,idnaPvalid:true},
    "t": {danger:0.7668,stableDanger:0.7668,cost:0.2332,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\udcfb": {
    "i": {danger:0.9315,stableDanger:0.9315,cost:0.0685,idnaPvalid:true},
    "j": {danger:0.9093,stableDanger:0.9093,cost:0.0907,idnaPvalid:true},
    "l": {danger:0.9763,stableDanger:0.9763,cost:0.0237,idnaPvalid:true},
    "t": {danger:0.7668,stableDanger:0.7668,cost:0.2332,idnaPvalid:true},
  },
  "\ud802\udd06": {
    "i": {danger:0.7085,stableDanger:0.7085,cost:0.2915,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.78,stableDanger:0.78,cost:0.22,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\udd0f": {
    "d": {danger:0.7498,stableDanger:0.7498,cost:0.2502,xidContinue:true,idnaPvalid:true},
    "o": {danger:0.9026,stableDanger:0.9026,cost:0.0974,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\udd16": {
    "i": {danger:0.7343,stableDanger:0.7343,cost:0.2657,idnaPvalid:true},
    "l": {danger:0.7441,stableDanger:0.7441,cost:0.2559,idnaPvalid:true},
  },
  "\ud802\udd26": {
    "i": {danger:0.88,stableDanger:0.88,cost:0.12,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.8734,stableDanger:0.8734,cost:0.1266,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.9141,stableDanger:0.9141,cost:0.0859,xidContinue:true,idnaPvalid:true},
    "t": {danger:0.7529,stableDanger:0.7529,cost:0.2471,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\udd2c": {
    "o": {danger:0.704,stableDanger:0.704,cost:0.296,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\udd2f": {
    "i": {danger:0.8028,stableDanger:0.8028,cost:0.1972,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.7844,stableDanger:0.7844,cost:0.2156,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.7201,stableDanger:0.7201,cost:0.2799,xidContinue:true,idnaPvalid:true},
    "t": {danger:0.8175,stableDanger:0.8175,cost:0.1825,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\udd31": {
    "8": {danger:0.8326,stableDanger:0.8326,cost:0.1674,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\udda1": {
    "5": {danger:0.7358,stableDanger:0.7358,cost:0.2642,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\uddc0": {
    "i": {danger:0.9311,stableDanger:0.9311,cost:0.0689,idnaPvalid:true},
    "j": {danger:0.9163,stableDanger:0.9163,cost:0.0837,idnaPvalid:true},
    "l": {danger:0.9778,stableDanger:0.9778,cost:0.0222,idnaPvalid:true},
    "t": {danger:0.7705,stableDanger:0.7705,cost:0.2295,idnaPvalid:true},
  },
  "\ud802\ude61": {
    "j": {danger:0.7624,stableDanger:0.7624,cost:0.2376,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\ude72": {
    "o": {danger:0.7098,stableDanger:0.7098,cost:0.2902,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\ude7a": {
    "j": {danger:0.7273,stableDanger:0.7273,cost:0.2727,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\ude7d": {
    "i": {danger:0.8454,stableDanger:0.8454,cost:0.1546,idnaPvalid:true},
    "j": {danger:0.8939,stableDanger:0.8939,cost:0.1061,idnaPvalid:true},
    "l": {danger:0.9001,stableDanger:0.9001,cost:0.0999,idnaPvalid:true},
    "t": {danger:0.7324,stableDanger:0.7324,cost:0.2676,idnaPvalid:true},
  },
  "\ud802\ude89": {
    "x": {danger:0.7882,stableDanger:0.7882,cost:0.2118,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\ude92": {
    "o": {danger:0.8013,stableDanger:0.8013,cost:0.1987,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\ude9d": {
    "i": {danger:0.932,stableDanger:0.932,cost:0.068,idnaPvalid:true},
    "j": {danger:0.9034,stableDanger:0.9034,cost:0.0966,idnaPvalid:true},
    "l": {danger:0.9723,stableDanger:0.9723,cost:0.0277,idnaPvalid:true},
    "t": {danger:0.7607,stableDanger:0.7607,cost:0.2393,idnaPvalid:true},
  },
  "\ud802\udeeb": {
    "i": {danger:0.7293,stableDanger:0.7293,cost:0.2707,idnaPvalid:true},
    "j": {danger:0.738,stableDanger:0.738,cost:0.262,idnaPvalid:true},
    "l": {danger:0.7558,stableDanger:0.7558,cost:0.2442,idnaPvalid:true},
  },
  "\ud802\udf0c": {
    "j": {danger:0.7311,stableDanger:0.7311,cost:0.2689,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\udf10": {
    "9": {danger:0.7067,stableDanger:0.7067,cost:0.2933,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\udf25": {
    "i": {danger:0.7876,stableDanger:0.7876,cost:0.2124,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.7677,stableDanger:0.7677,cost:0.2323,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.8398,stableDanger:0.8398,cost:0.1602,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\udf26": {
    "i": {danger:0.7715,stableDanger:0.7715,cost:0.2285,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.7936,stableDanger:0.7936,cost:0.2064,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.7736,stableDanger:0.7736,cost:0.2264,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\udf30": {
    "i": {danger:0.7521,stableDanger:0.7521,cost:0.2479,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.8021,stableDanger:0.8021,cost:0.1979,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\udf45": {
    "o": {danger:0.7024,stableDanger:0.7024,cost:0.2976,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\udf58": {
    "j": {danger:0.9009,stableDanger:0.9009,cost:0.0991,idnaPvalid:true},
  },
  "\ud802\udf63": {
    "3": {danger:0.7276,stableDanger:0.7276,cost:0.2724,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\udf78": {
    "j": {danger:0.7336,stableDanger:0.7336,cost:0.2664,idnaPvalid:true},
  },
  "\ud802\udf82": {
    "j": {danger:0.8298,stableDanger:0.8298,cost:0.1702,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\udf8e": {
    "o": {danger:0.7113,stableDanger:0.7113,cost:0.2887,xidContinue:true,idnaPvalid:true},
  },
  "\ud803\udc1f": {
    "v": {danger:0.8623,stableDanger:0.8623,cost:0.1377,xidContinue:true,idnaPvalid:true},
  },
  "\ud803\udc3e": {
    "i": {danger:0.8914,stableDanger:0.8914,cost:0.1086,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.8713,stableDanger:0.8713,cost:0.1287,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.9277,stableDanger:0.9277,cost:0.0723,xidContinue:true,idnaPvalid:true},
    "t": {danger:0.7509,stableDanger:0.7509,cost:0.2491,xidContinue:true,idnaPvalid:true},
  },
  "\ud803\udc82": {
    "x": {danger:0.7128,stableDanger:0.7128,cost:0.2872,xidContinue:true},
  },
  "\ud803\udc91": {
    "l": {danger:0.7312,stableDanger:0.7312,cost:0.2688,xidContinue:true},
  },
  "\ud803\udca5": {
    "i": {danger:0.91,stableDanger:0.91,cost:0.09,xidContinue:true},
    "j": {danger:0.9369,stableDanger:0.9369,cost:0.0631,xidContinue:true},
    "l": {danger:0.9555,stableDanger:0.9555,cost:0.0445,xidContinue:true},
    "t": {danger:0.7823,stableDanger:0.7823,cost:0.2177,xidContinue:true},
  },
  "\ud803\udcc2": {
    "x": {danger:0.8833,stableDanger:0.8833,cost:0.1167,xidContinue:true,idnaPvalid:true},
  },
  "\ud803\udcd0": {
    "t": {danger:0.7291,stableDanger:0.7291,cost:0.2709,xidContinue:true,idnaPvalid:true},
  },
  "\ud803\udce5": {
    "i": {danger:0.8757,stableDanger:0.8757,cost:0.1243,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.8366,stableDanger:0.8366,cost:0.1634,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.9197,stableDanger:0.9197,cost:0.0803,xidContinue:true,idnaPvalid:true},
    "t": {danger:0.7245,stableDanger:0.7245,cost:0.2755,xidContinue:true,idnaPvalid:true},
  },
  "\ud803\udce8": {
    "x": {danger:0.7889,stableDanger:0.7889,cost:0.2111,xidContinue:true,idnaPvalid:true},
  },
  "\ud803\udce9": {
    "x": {danger:0.7491,stableDanger:0.7491,cost:0.2509,xidContinue:true,idnaPvalid:true},
  },
  "\ud803\udcfa": {
    "i": {danger:0.8757,stableDanger:0.8757,cost:0.1243,idnaPvalid:true},
    "j": {danger:0.8366,stableDanger:0.8366,cost:0.1634,idnaPvalid:true},
    "l": {danger:0.9197,stableDanger:0.9197,cost:0.0803,idnaPvalid:true},
    "t": {danger:0.7245,stableDanger:0.7245,cost:0.2755,idnaPvalid:true},
  },
  "\ud803\udcfb": {
    "v": {danger:0.8529,stableDanger:0.8529,cost:0.1471,idnaPvalid:true},
  },
  "\ud803\udcfc": {
    "x": {danger:0.8833,stableDanger:0.8833,cost:0.1167,idnaPvalid:true},
  },
  "\ud803\udd0c": {
    "f": {danger:0.7114,stableDanger:0.7114,cost:0.2886,xidContinue:true,idnaPvalid:true},
  },
  "\ud803\udd13": {
    "j": {danger:0.7329,stableDanger:0.7329,cost:0.2671,xidContinue:true,idnaPvalid:true},
  },
  "\ud803\udd31": {
    "i": {danger:0.9157,stableDanger:0.9157,cost:0.0843,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.8813,stableDanger:0.8813,cost:0.1187,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.9784,stableDanger:0.9784,cost:0.0216,xidContinue:true,idnaPvalid:true},
    "t": {danger:0.7341,stableDanger:0.7341,cost:0.2659,xidContinue:true,idnaPvalid:true},
  },
  "\ud803\ude80": {
    "i": {danger:0.7687,stableDanger:0.7687,cost:0.2313,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.7694,stableDanger:0.7694,cost:0.2306,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.8019,stableDanger:0.8019,cost:0.1981,xidContinue:true,idnaPvalid:true},
  },
  "\ud803\udea0": {
    "j": {danger:0.8844,stableDanger:0.8844,cost:0.1156,xidContinue:true,idnaPvalid:true},
  },
  "\ud803\udeb0": {
    "j": {danger:0.7912,stableDanger:0.7912,cost:0.2088,xidContinue:true,idnaPvalid:true},
  },
  "\ud804\udc09": {
    "l": {danger:0.8816,stableDanger:0.8644,cost:0.1356,xidContinue:true,idnaPvalid:true},
  },
  "\ud804\udc0b": {
    "x": {danger:0.8548,stableDanger:0.8394,cost:0.1606,xidContinue:true,idnaPvalid:true},
  },
  "\ud804\udc11": {
    "l": {danger:0.8648,stableDanger:0.8627,cost:0.1373,xidContinue:true,idnaPvalid:true},
  },
  "\ud804\udc21": {
    "i": {danger:0.7284,stableDanger:0.7257,cost:0.2743,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.7421,stableDanger:0.7386,cost:0.2614,xidContinue:true,idnaPvalid:true},
    "t": {danger:0.7789,stableDanger:0.777,cost:0.223,xidContinue:true,idnaPvalid:true},
  },
  "\ud804\udc26": {
    "i": {danger:0.8309,stableDanger:0.8282,cost:0.1718,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.8441,stableDanger:0.8408,cost:0.1592,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.875,stableDanger:0.8721,cost:0.1279,xidContinue:true,idnaPvalid:true},
  },
  "\ud804\udc2d": {
    "i": {danger:0.9402,stableDanger:0.9365,cost:0.0635,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.8999,stableDanger:0.8987,cost:0.1013,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.987,stableDanger:0.9821,cost:0.0179,xidContinue:true,idnaPvalid:true},
    "t": {danger:0.756,stableDanger:0.7554,cost:0.2446,xidContinue:true,idnaPvalid:true},
  },
  "\ud804\udcf4": {
    "j": {danger:0.8016,stableDanger:0.8016,cost:0.1984,xidContinue:true,idnaPvalid:true},
  },
  "\ud804\udcf6": {
    "i": {danger:0.7406,stableDanger:0.7406,cost:0.2594,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.7503,stableDanger:0.7503,cost:0.2497,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.7885,stableDanger:0.7885,cost:0.2115,xidContinue:true,idnaPvalid:true},
  },
  "\ud804\udcf9": {
    "l": {danger:0.7054,stableDanger:0.7054,cost:0.2946,xidContinue:true,idnaPvalid:true},
  },
  "\ud804\udd05": {
    "a": {danger:0.7487,stableDanger:0.7487,cost:0.2513,xidContinue:true,idnaPvalid:true},
  },
  "\ud804\udd18": {
    "o": {danger:0.7554,stableDanger:0.7554,cost:0.2446,xidContinue:true,idnaPvalid:true},
  },
  "\ud804\udd24": {
    "c": {danger:0.7394,stableDanger:0.7394,cost:0.2606,xidContinue:true,idnaPvalid:true},
    "o": {danger:0.9292,stableDanger:0.9292,cost:0.0708,xidContinue:true,idnaPvalid:true},
  },
  "\ud804\udd5f": {
    "8": {danger:0.701,stableDanger:0.701,cost:0.299,xidContinue:true,idnaPvalid:true},
  },
  "\ud804\udd60": {
    "s": {danger:0.7677,stableDanger:0.7677,cost:0.2323,xidContinue:true,idnaPvalid:true},
  },
  "\ud804\udd9c": {
    "c": {danger:0.707,stableDanger:0.707,cost:0.293,xidContinue:true,idnaPvalid:true},
  },
  "\ud804\uddab": {
    "t": {danger:0.7087,stableDanger:0.7087,cost:0.2913,xidContinue:true,idnaPvalid:true},
  },
  "\ud804\uddd1": {
    "o": {danger:0.7656,stableDanger:0.7656,cost:0.2344,xidContinue:true,idnaPvalid:true},
  },
  "\ud804\ude96": {
    "3": {danger:0.7621,stableDanger:0.7621,cost:0.2379,xidContinue:true,idnaPvalid:true},
  },
  "\ud804\udedb": {
    "o": {danger:0.8708,stableDanger:0.8708,cost:0.1292,xidContinue:true,idnaPvalid:true},
  },
  "\ud804\udedd": {
    "n": {danger:0.7685,stableDanger:0.7685,cost:0.2315,xidContinue:true,idnaPvalid:true},
  },
  "\ud804\udef0": {
    "d": {danger:0.7805,stableDanger:0.7805,cost:0.2195,xidContinue:true,idnaPvalid:true},
  },
  "\ud804\udf20": {
    "o": {danger:0.7312,stableDanger:0.7312,cost:0.2688,xidContinue:true,idnaPvalid:true},
  },
  "\ud805\udc50": {
    "o": {danger:0.9009,stableDanger:0.9009,cost:0.0991,xidContinue:true,idnaPvalid:true},
  },
  "\ud805\ude50": {
    "o": {danger:0.7814,stableDanger:0.7814,cost:0.2186,xidContinue:true,idnaPvalid:true},
  },
  "\ud805\ude53": {
    "3": {danger:0.7597,stableDanger:0.7597,cost:0.2403,xidContinue:true,idnaPvalid:true},
  },
  "\ud805\ude99": {
    "3": {danger:0.7028,stableDanger:0.7028,cost:0.2972,xidContinue:true,idnaPvalid:true},
  },
  "\ud805\udec8": {
    "s": {danger:0.7122,stableDanger:0.7122,cost:0.2878,xidContinue:true,idnaPvalid:true},
  },
  "\ud805\udf15": {
    "o": {danger:0.8133,stableDanger:0.8133,cost:0.1867,xidContinue:true,idnaPvalid:true},
  },
  "\ud805\udf1a": {
    "o": {danger:0.7292,stableDanger:0.7292,cost:0.2708,xidContinue:true,idnaPvalid:true},
  },
  "\ud805\udf30": {
    "c": {danger:0.716,stableDanger:0.716,cost:0.284,xidContinue:true,idnaPvalid:true},
  },
  "\ud806\udca1": {
    "i": {danger:0.7687,stableDanger:0.7687,cost:0.2313,xidContinue:true},
    "j": {danger:0.7934,stableDanger:0.7934,cost:0.2066,xidContinue:true},
    "l": {danger:0.8046,stableDanger:0.8046,cost:0.1954,xidContinue:true},
  },
  "\ud806\udcb0": {
    "m": {danger:0.7828,stableDanger:0.7828,cost:0.2172,xidContinue:true},
  },
  "\ud806\udccb": {
    "n": {danger:0.8209,stableDanger:0.8209,cost:0.1791,xidContinue:true,idnaPvalid:true},
  },
  "\ud806\udcd9": {
    "m": {danger:0.7022,stableDanger:0.7022,cost:0.2978,xidContinue:true,idnaPvalid:true},
  },
  "\ud806\udebc": {
    "z": {danger:0.7666,stableDanger:0.7602,cost:0.2398,xidContinue:true,idnaPvalid:true},
  },
  "\ud806\uded1": {
    "z": {danger:0.7724,stableDanger:0.7724,cost:0.2276,xidContinue:true,idnaPvalid:true},
  },
  "\ud806\uded3": {
    "h": {danger:0.7944,stableDanger:0.7944,cost:0.2056,xidContinue:true,idnaPvalid:true},
  },
  "\ud806\udedd": {
    "i": {danger:0.7993,stableDanger:0.7993,cost:0.2007,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.7829,stableDanger:0.7829,cost:0.2171,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.756,stableDanger:0.756,cost:0.244,xidContinue:true,idnaPvalid:true},
    "t": {danger:0.8467,stableDanger:0.8467,cost:0.1533,xidContinue:true,idnaPvalid:true},
  },
  "\ud806\udedf": {
    "v": {danger:0.7255,stableDanger:0.7255,cost:0.2745,xidContinue:true,idnaPvalid:true},
  },
  "\ud806\udee1": {
    "n": {danger:0.7329,stableDanger:0.7329,cost:0.2671,xidContinue:true,idnaPvalid:true},
  },
  "\ud806\udee2": {
    "p": {danger:0.7474,stableDanger:0.7474,cost:0.2526,xidContinue:true,idnaPvalid:true},
  },
  "\ud806\udee4": {
    "o": {danger:0.719,stableDanger:0.719,cost:0.281,xidContinue:true,idnaPvalid:true},
  },
  "\ud806\udee5": {
    "i": {danger:0.8961,stableDanger:0.8961,cost:0.1039,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.8649,stableDanger:0.8649,cost:0.1351,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.9604,stableDanger:0.9604,cost:0.0396,xidContinue:true,idnaPvalid:true},
    "t": {danger:0.7176,stableDanger:0.7176,cost:0.2824,xidContinue:true,idnaPvalid:true},
  },
  "\ud806\udee6": {
    "t": {danger:0.7358,stableDanger:0.7358,cost:0.2642,xidContinue:true,idnaPvalid:true},
  },
  "\ud807\udd06": {
    "l": {danger:0.7398,stableDanger:0.7398,cost:0.2602,xidContinue:true,idnaPvalid:true},
  },
  "\ud807\udd50": {
    "c": {danger:0.7282,stableDanger:0.7282,cost:0.2718,xidContinue:true,idnaPvalid:true},
  },
  "\ud807\udd52": {
    "u": {danger:0.7257,stableDanger:0.7257,cost:0.2743,xidContinue:true,idnaPvalid:true},
  },
  "\ud807\udd54": {
    "o": {danger:0.7289,stableDanger:0.7289,cost:0.2711,xidContinue:true,idnaPvalid:true},
  },
  "\ud807\udda0": {
    "c": {danger:0.803,stableDanger:0.803,cost:0.197,xidContinue:true,idnaPvalid:true},
  },
  "\ud807\udda1": {
    "d": {danger:0.8358,stableDanger:0.8358,cost:0.1642,xidContinue:true,idnaPvalid:true},
  },
  "\ud81a\udc61": {
    "j": {danger:0.723,stableDanger:0.723,cost:0.277,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.7441,stableDanger:0.7441,cost:0.2559,xidContinue:true,idnaPvalid:true},
  },
  "\ud81a\ude43": {
    "9": {danger:0.7533,stableDanger:0.7533,cost:0.2467,xidContinue:true,idnaPvalid:true},
  },
  "\ud81a\ude44": {
    "i": {danger:0.7026,stableDanger:0.7026,cost:0.2974,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.7133,stableDanger:0.7133,cost:0.2867,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.7302,stableDanger:0.7302,cost:0.2698,xidContinue:true,idnaPvalid:true},
  },
  "\ud81a\ude4b": {
    "i": {danger:0.7075,stableDanger:0.7075,cost:0.2925,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.7189,stableDanger:0.7189,cost:0.2811,xidContinue:true,idnaPvalid:true},
  },
  "\ud81a\ude4c": {
    "f": {danger:0.7618,stableDanger:0.7618,cost:0.2382,xidContinue:true,idnaPvalid:true},
    "h": {danger:0.7002,stableDanger:0.7002,cost:0.2998,xidContinue:true,idnaPvalid:true},
  },
  "\ud81a\ude4d": {
    "v": {danger:0.8007,stableDanger:0.8007,cost:0.1993,xidContinue:true,idnaPvalid:true},
  },
  "\ud81a\ude57": {
    "c": {danger:0.7207,stableDanger:0.7207,cost:0.2793,xidContinue:true,idnaPvalid:true},
  },
  "\ud81a\ude59": {
    "i": {danger:0.9366,stableDanger:0.9366,cost:0.0634,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.9012,stableDanger:0.9012,cost:0.0988,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.9779,stableDanger:0.9779,cost:0.0221,xidContinue:true,idnaPvalid:true},
    "t": {danger:0.7578,stableDanger:0.7578,cost:0.2422,xidContinue:true,idnaPvalid:true},
  },
  "\ud81a\ude60": {
    "o": {danger:0.8453,stableDanger:0.8453,cost:0.1547,xidContinue:true,idnaPvalid:true},
  },
  "\ud81a\udf10": {
    "m": {danger:0.746,stableDanger:0.746,cost:0.254,xidContinue:true,idnaPvalid:true},
  },
  "\ud81a\udf14": {
    "u": {danger:0.7804,stableDanger:0.7804,cost:0.2196,xidContinue:true,idnaPvalid:true},
  },
  "\ud81a\udf2a": {
    "m": {danger:0.8314,stableDanger:0.8314,cost:0.1686,xidContinue:true,idnaPvalid:true},
  },
  "\ud81a\udf41": {
    "i": {danger:0.7383,stableDanger:0.7383,cost:0.2617,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.74,stableDanger:0.74,cost:0.26,xidContinue:true,idnaPvalid:true},
  },
  "\ud81a\udf50": {
    "i": {danger:0.9268,stableDanger:0.9268,cost:0.0732,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.8891,stableDanger:0.8891,cost:0.1109,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.9863,stableDanger:0.9863,cost:0.0137,xidContinue:true,idnaPvalid:true},
    "t": {danger:0.7428,stableDanger:0.7428,cost:0.2572,xidContinue:true,idnaPvalid:true},
  },
  "\ud81a\udf67": {
    "m": {danger:0.7264,stableDanger:0.7264,cost:0.2736,xidContinue:true,idnaPvalid:true},
  },
  "\ud81a\udf6f": {
    "l": {danger:0.7333,stableDanger:0.7333,cost:0.2667,xidContinue:true,idnaPvalid:true},
  },
  "\ud81b\udf0d": {
    "i": {danger:0.7292,stableDanger:0.7277,cost:0.2723,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.7488,stableDanger:0.7458,cost:0.2542,xidContinue:true,idnaPvalid:true},
  },
  "\ud81b\udf0e": {
    "i": {danger:0.7405,stableDanger:0.739,cost:0.261,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.7597,stableDanger:0.758,cost:0.242,xidContinue:true,idnaPvalid:true},
  },
  "\ud81b\udf28": {
    "l": {danger:0.9962,stableDanger:0.9496,cost:0.0504,xidContinue:true,idnaPvalid:true},
  },
  "\ud81b\udf2a": {
    "i": {danger:0.7566,stableDanger:0.751,cost:0.249,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.7472,stableDanger:0.744,cost:0.256,xidContinue:true,idnaPvalid:true},
  },
  "\ud82f\udc02": {
    "i": {danger:0.7746,stableDanger:0.7746,cost:0.2254,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.7496,stableDanger:0.7496,cost:0.2504,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.8224,stableDanger:0.8224,cost:0.1776,xidContinue:true,idnaPvalid:true},
  },
  "\ud82f\udc07": {
    "i": {danger:0.9332,stableDanger:0.9332,cost:0.0668,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.9192,stableDanger:0.9192,cost:0.0808,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.9806,stableDanger:0.9806,cost:0.0194,xidContinue:true,idnaPvalid:true},
    "t": {danger:0.7714,stableDanger:0.7714,cost:0.2286,xidContinue:true,idnaPvalid:true},
  },
  "\ud82f\udc0c": {
    "i": {danger:0.8425,stableDanger:0.8425,cost:0.1575,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.8686,stableDanger:0.8686,cost:0.1314,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.8802,stableDanger:0.8802,cost:0.1198,xidContinue:true,idnaPvalid:true},
    "t": {danger:0.7376,stableDanger:0.7376,cost:0.2624,xidContinue:true,idnaPvalid:true},
  },
  "\ud82f\udc43": {
    "o": {danger:0.7652,stableDanger:0.7652,cost:0.2348,xidContinue:true,idnaPvalid:true},
  },
  "\ud82f\udc44": {
    "c": {danger:0.7552,stableDanger:0.7552,cost:0.2448,xidContinue:true,idnaPvalid:true},
    "d": {danger:0.7203,stableDanger:0.7203,cost:0.2797,xidContinue:true,idnaPvalid:true},
    "o": {danger:0.9151,stableDanger:0.9151,cost:0.0849,xidContinue:true,idnaPvalid:true},
  },
  "\ud82f\udc45": {
    "o": {danger:0.7248,stableDanger:0.7248,cost:0.2752,xidContinue:true,idnaPvalid:true},
  },
  "\ud82f\udc5a": {
    "o": {danger:0.7505,stableDanger:0.7505,cost:0.2495,xidContinue:true,idnaPvalid:true},
  },
  "\ud82f\udc5b": {
    "o": {danger:0.7793,stableDanger:0.7793,cost:0.2207,xidContinue:true,idnaPvalid:true},
  },
  "\ud82f\udc5e": {
    "o": {danger:0.7212,stableDanger:0.7212,cost:0.2788,xidContinue:true,idnaPvalid:true},
  },
  "\ud82f\udc7b": {
    "j": {danger:0.7854,stableDanger:0.7854,cost:0.2146,xidContinue:true,idnaPvalid:true},
  },
  "\ud834\udf60": {
    "i": {danger:0.8632,stableDanger:0.8632,cost:0.1368,idnaPvalid:true},
    "j": {danger:0.8682,stableDanger:0.8682,cost:0.1318,idnaPvalid:true},
    "l": {danger:0.8959,stableDanger:0.8959,cost:0.1041,idnaPvalid:true},
    "t": {danger:0.7574,stableDanger:0.7574,cost:0.2426,idnaPvalid:true},
  },
  "\ud834\udf6e": {
    "i": {danger:0.7522,stableDanger:0.7522,cost:0.2478,idnaPvalid:true},
    "j": {danger:0.7619,stableDanger:0.7619,cost:0.2381,idnaPvalid:true},
    "l": {danger:0.7857,stableDanger:0.7857,cost:0.2143,idnaPvalid:true},
  },
  "\ud835\udc26": {
    "m": {danger:0.7319,stableDanger:0.7319,cost:0.2681,xidContinue:true},
  },
  "\ud835\udc5a": {
    "m": {danger:0.7285,stableDanger:0.7285,cost:0.2715,xidContinue:true},
  },
  "\ud835\udda8": {
    "l": {danger:0.9814,stableDanger:0.9448,cost:0.0552,xidContinue:true},
  },
  "\ud835\uddc2": {
    "i": {danger:0.9694,stableDanger:0.9443,cost:0.0557,xidContinue:true},
  },
  "\ud835\uddc3": {
    "j": {danger:0.9402,stableDanger:0.9215,cost:0.0785,xidContinue:true},
  },
  "\ud835\uddc5": {
    "l": {danger:0.9669,stableDanger:0.9331,cost:0.0669,xidContinue:true},
  },
  "\ud835\uddc6": {
    "m": {danger:0.8777,stableDanger:0.8777,cost:0.1223,xidContinue:true},
  },
  "\ud835\uddf6": {
    "i": {danger:0.9126,stableDanger:0.8746,cost:0.1254,xidContinue:true},
  },
  "\ud835\udeaa": {
    "r": {danger:0.7329,stableDanger:0.7329,cost:0.2671,xidContinue:true},
  },
  "\ud835\udf5d": {
    "o": {danger:0.7141,stableDanger:0.7141,cost:0.2859,xidContinue:true},
  },
  "\ud835\udf6e": {
    "o": {danger:0.7021,stableDanger:0.7021,cost:0.2979,xidContinue:true},
  },
  "\ud835\udf76": {
    "n": {danger:0.7265,stableDanger:0.7265,cost:0.2735,xidContinue:true},
    "o": {danger:0.7032,stableDanger:0.7032,cost:0.2968,xidContinue:true},
  },
  "\ud835\udf77": {
    "8": {danger:0.714,stableDanger:0.714,cost:0.286,xidContinue:true},
    "e": {danger:0.7836,stableDanger:0.7836,cost:0.2164,xidContinue:true},
    "o": {danger:0.7844,stableDanger:0.7844,cost:0.2156,xidContinue:true},
  },
  "\ud835\udf86": {
    "x": {danger:0.7229,stableDanger:0.7229,cost:0.2771,xidContinue:true},
  },
  "\ud838\udd41": {
    "i": {danger:0.8356,stableDanger:0.8356,cost:0.1644,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.8605,stableDanger:0.8605,cost:0.1395,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.878,stableDanger:0.878,cost:0.122,xidContinue:true,idnaPvalid:true},
    "t": {danger:0.7285,stableDanger:0.7285,cost:0.2715,xidContinue:true,idnaPvalid:true},
  },
  "\ud838\udd45": {
    "v": {danger:0.7193,stableDanger:0.7193,cost:0.2807,xidContinue:true,idnaPvalid:true},
  },
  "\ud838\udef0": {
    "o": {danger:0.7061,stableDanger:0.7061,cost:0.2939,xidContinue:true,idnaPvalid:true},
  },
  "\ud839\udcd0": {
    "3": {danger:0.7553,stableDanger:0.7553,cost:0.2447,xidContinue:true,idnaPvalid:true},
  },
  "\ud839\udcd4": {
    "e": {danger:0.7111,stableDanger:0.7111,cost:0.2889,xidContinue:true,idnaPvalid:true},
  },
  "\ud839\udce3": {
    "8": {danger:0.7434,stableDanger:0.7434,cost:0.2566,xidContinue:true,idnaPvalid:true},
  },
  "\ud839\udce8": {
    "v": {danger:0.7156,stableDanger:0.7156,cost:0.2844,xidContinue:true,idnaPvalid:true},
  },
  "\ud839\udce9": {
    "q": {danger:0.7523,stableDanger:0.7523,cost:0.2477,xidContinue:true,idnaPvalid:true},
  },
  "\ud839\udcf1": {
    "i": {danger:0.8553,stableDanger:0.8553,cost:0.1447,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.9003,stableDanger:0.9003,cost:0.0997,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.9075,stableDanger:0.9075,cost:0.0925,xidContinue:true,idnaPvalid:true},
    "t": {danger:0.7422,stableDanger:0.7422,cost:0.2578,xidContinue:true,idnaPvalid:true},
  },
  "\ud839\udcf3": {
    "z": {danger:0.7401,stableDanger:0.7401,cost:0.2599,xidContinue:true,idnaPvalid:true},
  },
  "\ud83a\udc1a": {
    "l": {danger:0.8002,stableDanger:0.8002,cost:0.1998,xidContinue:true,idnaPvalid:true},
  },
  "\ud83a\udc22": {
    "i": {danger:0.9292,stableDanger:0.9292,cost:0.0708,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.9176,stableDanger:0.9176,cost:0.0824,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.9781,stableDanger:0.9781,cost:0.0219,xidContinue:true,idnaPvalid:true},
    "t": {danger:0.7695,stableDanger:0.7695,cost:0.2305,xidContinue:true,idnaPvalid:true},
  },
  "\ud83a\udc26": {
    "i": {danger:0.7977,stableDanger:0.7977,cost:0.2023,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.8079,stableDanger:0.8079,cost:0.1921,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.8208,stableDanger:0.8208,cost:0.1792,xidContinue:true,idnaPvalid:true},
  },
  "\ud83a\udc29": {
    "i": {danger:0.7981,stableDanger:0.7981,cost:0.2019,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.8072,stableDanger:0.8072,cost:0.1928,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.8327,stableDanger:0.8327,cost:0.1673,xidContinue:true,idnaPvalid:true},
  },
  "\ud83a\udc2b": {
    "i": {danger:0.8718,stableDanger:0.8718,cost:0.1282,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.8684,stableDanger:0.8684,cost:0.1316,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.9227,stableDanger:0.9227,cost:0.0773,xidContinue:true,idnaPvalid:true},
    "t": {danger:0.7217,stableDanger:0.7217,cost:0.2783,xidContinue:true,idnaPvalid:true},
  },
  "\ud83a\udc67": {
    "i": {danger:0.7028,stableDanger:0.7028,cost:0.2972,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.7164,stableDanger:0.7164,cost:0.2836,xidContinue:true,idnaPvalid:true},
  },
  "\ud83a\udc8d": {
    "y": {danger:0.7464,stableDanger:0.7464,cost:0.2536,xidContinue:true,idnaPvalid:true},
  },
  "\ud83a\udcc7": {
    "l": {danger:0.9906,stableDanger:0.945,cost:0.055,idnaPvalid:true},
  },
  "\ud83a\udd06": {
    "p": {danger:0.713,stableDanger:0.713,cost:0.287,xidContinue:true},
  },
  "\ud83a\udd0a": {
    "h": {danger:0.7321,stableDanger:0.7321,cost:0.2679,xidContinue:true},
  },
  "\ud83a\udd0c": {
    "c": {danger:0.7584,stableDanger:0.7584,cost:0.2416,xidContinue:true},
  },
  "\ud83a\udd12": {
    "3": {danger:0.7427,stableDanger:0.7427,cost:0.2573,xidContinue:true},
  },
  "\ud83a\udd2e": {
    "c": {danger:0.8043,stableDanger:0.8043,cost:0.1957,xidContinue:true,idnaPvalid:true},
  },
  "\ud83a\udd36": {
    "m": {danger:0.784,stableDanger:0.784,cost:0.216,xidContinue:true,idnaPvalid:true},
  },
  "\ud83a\udd51": {
    "i": {danger:0.9335,stableDanger:0.9335,cost:0.0665,xidContinue:true,idnaPvalid:true},
    "j": {danger:0.9031,stableDanger:0.9031,cost:0.0969,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.9727,stableDanger:0.9727,cost:0.0273,xidContinue:true,idnaPvalid:true},
    "t": {danger:0.7595,stableDanger:0.7595,cost:0.2405,xidContinue:true,idnaPvalid:true},
  },
};
