// Auto-generated by scripts/generate-confusable-weights.js
// Source: confusable-vision confusable-weights-v3.json (322 pairs, release 2026.09.24)
// Generated: 2026-09-24T19:04:16.505Z
//
// DO NOT EDIT MANUALLY. Regenerate with:
//   node scripts/generate-confusable-weights.js
//
// LICENCE: This data is derived from confusable-vision output and is
// licensed under CC-BY-4.0 (https://creativecommons.org/licenses/by/4.0/).
// Attribution: Paul Wood FRSA (@paultendo), confusable-vision
// (https://github.com/paultendo/confusable-vision).
// The surrounding namespace-guard code is MIT-licensed.

import type { ConfusableWeight, ConfusableWeights } from "./index";

/**
 * Measured visual similarity weights for 322 confusable pairs, from confusable-vision release 2026.09.24.
 *
 * Each pair was found alike by RaySpace at the size and baseline position the two glyphs have in running text,
 * within one font or across fonts (a rare-script character in its fallback font against Latin in a common text
 * font). danger and stableDanger are the share of text fonts (or font combinations) where the pair is alike, and
 * cost is 1 minus that share. Identifier property flags describe the source character.
 *
 * Import from "namespace-guard/confusable-weights" to use with confusableDistance().
 *
 * @licence CC-BY-4.0 (data); MIT (code)
 * @attribution Paul Wood FRSA, confusable-vision
 * @see https://github.com/paultendo/confusable-vision
 */
export const CONFUSABLE_WEIGHTS: ConfusableWeights = {
  "l": {
    "I": {danger:0.3208,stableDanger:0.3208,cost:0.6792,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "o": {
    "0": {danger:0.066,stableDanger:0.066,cost:0.934,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "|": {
    "l": {danger:0.0667,stableDanger:0.0667,cost:0.9333,idnaPvalid:true},
  },
  "\u0131": {
    "I": {danger:0.2179,stableDanger:0.2179,cost:0.7821,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
    "l": {danger:0.1154,stableDanger:0.1154,cost:0.8846,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0185": {
    "b": {danger:0.25,stableDanger:0.25,cost:0.75,xidContinue:true,idnaPvalid:true},
  },
  "\u01c0": {
    "I": {danger:0.2632,stableDanger:0.2632,cost:0.7368,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.1316,stableDanger:0.1316,cost:0.8684,xidContinue:true,idnaPvalid:true},
  },
  "\u0251": {
    "a": {danger:0.125,stableDanger:0.125,cost:0.875,xidContinue:true,idnaPvalid:true},
  },
  "\u0261": {
    "g": {danger:0.5806,stableDanger:0.5806,cost:0.4194,xidContinue:true,idnaPvalid:true},
  },
  "\u0275": {
    "e": {danger:0.1111,stableDanger:0.1111,cost:0.8889,xidContinue:true,idnaPvalid:true},
  },
  "\u027e": {
    "r": {danger:0.1111,stableDanger:0.1111,cost:0.8889,xidContinue:true,idnaPvalid:true},
  },
  "\u03b1": {
    "a": {danger:0.0612,stableDanger:0.0612,cost:0.9388,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u03b3": {
    "y": {danger:0.1224,stableDanger:0.1224,cost:0.8776,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u03b9": {
    "l": {danger:0.0612,stableDanger:0.0612,cost:0.9388,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u03bd": {
    "v": {danger:0.5306,stableDanger:0.5306,cost:0.4694,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u03bf": {
    "o": {danger:0.8163,stableDanger:0.8163,cost:0.1837,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u03c1": {
    "p": {danger:0.3265,stableDanger:0.3265,cost:0.6735,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u03c5": {
    "u": {danger:0.2245,stableDanger:0.2245,cost:0.7755,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u03c7": {
    "x": {danger:0.0612,stableDanger:0.0612,cost:0.9388,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u03f3": {
    "j": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\u0430": {
    "a": {danger:0.8136,stableDanger:0.8136,cost:0.1864,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0435": {
    "e": {danger:0.8305,stableDanger:0.8305,cost:0.1695,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u043a": {
    "\u03ba": {danger:0.1837,stableDanger:0.1837,cost:0.8163,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u043e": {
    "0": {danger:0.0508,stableDanger:0.0508,cost:0.9492,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
    "o": {danger:0.8305,stableDanger:0.8305,cost:0.1695,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
    "\u03bf": {danger:0.8776,stableDanger:0.8776,cost:0.1224,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u043f": {
    "n": {danger:0.0508,stableDanger:0.0508,cost:0.9492,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
    "\u03c0": {danger:0.1034,stableDanger:0.1034,cost:0.8966,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0440": {
    "p": {danger:0.7966,stableDanger:0.7966,cost:0.2034,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
    "\u03c1": {danger:0.3061,stableDanger:0.3061,cost:0.6939,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0441": {
    "c": {danger:0.8305,stableDanger:0.8305,cost:0.1695,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0442": {
    "\u03c4": {danger:0.3061,stableDanger:0.3061,cost:0.6939,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0443": {
    "y": {danger:0.8305,stableDanger:0.8305,cost:0.1695,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
    "\u03b3": {danger:0.0816,stableDanger:0.0816,cost:0.9184,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0445": {
    "x": {danger:0.8136,stableDanger:0.8136,cost:0.1864,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
    "\u03c7": {danger:0.0612,stableDanger:0.0612,cost:0.9388,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0455": {
    "s": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0456": {
    "i": {danger:0.9804,stableDanger:0.9804,cost:0.0196,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0457": {
    "\u03ca": {danger:0.2683,stableDanger:0.2683,cost:0.7317,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0458": {
    "j": {danger:0.9412,stableDanger:0.9412,cost:0.0588,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
    "\u03f3": {danger:0.9474,stableDanger:0.9474,cost:0.0526,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0461": {
    "\u03c9": {danger:0.2143,stableDanger:0.2143,cost:0.7857,xidContinue:true,idnaPvalid:true},
  },
  "\u0471": {
    "\u03c8": {danger:0.375,stableDanger:0.375,cost:0.625,xidContinue:true,idnaPvalid:true},
  },
  "\u0475": {
    "v": {danger:0.2424,stableDanger:0.2424,cost:0.7576,xidContinue:true,idnaPvalid:true},
  },
  "\u04af": {
    "y": {danger:0.0909,stableDanger:0.0909,cost:0.9091,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
    "\u03b3": {danger:0.3846,stableDanger:0.3846,cost:0.6154,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u04bb": {
    "h": {danger:0.8235,stableDanger:0.8235,cost:0.1765,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u04cf": {
    "I": {danger:0.45,stableDanger:0.45,cost:0.55,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
    "l": {danger:0.35,stableDanger:0.35,cost:0.65,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0501": {
    "d": {danger:0.8667,stableDanger:0.8667,cost:0.1333,xidContinue:true,idnaPvalid:true},
  },
  "\u0511": {
    "\u03b5": {danger:0.6,stableDanger:0.6,cost:0.4,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u051b": {
    "q": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u051d": {
    "w": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u05c0": {
    "l": {danger:0.4286,stableDanger:0.4286,cost:0.5714,idnaPvalid:true},
  },
  "\u0627": {
    "l": {danger:0.5,stableDanger:0.5,cost:0.5,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u07c0": {
    "0": {danger:0.2381,stableDanger:0.2381,cost:0.7619,xidContinue:true,idnaPvalid:true},
  },
  "\u07ca": {
    "I": {danger:0.1429,stableDanger:0.1429,cost:0.8571,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.4286,stableDanger:0.4286,cost:0.5714,xidContinue:true,idnaPvalid:true},
  },
  "\u07cb": {
    "o": {danger:0.4286,stableDanger:0.4286,cost:0.5714,xidContinue:true,idnaPvalid:true},
  },
  "\u07d7": {
    "1": {danger:0.381,stableDanger:0.381,cost:0.619,xidContinue:true,idnaPvalid:true},
  },
  "\u09f7": {
    "I": {danger:0.1524,stableDanger:0.1524,cost:0.8476,idnaPvalid:true},
    "l": {danger:0.1333,stableDanger:0.1333,cost:0.8667,idnaPvalid:true},
  },
  "\u0b3e": {
    "I": {danger:0.1071,stableDanger:0.1071,cost:0.8929,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
    "l": {danger:0.2024,stableDanger:0.2024,cost:0.7976,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0b40": {
    "1": {danger:0.1786,stableDanger:0.1786,cost:0.8214,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0b72": {
    "I": {danger:0.1111,stableDanger:0.1111,cost:0.8889,idnaPvalid:true},
  },
  "\u0be6": {
    "o": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0c79": {
    "I": {danger:0.1905,stableDanger:0.1905,cost:0.8095,idnaPvalid:true},
  },
  "\u0d1f": {
    "s": {danger:0.2381,stableDanger:0.2381,cost:0.7619,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0d20": {
    "o": {danger:0.2222,stableDanger:0.2222,cost:0.7778,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0d3f": {
    "1": {danger:0.2381,stableDanger:0.2381,cost:0.7619,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0d66": {
    "o": {danger:0.1587,stableDanger:0.1587,cost:0.8413,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u0ed0": {
    "o": {danger:0.1746,stableDanger:0.1746,cost:0.8254,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u10ff": {
    "o": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
    "\u03bf": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
    "\u043e": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u1175": {
    "l": {danger:0.3095,stableDanger:0.3095,cost:0.6905,xidContinue:true,idnaPvalid:true},
  },
  "\u12d0": {
    "0": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u1340": {
    "6": {danger:0.1429,stableDanger:0.1429,cost:0.8571,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u13a0": {
    "D": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\u13a1": {
    "R": {danger:0.2698,stableDanger:0.2698,cost:0.7302,xidContinue:true,idnaPvalid:true},
  },
  "\u13a2": {
    "T": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\u13aa": {
    "A": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\u13ab": {
    "J": {danger:0.2698,stableDanger:0.2698,cost:0.7302,xidContinue:true,idnaPvalid:true},
  },
  "\u13ac": {
    "E": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\u13b3": {
    "W": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\u13b7": {
    "M": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\u13bb": {
    "H": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\u13c0": {
    "G": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\u13c3": {
    "Z": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\u13cf": {
    "b": {danger:0.2063,stableDanger:0.2063,cost:0.7937,xidContinue:true,idnaPvalid:true},
  },
  "\u13d2": {
    "R": {danger:0.2063,stableDanger:0.2063,cost:0.7937,xidContinue:true,idnaPvalid:true},
  },
  "\u13d9": {
    "V": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\u13da": {
    "S": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\u13de": {
    "L": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\u13df": {
    "C": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\u13e2": {
    "P": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\u13e6": {
    "K": {danger:0.3968,stableDanger:0.3968,cost:0.6032,xidContinue:true,idnaPvalid:true},
  },
  "\u13ed": {
    "9": {danger:0.127,stableDanger:0.127,cost:0.873,xidContinue:true,idnaPvalid:true},
  },
  "\u13ee": {
    "6": {danger:0.1429,stableDanger:0.1429,cost:0.8571,xidContinue:true,idnaPvalid:true},
  },
  "\u13f4": {
    "B": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\u1455": {
    "C": {danger:0.1429,stableDanger:0.1429,cost:0.8571,xidContinue:true,idnaPvalid:true},
  },
  "\u146f": {
    "d": {danger:0.381,stableDanger:0.381,cost:0.619,xidContinue:true,idnaPvalid:true},
  },
  "\u1472": {
    "b": {danger:0.5238,stableDanger:0.5238,cost:0.4762,xidContinue:true,idnaPvalid:true},
  },
  "\u14aa": {
    "L": {danger:0.1429,stableDanger:0.1429,cost:0.8571,xidContinue:true,idnaPvalid:true},
  },
  "\u14bf": {
    "2": {danger:0.1429,stableDanger:0.1429,cost:0.8571,xidContinue:true,idnaPvalid:true},
  },
  "\u157c": {
    "H": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\u15af": {
    "b": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\u15de": {
    "D": {danger:0.1905,stableDanger:0.1905,cost:0.8095,xidContinue:true,idnaPvalid:true},
  },
  "\u16c1": {
    "l": {danger:0.4286,stableDanger:0.4286,cost:0.5714,xidContinue:true,idnaPvalid:true},
  },
  "\u16d0": {
    "1": {danger:0.2381,stableDanger:0.2381,cost:0.7619,xidContinue:true,idnaPvalid:true},
  },
  "\u1810": {
    "0": {danger:0.2222,stableDanger:0.2222,cost:0.7778,xidContinue:true,idnaPvalid:true},
  },
  "\u1952": {
    "n": {danger:0.2857,stableDanger:0.2857,cost:0.7143,xidContinue:true,idnaPvalid:true},
  },
  "\u1959": {
    "u": {danger:0.1905,stableDanger:0.1905,cost:0.8095,xidContinue:true,idnaPvalid:true},
  },
  "\u1974": {
    "c": {danger:0.1905,stableDanger:0.1905,cost:0.8095,xidContinue:true,idnaPvalid:true},
  },
  "\u199e": {
    "o": {danger:0.381,stableDanger:0.381,cost:0.619,xidContinue:true,idnaPvalid:true},
  },
  "\u19d0": {
    "o": {danger:0.381,stableDanger:0.381,cost:0.619,xidContinue:true,idnaPvalid:true},
  },
  "\u1a21": {
    "a": {danger:0.1429,stableDanger:0.1429,cost:0.8571,xidContinue:true,idnaPvalid:true},
  },
  "\u1a45": {
    "o": {danger:0.3333,stableDanger:0.3333,cost:0.6667,xidContinue:true,idnaPvalid:true},
  },
  "\u1a6e": {
    "c": {danger:0.1429,stableDanger:0.1429,cost:0.8571,xidContinue:true,idnaPvalid:true},
  },
  "\u1a80": {
    "o": {danger:0.3333,stableDanger:0.3333,cost:0.6667,xidContinue:true,idnaPvalid:true},
  },
  "\u1a90": {
    "o": {danger:0.3333,stableDanger:0.3333,cost:0.6667,xidContinue:true,idnaPvalid:true},
  },
  "\u1bb0": {
    "O": {danger:0.3333,stableDanger:0.3333,cost:0.6667,xidContinue:true,idnaPvalid:true},
  },
  "\u1c50": {
    "0": {danger:0.6667,stableDanger:0.6667,cost:0.3333,xidContinue:true,idnaPvalid:true},
  },
  "\u1c5b": {
    "O": {danger:0.5714,stableDanger:0.5714,cost:0.4286,xidContinue:true,idnaPvalid:true},
  },
  "\u1c60": {
    "b": {danger:0.1905,stableDanger:0.1905,cost:0.8095,xidContinue:true,idnaPvalid:true},
  },
  "\u1d04": {
    "c": {danger:0.625,stableDanger:0.625,cost:0.375,xidContinue:true,idnaPvalid:true},
  },
  "\u1d0f": {
    "o": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\u1d1c": {
    "u": {danger:0.3889,stableDanger:0.3889,cost:0.6111,xidContinue:true,idnaPvalid:true},
  },
  "\u1d20": {
    "v": {danger:0.875,stableDanger:0.875,cost:0.125,xidContinue:true,idnaPvalid:true},
  },
  "\u1d21": {
    "w": {danger:0.875,stableDanger:0.875,cost:0.125,xidContinue:true,idnaPvalid:true},
  },
  "\u1d22": {
    "z": {danger:0.9375,stableDanger:0.9375,cost:0.0625,xidContinue:true,idnaPvalid:true},
  },
  "\u1ef5": {
    "y": {danger:0.3902,stableDanger:0.3902,cost:0.6098,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u2228": {
    "v": {danger:0.1875,stableDanger:0.1875,cost:0.8125,idnaPvalid:true},
  },
  "\u23fd": {
    "I": {danger:0.1905,stableDanger:0.1905,cost:0.8095,idnaPvalid:true},
    "l": {danger:0.2857,stableDanger:0.2857,cost:0.7143,idnaPvalid:true},
  },
  "\u2c85": {
    "r": {danger:0.1429,stableDanger:0.1429,cost:0.8571,xidContinue:true,idnaPvalid:true},
  },
  "\u2c91": {
    "e": {danger:0.1429,stableDanger:0.1429,cost:0.8571,xidContinue:true,idnaPvalid:true},
  },
  "\u2c93": {
    "I": {danger:0.1429,stableDanger:0.1429,cost:0.8571,xidContinue:true,idnaPvalid:true},
  },
  "\u2c9f": {
    "o": {danger:0.4286,stableDanger:0.4286,cost:0.5714,xidContinue:true,idnaPvalid:true},
  },
  "\u2ca5": {
    "c": {danger:0.1905,stableDanger:0.1905,cost:0.8095,xidContinue:true,idnaPvalid:true},
  },
  "\u2cad": {
    "x": {danger:0.381,stableDanger:0.381,cost:0.619,xidContinue:true,idnaPvalid:true},
  },
  "\u2d38": {
    "V": {danger:0.4286,stableDanger:0.4286,cost:0.5714,xidContinue:true,idnaPvalid:true},
  },
  "\u2d39": {
    "E": {danger:0.5238,stableDanger:0.5238,cost:0.4762,xidContinue:true,idnaPvalid:true},
  },
  "\u2d4a": {
    "I": {danger:0.381,stableDanger:0.381,cost:0.619,xidContinue:true,idnaPvalid:true},
  },
  "\u2d4f": {
    "I": {danger:0.1429,stableDanger:0.1429,cost:0.8571,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.4286,stableDanger:0.4286,cost:0.5714,xidContinue:true,idnaPvalid:true},
  },
  "\u2d54": {
    "O": {danger:0.5238,stableDanger:0.5238,cost:0.4762,xidContinue:true,idnaPvalid:true},
  },
  "\u2d55": {
    "Q": {danger:0.1905,stableDanger:0.1905,cost:0.8095,xidContinue:true,idnaPvalid:true},
  },
  "\u2d5d": {
    "X": {danger:0.4762,stableDanger:0.4762,cost:0.5238,xidContinue:true,idnaPvalid:true},
  },
  "\u30d8": {
    "\u3078": {danger:0.7273,stableDanger:0.7273,cost:0.2727,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u30d9": {
    "\u3079": {danger:0.5455,stableDanger:0.5455,cost:0.4545,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u30da": {
    "\u307a": {danger:0.4545,stableDanger:0.4545,cost:0.5455,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u4e28": {
    "I": {danger:0.1952,stableDanger:0.1952,cost:0.8048,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
    "l": {danger:0.1905,stableDanger:0.1905,cost:0.8095,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
    "\u1175": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u4e36": {
    "\u30fd": {danger:0.8889,stableDanger:0.8889,cost:0.1111,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u4e85": {
    "J": {danger:0.1376,stableDanger:0.1376,cost:0.8624,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\u535c": {
    "\u30c8": {danger:0.2727,stableDanger:0.2727,cost:0.7273,xidContinue:true,idnaPvalid:true,tr39Allowed:true},
  },
  "\ua024": {
    "I": {danger:0.3016,stableDanger:0.3016,cost:0.6984,xidContinue:true,idnaPvalid:true},
  },
  "\ua254": {
    "C": {danger:0.1111,stableDanger:0.1111,cost:0.8889,xidContinue:true,idnaPvalid:true},
  },
  "\ua4d0": {
    "B": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\ua4d1": {
    "P": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\ua4d2": {
    "d": {danger:0.2143,stableDanger:0.2143,cost:0.7857,xidContinue:true,idnaPvalid:true},
  },
  "\ua4d3": {
    "D": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\ua4d4": {
    "T": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\ua4d6": {
    "G": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\ua4d7": {
    "K": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\ua4d9": {
    "J": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\ua4da": {
    "C": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\ua4dc": {
    "Z": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\ua4dd": {
    "F": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\ua4df": {
    "M": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\ua4e0": {
    "N": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\ua4e1": {
    "L": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\ua4e2": {
    "S": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\ua4e3": {
    "R": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\ua4e5": {
    "A": {danger:0.1429,stableDanger:0.1429,cost:0.8571,xidContinue:true,idnaPvalid:true},
  },
  "\ua4e6": {
    "V": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\ua4e7": {
    "H": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\ua4ea": {
    "W": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\ua4eb": {
    "X": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\ua4ec": {
    "Y": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\ua4ee": {
    "A": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\ua4f0": {
    "E": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\ua4f2": {
    "I": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
    "l": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\ua4f3": {
    "O": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\ua4f4": {
    "U": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\ua50b": {
    "T": {danger:0.2857,stableDanger:0.2857,cost:0.7143,xidContinue:true,idnaPvalid:true},
  },
  "\ua543": {
    "6": {danger:0.1429,stableDanger:0.1429,cost:0.8571,xidContinue:true,idnaPvalid:true},
  },
  "\ua557": {
    "B": {danger:0.2857,stableDanger:0.2857,cost:0.7143,xidContinue:true,idnaPvalid:true},
  },
  "\ua56f": {
    "I": {danger:0.1429,stableDanger:0.1429,cost:0.8571,xidContinue:true,idnaPvalid:true},
  },
  "\ua576": {
    "S": {danger:0.1905,stableDanger:0.1905,cost:0.8095,xidContinue:true,idnaPvalid:true},
  },
  "\ua5cb": {
    "E": {danger:0.2381,stableDanger:0.2381,cost:0.7619,xidContinue:true,idnaPvalid:true},
  },
  "\ua621": {
    "I": {danger:0.1429,stableDanger:0.1429,cost:0.8571,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.381,stableDanger:0.381,cost:0.619,xidContinue:true,idnaPvalid:true},
  },
  "\ua6c9": {
    "Z": {danger:0.3333,stableDanger:0.3333,cost:0.6667,xidContinue:true,idnaPvalid:true},
  },
  "\ua6ce": {
    "A": {danger:0.1429,stableDanger:0.1429,cost:0.8571,xidContinue:true,idnaPvalid:true},
  },
  "\ua6df": {
    "V": {danger:0.4286,stableDanger:0.4286,cost:0.5714,xidContinue:true,idnaPvalid:true},
  },
  "\ua731": {
    "s": {danger:0.75,stableDanger:0.75,cost:0.25,xidContinue:true,idnaPvalid:true},
  },
  "\ua830": {
    "I": {danger:0.2698,stableDanger:0.2698,cost:0.7302,idnaPvalid:true},
    "l": {danger:1,stableDanger:1,cost:0,idnaPvalid:true},
  },
  "\ua89d": {
    "O": {danger:0.1429,stableDanger:0.1429,cost:0.8571,xidContinue:true,idnaPvalid:true},
  },
  "\ua8d0": {
    "O": {danger:0.1429,stableDanger:0.1429,cost:0.8571,xidContinue:true,idnaPvalid:true},
  },
  "\ua9d0": {
    "o": {danger:0.4286,stableDanger:0.4286,cost:0.5714,xidContinue:true,idnaPvalid:true},
  },
  "\uaab1": {
    "I": {danger:0.2381,stableDanger:0.2381,cost:0.7619,xidContinue:true,idnaPvalid:true},
  },
  "\uab35": {
    "f": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\uab48": {
    "\u0433": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
    "\u1d26": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\uab51": {
    "m": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\uabf0": {
    "O": {danger:0.1429,stableDanger:0.1429,cost:0.8571,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\ude82": {
    "B": {danger:0.2619,stableDanger:0.2619,cost:0.7381,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\ude86": {
    "E": {danger:0.2619,stableDanger:0.2619,cost:0.7381,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\ude87": {
    "F": {danger:0.1905,stableDanger:0.1905,cost:0.8095,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\ude88": {
    "I": {danger:0.1667,stableDanger:0.1667,cost:0.8333,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\ude8a": {
    "I": {danger:0.2381,stableDanger:0.2381,cost:0.7619,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.3333,stableDanger:0.3333,cost:0.6667,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\ude90": {
    "X": {danger:0.3333,stableDanger:0.3333,cost:0.6667,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\ude92": {
    "O": {danger:0.3095,stableDanger:0.3095,cost:0.6905,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\ude95": {
    "P": {danger:0.2381,stableDanger:0.2381,cost:0.7619,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\ude97": {
    "T": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\udea0": {
    "A": {danger:0.3333,stableDanger:0.3333,cost:0.6667,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\udea1": {
    "B": {danger:0.2619,stableDanger:0.2619,cost:0.7381,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\udea2": {
    "C": {danger:0.1429,stableDanger:0.1429,cost:0.8571,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\udea6": {
    "I": {danger:0.2857,stableDanger:0.2857,cost:0.7143,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\udea7": {
    "B": {danger:0.1667,stableDanger:0.1667,cost:0.8333,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\udeab": {
    "O": {danger:0.3095,stableDanger:0.3095,cost:0.6905,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\udeb1": {
    "T": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\udeb2": {
    "Y": {danger:0.1905,stableDanger:0.1905,cost:0.8095,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\udeb4": {
    "X": {danger:0.3333,stableDanger:0.3333,cost:0.6667,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\udece": {
    "A": {danger:0.1667,stableDanger:0.1667,cost:0.8333,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\udecf": {
    "H": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\udf09": {
    "I": {danger:0.2381,stableDanger:0.2381,cost:0.7619,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.3333,stableDanger:0.3333,cost:0.6667,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\udf20": {
    "I": {danger:0.2381,stableDanger:0.2381,cost:0.7619,idnaPvalid:true},
    "l": {danger:0.3333,stableDanger:0.3333,cost:0.6667,idnaPvalid:true},
  },
  "\ud800\udf39": {
    "I": {danger:0.4286,stableDanger:0.4286,cost:0.5714,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\udf44": {
    "T": {danger:0.1429,stableDanger:0.1429,cost:0.8571,xidContinue:true,idnaPvalid:true},
  },
  "\ud800\udf58": {
    "I": {danger:0.4286,stableDanger:0.4286,cost:0.5714,xidContinue:true,idnaPvalid:true},
  },
  "\ud801\udc47": {
    "b": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\ud801\udc66": {
    "I": {danger:0.2381,stableDanger:0.2381,cost:0.7619,xidContinue:true,idnaPvalid:true},
  },
  "\ud801\udc69": {
    "r": {danger:0.3333,stableDanger:0.3333,cost:0.6667,xidContinue:true,idnaPvalid:true},
  },
  "\ud801\udc83": {
    "I": {danger:0.4762,stableDanger:0.4762,cost:0.5238,xidContinue:true,idnaPvalid:true},
  },
  "\ud801\udc86": {
    "O": {danger:0.2857,stableDanger:0.2857,cost:0.7143,xidContinue:true,idnaPvalid:true},
  },
  "\ud801\udc98": {
    "9": {danger:0.1905,stableDanger:0.1905,cost:0.8095,xidContinue:true,idnaPvalid:true},
  },
  "\ud801\udd0e": {
    "I": {danger:0.381,stableDanger:0.381,cost:0.619,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\udc10": {
    "8": {danger:0.4286,stableDanger:0.4286,cost:0.5714,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\udc33": {
    "I": {danger:0.1429,stableDanger:0.1429,cost:0.8571,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\udc45": {
    "1": {danger:0.2857,stableDanger:0.2857,cost:0.7143,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\udc46": {
    "I": {danger:0.2381,stableDanger:0.2381,cost:0.7619,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.3333,stableDanger:0.3333,cost:0.6667,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\udc89": {
    "I": {danger:0.2381,stableDanger:0.2381,cost:0.7619,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.1905,stableDanger:0.1905,cost:0.8095,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\udca7": {
    "I": {danger:0.381,stableDanger:0.381,cost:0.619,idnaPvalid:true},
  },
  "\ud802\udce6": {
    "I": {danger:0.381,stableDanger:0.381,cost:0.619,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\udd20": {
    "A": {danger:0.3333,stableDanger:0.3333,cost:0.6667,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\udd26": {
    "I": {danger:0.1429,stableDanger:0.1429,cost:0.8571,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.4286,stableDanger:0.4286,cost:0.5714,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\udd2f": {
    "T": {danger:0.381,stableDanger:0.381,cost:0.619,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\udd31": {
    "8": {danger:0.5238,stableDanger:0.5238,cost:0.4762,xidContinue:true,idnaPvalid:true},
  },
  "\ud802\uddc0": {
    "I": {danger:0.1905,stableDanger:0.1905,cost:0.8095,idnaPvalid:true},
    "l": {danger:0.3333,stableDanger:0.3333,cost:0.6667,idnaPvalid:true},
  },
  "\ud802\ude9d": {
    "I": {danger:0.2381,stableDanger:0.2381,cost:0.7619,idnaPvalid:true},
    "l": {danger:0.2857,stableDanger:0.2857,cost:0.7143,idnaPvalid:true},
  },
  "\ud803\udc13": {
    "X": {danger:0.5714,stableDanger:0.5714,cost:0.4286,xidContinue:true,idnaPvalid:true},
  },
  "\ud803\udc17": {
    "O": {danger:0.381,stableDanger:0.381,cost:0.619,xidContinue:true,idnaPvalid:true},
  },
  "\ud803\udc1e": {
    "J": {danger:0.2381,stableDanger:0.2381,cost:0.7619,xidContinue:true,idnaPvalid:true},
  },
  "\ud803\udc1f": {
    "V": {danger:0.381,stableDanger:0.381,cost:0.619,xidContinue:true,idnaPvalid:true},
  },
  "\ud803\udc3e": {
    "I": {danger:0.1429,stableDanger:0.1429,cost:0.8571,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.4286,stableDanger:0.4286,cost:0.5714,xidContinue:true,idnaPvalid:true},
  },
  "\ud803\udce5": {
    "I": {danger:0.381,stableDanger:0.381,cost:0.619,xidContinue:true,idnaPvalid:true},
  },
  "\ud803\udcfa": {
    "I": {danger:0.381,stableDanger:0.381,cost:0.619,idnaPvalid:true},
  },
  "\ud803\udcfb": {
    "v": {danger:0.1429,stableDanger:0.1429,cost:0.8571,idnaPvalid:true},
  },
  "\ud803\udd13": {
    "J": {danger:0.1905,stableDanger:0.1905,cost:0.8095,xidContinue:true,idnaPvalid:true},
  },
  "\ud803\udd31": {
    "I": {danger:0.1429,stableDanger:0.1429,cost:0.8571,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.4286,stableDanger:0.4286,cost:0.5714,xidContinue:true,idnaPvalid:true},
  },
  "\ud804\udc1e": {
    "O": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\ud804\udc21": {
    "I": {danger:0.1429,stableDanger:0.1429,cost:0.8571,xidContinue:true,idnaPvalid:true},
  },
  "\ud804\udc25": {
    "D": {danger:0.1905,stableDanger:0.1905,cost:0.8095,xidContinue:true,idnaPvalid:true},
  },
  "\ud804\udc2d": {
    "I": {danger:0.1429,stableDanger:0.1429,cost:0.8571,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.3333,stableDanger:0.3333,cost:0.6667,xidContinue:true,idnaPvalid:true},
  },
  "\ud804\udcb0": {
    "I": {danger:0.2857,stableDanger:0.2857,cost:0.7143,xidContinue:true,idnaPvalid:true},
  },
  "\ud804\udd24": {
    "o": {danger:0.381,stableDanger:0.381,cost:0.619,xidContinue:true,idnaPvalid:true},
  },
  "\ud804\udf20": {
    "o": {danger:1,stableDanger:1,cost:0,xidContinue:true,idnaPvalid:true},
  },
  "\ud805\udec8": {
    "s": {danger:0.1429,stableDanger:0.1429,cost:0.8571,xidContinue:true,idnaPvalid:true},
  },
  "\ud806\udebc": {
    "Z": {danger:0.1905,stableDanger:0.1905,cost:0.8095,xidContinue:true,idnaPvalid:true},
  },
  "\ud806\uded1": {
    "Z": {danger:0.3333,stableDanger:0.3333,cost:0.6667,xidContinue:true,idnaPvalid:true},
  },
  "\ud806\udedd": {
    "T": {danger:0.381,stableDanger:0.381,cost:0.619,xidContinue:true,idnaPvalid:true},
  },
  "\ud806\udedf": {
    "V": {danger:0.5714,stableDanger:0.5714,cost:0.4286,xidContinue:true,idnaPvalid:true},
  },
  "\ud806\udee2": {
    "P": {danger:0.2381,stableDanger:0.2381,cost:0.7619,xidContinue:true,idnaPvalid:true},
  },
  "\ud806\udee4": {
    "O": {danger:0.5714,stableDanger:0.5714,cost:0.4286,xidContinue:true,idnaPvalid:true},
  },
  "\ud806\udee5": {
    "I": {danger:0.1429,stableDanger:0.1429,cost:0.8571,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.4286,stableDanger:0.4286,cost:0.5714,xidContinue:true,idnaPvalid:true},
  },
  "\ud807\udda0": {
    "o": {danger:0.3333,stableDanger:0.3333,cost:0.6667,xidContinue:true,idnaPvalid:true},
  },
  "\ud81a\ude4b": {
    "T": {danger:0.619,stableDanger:0.619,cost:0.381,xidContinue:true,idnaPvalid:true},
  },
  "\ud81a\ude4d": {
    "V": {danger:0.5714,stableDanger:0.5714,cost:0.4286,xidContinue:true,idnaPvalid:true},
  },
  "\ud81a\ude57": {
    "C": {danger:0.4286,stableDanger:0.4286,cost:0.5714,xidContinue:true,idnaPvalid:true},
  },
  "\ud81a\ude59": {
    "I": {danger:0.1429,stableDanger:0.1429,cost:0.8571,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.4286,stableDanger:0.4286,cost:0.5714,xidContinue:true,idnaPvalid:true},
  },
  "\ud81a\ude60": {
    "O": {danger:0.3333,stableDanger:0.3333,cost:0.6667,xidContinue:true,idnaPvalid:true},
  },
  "\ud81a\udf14": {
    "U": {danger:0.3333,stableDanger:0.3333,cost:0.6667,xidContinue:true,idnaPvalid:true},
  },
  "\ud81a\udf41": {
    "1": {danger:0.381,stableDanger:0.381,cost:0.619,xidContinue:true,idnaPvalid:true},
  },
  "\ud81a\udf50": {
    "I": {danger:0.1429,stableDanger:0.1429,cost:0.8571,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.4286,stableDanger:0.4286,cost:0.5714,xidContinue:true,idnaPvalid:true},
  },
  "\ud81a\udf6f": {
    "L": {danger:0.1429,stableDanger:0.1429,cost:0.8571,xidContinue:true,idnaPvalid:true},
  },
  "\ud81b\udf28": {
    "I": {danger:0.2381,stableDanger:0.2381,cost:0.7619,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.3333,stableDanger:0.3333,cost:0.6667,xidContinue:true,idnaPvalid:true},
  },
  "\ud82f\udc07": {
    "I": {danger:0.1429,stableDanger:0.1429,cost:0.8571,xidContinue:true,idnaPvalid:true},
  },
  "\ud82f\udc44": {
    "o": {danger:0.1429,stableDanger:0.1429,cost:0.8571,xidContinue:true,idnaPvalid:true},
  },
  "\ud838\udd41": {
    "l": {danger:0.381,stableDanger:0.381,cost:0.619,xidContinue:true,idnaPvalid:true},
  },
  "\ud838\udef0": {
    "O": {danger:0.2857,stableDanger:0.2857,cost:0.7143,xidContinue:true,idnaPvalid:true},
  },
  "\ud839\udcf1": {
    "I": {danger:0.1429,stableDanger:0.1429,cost:0.8571,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.381,stableDanger:0.381,cost:0.619,xidContinue:true,idnaPvalid:true},
  },
  "\ud83a\udc22": {
    "I": {danger:0.1429,stableDanger:0.1429,cost:0.8571,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.381,stableDanger:0.381,cost:0.619,xidContinue:true,idnaPvalid:true},
  },
  "\ud83a\udc67": {
    "I": {danger:0.381,stableDanger:0.381,cost:0.619,xidContinue:true,idnaPvalid:true},
  },
  "\ud83a\udcc7": {
    "I": {danger:0.1429,stableDanger:0.1429,cost:0.8571,idnaPvalid:true},
    "l": {danger:0.381,stableDanger:0.381,cost:0.619,idnaPvalid:true},
  },
  "\ud83a\udd51": {
    "I": {danger:0.1429,stableDanger:0.1429,cost:0.8571,xidContinue:true,idnaPvalid:true},
    "l": {danger:0.4286,stableDanger:0.4286,cost:0.5714,xidContinue:true,idnaPvalid:true},
  },
};
