import {
  createProfanityValidator,
  type NamespaceValidator,
  type ProfanityValidatorOptions,
} from "./index";

/**
 * Curated English profanity word list for optional moderation checks.
 *
 * Source: https://github.com/zautumnz/profane-words/blob/master/words.json
 * Upstream license: WTFPL v2
 * Curated by namespace-guard maintainers (see docs/data/profanity-words.SOURCE.md). Entries that are also common
 * first names, surnames or places (wang, lynch, sanchez, pula) were taken off in 0.23.0; see CHANGELOG.md.
 */
const WORDS_EN: string[] = [
  "2 girls 1 cup",
  "2g1c",
  "4r5e",
  "5h1t",
  "5hit",
  "5ht",
  "@$$",
  "a s s",
  "a s shole",
  "a55",
  "a55hole",
  "a_s_s",
  "abbo",
  "abeed",
  "abuse",
  "acrotomophilia",
  "africoon",
  "ahole",
  "alabama hot pocket",
  "alaskan pipeline",
  "alligator bait",
  "alligatorbait",
  "amcik",
  "anal",
  "analannie",
  "analprobe",
  "analsex",
  "andskota",
  "anilingus",
  "anus",
  "apeshit",
  "ar5e",
  "arabush",
  "arabushs",
  "areole",
  "argie",
  "armo",
  "armos",
  "arrse",
  "arschloch",
  "arse",
  "arsehole",
  "ash0le",
  "ash0les",
  "asholes",
  "ass",
  "ass monkey",
  "ass-fucker",
  "ass-hat",
  "ass-pirate",
  "assbag",
  "assbagger",
  "assbandit",
  "assbang",
  "assbanged",
  "assbanger",
  "assbangs",
  "assbite",
  "assblaster",
  "assclart",
  "assclown",
  "asscock",
  "asscowboy",
  "asscracker",
  "asses",
  "assface",
  "assfuck",
  "assfucker",
  "assfukka",
  "assgoblin",
  "assh0le",
  "assh0lez",
  "asshat",
  "asshead",
  "assho1e",
  "asshole",
  "assholes",
  "assholz",
  "asshopper",
  "asshore",
  "assjacker",
  "assjockey",
  "asskiss",
  "asskisser",
  "assklown",
  "asslick",
  "asslicker",
  "asslover",
  "assman",
  "assmaster",
  "assmonkey",
  "assmunch",
  "assmuncher",
  "assnigger",
  "asspacker",
  "asspirate",
  "asspuppies",
  "assrammer",
  "assranger",
  "assshit",
  "assshole",
  "asssucker",
  "asswad",
  "asswhole",
  "asswhore",
  "asswipe",
  "asswipes",
  "auto erotic",
  "autoerotic",
  "ayir",
  "azazel",
  "azz",
  "azzhole",
  "b a s t a r d",
  "b i t c h",
  "b o o b",
  "b!+ch",
  "b!tch",
  "b!tchin",
  "b*tch",
  "b00b",
  "b00bies",
  "b00biez",
  "b00bs",
  "b00bz",
  "b17ch",
  "b1tch",
  "b7ch",
  "babeland",
  "babes",
  "baby batter",
  "baby juice",
  "backdoorman",
  "badfuck",
  "ball gag",
  "ball gravy",
  "ball kicking",
  "ball licking",
  "ball sack",
  "ball sucking",
  "ballbag",
  "balllicker",
  "ballsack",
  "bampot",
  "bangbro",
  "bangbros",
  "bangbus",
  "bareback",
  "barely legal",
  "barelylegal",
  "barenaked",
  "barface",
  "barfface",
  "bassterd",
  "bassterds",
  "bastard",
  "bastardo",
  "bastards",
  "bastardz",
  "basterds",
  "basterdz",
  "bastinado",
  "battyhole",
  "battyman",
  "bazongas",
  "bazooms",
  "bbw",
  "bdsm",
  "beaner",
  "beaners",
  "beaney",
  "beaneys",
  "beardedclam",
  "beastality",
  "beastial",
  "beastiality",
  "beastility",
  "beatch",
  "beatoff",
  "beatyourmeat",
  "beaver cleaver",
  "beaver lips",
  "beef curtains",
  "beeyotch",
  "bellend",
  "beotch",
  "bestial",
  "bestiality",
  "bi+ch",
  "bi7ch",
  "biatch",
  "big black",
  "big breasts",
  "big knockers",
  "big tits",
  "bigass",
  "bigbastard",
  "bigbreasts",
  "bigbutt",
  "bigtits",
  "bimbo",
  "bimbos",
  "birdlock",
  "bitch",
  "bitchass",
  "bitched",
  "bitcher",
  "bitchers",
  "bitches",
  "bitchez",
  "bitchin",
  "bitching",
  "bitchslap",
  "bitchtit",
  "bitchy",
  "biteme",
  "bitties",
  "black cock",
  "blackcock",
  "blacks",
  "blonde action",
  "blonde on blonde",
  "blonde on blonde action",
  "bloodclaat",
  "blow j",
  "blow job",
  "blow your l",
  "blow your load",
  "blowjob",
  "blowjobs",
  "blue waffle",
  "bluegum",
  "bluegums",
  "blumpkin",
  "bo ob",
  "bo obs",
  "boang",
  "boche",
  "boches",
  "boffing",
  "bogan",
  "bohunk",
  "boink",
  "boiolas",
  "bollick",
  "bollock",
  "bollocks",
  "bollok",
  "bollox",
  "bombers",
  "bomd",
  "bondage",
  "boned",
  "boner",
  "boners",
  "boong",
  "boonga",
  "boongas",
  "boongs",
  "boonie",
  "boonies",
  "booobs",
  "boooobs",
  "booooobs",
  "booooooobs",
  "bootee",
  "bootlip",
  "bootlips",
  "bosche",
  "bosches",
  "boschs",
  "bosomy",
  "bounty bar",
  "bounty bars",
  "bountybar",
  "brea5t",
  "breastjob",
  "breastlover",
  "breastman",
  "brown shower",
  "brown showers",
  "brunette action",
  "btch",
  "buceta",
  "buddhahead",
  "buddhaheads",
  "buffies",
  "bugger",
  "buggered",
  "buggery",
  "bukake",
  "bukkake",
  "bullcrap",
  "bulldike",
  "bulldyke",
  "bullet vibe",
  "bullshit",
  "bullshits",
  "bullshitted",
  "bullturds",
  "bumblefuck",
  "bumboraas",
  "bumfuck",
  "bung",
  "bung hole",
  "bunga",
  "bungas",
  "bunghole",
  "bunny fucker",
  "burr head",
  "burr heads",
  "burrhead",
  "burrheads",
  "butchbabes",
  "butchdike",
  "butchdyke",
  "butt plug",
  "butt-pirate",
  "buttbang",
  "buttcheeks",
  "buttface",
  "buttfuck",
  "buttfucker",
  "buttfuckers",
  "butthead",
  "butthole",
  "buttman",
  "buttmuch",
  "buttmunch",
  "buttmuncher",
  "buttpirate",
  "buttplug",
  "buttstain",
  "buttwipe",
  "byatch",
  "c u n t",
  "c-0-c-k",
  "c-o-c-k",
  "c-u-n-t",
  "c.0.c.k",
  "c.o.c.k.",
  "c.u.n.t",
  "c0ck",
  "c0cks",
  "c0cksucker",
  "c0k",
  "cabron",
  "caca",
  "cacker",
  "cahone",
  "camel jockey",
  "camel jockeys",
  "camel toe",
  "cameljockey",
  "cameltoe",
  "camgirl",
  "camslut",
  "camwhore",
  "carpet muncher",
  "carpetmuncher",
  "cawk",
  "cawks",
  "cazzo",
  "chav",
  "cheese eating surrender monkey",
  "cheese eating surrender monkies",
  "cheeseeating surrender monkey",
  "cheeseeating surrender monkies",
  "cheesehead",
  "cheeseheads",
  "cherrypopper",
  "chi chi man",
  "chichiman",
  "chickslick",
  "china swede",
  "china swedes",
  "chinaman",
  "chinamen",
  "chinaswede",
  "chinaswedes",
  "chinc",
  "chincs",
  "ching chong",
  "ching chongs",
  "chinga",
  "chingchong",
  "chingchongs",
  "chink",
  "chinks",
  "chinky",
  "choad",
  "chocolate rosebuds",
  "chode",
  "chodes",
  "chonkies",
  "chonky",
  "chonkys",
  "chraa",
  "christ killer",
  "christ killers",
  "chug",
  "chugs",
  "chuj",
  "chunger",
  "chungers",
  "cipa",
  "circlejerk",
  "cl1t",
  "clamdigger",
  "clamdiver",
  "clamps",
  "clansman",
  "clansmen",
  "clanswoman",
  "clanswomen",
  "cleveland steamer",
  "clit",
  "clitface",
  "clitfuck",
  "clitoris",
  "clitorus",
  "clits",
  "clitty",
  "clogwog",
  "clover clamps",
  "clusterfuck",
  "cnts",
  "cntz",
  "cnut",
  "cocain",
  "cocaine",
  "cock",
  "cock-head",
  "cock-sucker",
  "cockbite",
  "cockblock",
  "cockblocker",
  "cockburger",
  "cockcowboy",
  "cockface",
  "cockfight",
  "cockfucker",
  "cockhead",
  "cockholster",
  "cockjockey",
  "cockknob",
  "cockknocker",
  "cockknoker",
  "cocklicker",
  "cocklover",
  "cockmaster",
  "cockmongler",
  "cockmongruel",
  "cockmonkey",
  "cockmunch",
  "cockmuncher",
  "cocknob",
  "cocknose",
  "cocknugget",
  "cockqueen",
  "cockrider",
  "cocks",
  "cockshit",
  "cocksman",
  "cocksmith",
  "cocksmoker",
  "cocksucer",
  "cocksuck",
  "cocksucked",
  "cocksucker",
  "cocksucking",
  "cocksucks",
  "cocksuka",
  "cocksukka",
  "cocktease",
  "cocky",
  "cohee",
  "coital",
  "coitus",
  "cok",
  "cokmuncher",
  "coksucka",
  "condom",
  "coochie",
  "coochy",
  "coolies",
  "coon ass",
  "coon asses",
  "coonass",
  "coonasses",
  "coondog",
  "coons",
  "cooter",
  "coprolagnia",
  "coprophilia",
  "copulate",
  "corksucker",
  "cornhole",
  "cra5h",
  "crackcocain",
  "crackpipe",
  "crackwhore",
  "crap",
  "crapola",
  "crapper",
  "crappy",
  "creampie",
  "crotchjockey",
  "crotchmonkey",
  "crotchrot",
  "cuck",
  "cum",
  "cum face",
  "cum licker",
  "cumbubble",
  "cumdumpster",
  "cumfest",
  "cumguzzler",
  "cuming",
  "cumjockey",
  "cumlickr",
  "cumm",
  "cummer",
  "cummin",
  "cumming",
  "cumquat",
  "cumqueen",
  "cums",
  "cumshot",
  "cumshots",
  "cumslut",
  "cumstain",
  "cumsucker",
  "cumtart",
  "cunilingus",
  "cunillingus",
  "cunn",
  "cunnie",
  "cunnilingus",
  "cunntt",
  "cunny",
  "cunt",
  "cunteyed",
  "cuntface",
  "cuntfuck",
  "cuntfucker",
  "cunthole",
  "cunthunter",
  "cuntlick",
  "cuntlicker",
  "cuntlicking",
  "cuntrag",
  "cunts",
  "cuntslut",
  "cuntsucker",
  "cuntz",
  "curry muncher",
  "curry munchers",
  "currymuncher",
  "currymunchers",
  "cushi",
  "cushis",
  "cyalis",
  "cyberfuc",
  "cyberfuck",
  "cyberfucked",
  "cyberfucker",
  "cyberfuckers",
  "cyberfucking",
  "cybersex",
  "cyberslimer",
  "d0uch3",
  "d0uche",
  "d1ck",
  "d1ld0",
  "d1ldo",
  "d4mn",
  "dago",
  "dagos",
  "dahmer",
  "dammit",
  "damn",
  "damnit",
  "darkey",
  "darkeys",
  "darkie",
  "darkies",
  "darky",
  "date rape",
  "daterape",
  "datnigga",
  "dawgie style",
  "dawgie-style",
  "daygo",
  "deapthroat",
  "deep throat",
  "deep throating",
  "deepaction",
  "deepthroat",
  "deepthroating",
  "defecate",
  "deggo",
  "dego",
  "degos",
  "dendrophilia",
  "destroyyourpussy",
  "diaper daddy",
  "diaper head",
  "diaper heads",
  "diaperdaddy",
  "diaperhead",
  "diaperheads",
  "dick",
  "dick pic",
  "dick-ish",
  "dickbag",
  "dickbeater",
  "dickbeaters",
  "dickbrain",
  "dickdipper",
  "dickface",
  "dickflipper",
  "dickforbrains",
  "dickfuck",
  "dickhead",
  "dickheads",
  "dickhole",
  "dickish",
  "dickjuice",
  "dickless",
  "dicklick",
  "dicklicker",
  "dickman",
  "dickmilk",
  "dickmonger",
  "dickpic",
  "dickripper",
  "dicks",
  "dicksipper",
  "dickslap",
  "dickslicker",
  "dicksucker",
  "dickwad",
  "dickweasel",
  "dickweed",
  "dickwhipper",
  "dickwod",
  "dickzipper",
  "diddle",
  "dike",
  "dild0",
  "dild0s",
  "dildo",
  "dildos",
  "dilf",
  "diligaf",
  "dilld0",
  "dilld0s",
  "dillweed",
  "dimwit",
  "dingle",
  "dingleberries",
  "dingleberry",
  "dinks",
  "dipship",
  "dipshit",
  "dipstick",
  "dirsa",
  "dirty pillows",
  "dirty sanchez",
  "dixiedike",
  "dixiedyke",
  "dlck",
  "dog style",
  "dog-fucker",
  "doggie",
  "doggie style",
  "doggie-style",
  "doggiestyle",
  "doggin",
  "dogging",
  "doggy style",
  "doggy-style",
  "doggystyle",
  "dolcett",
  "dominatricks",
  "dominatrics",
  "dominatrix",
  "dommes",
  "donkey punch",
  "donkeypunch",
  "donkeyribber",
  "doochbag",
  "doodoo",
  "doofus",
  "dookie",
  "doosh",
  "dot head",
  "dot heads",
  "dothead",
  "dotheads",
  "double dong",
  "double penetration",
  "doubledong",
  "doublepenetration",
  "douch3",
  "douche",
  "douche bag",
  "douche-fag",
  "douchebag",
  "douchebags",
  "douchewaffle",
  "douchey",
  "dp action",
  "dpaction",
  "dragqueen",
  "dragqween",
  "dripdick",
  "dry hump",
  "dryhump",
  "duche",
  "dumass",
  "dumb ass",
  "dumbass",
  "dumbasses",
  "dumbbitch",
  "dumbfuck",
  "dumbshit",
  "dumshit",
  "dune coon",
  "dune coons",
  "dupa",
  "dvda",
  "dyefly",
  "dyke",
  "dykes",
  "dziwka",
  "earotics",
  "easyslut",
  "eat my",
  "eat my ass",
  "eatadick",
  "eatballs",
  "eathairpie",
  "eatme",
  "eatmyass",
  "eatpussy",
  "ecchi",
  "ediat",
  "ejackulate",
  "ejakulate",
  "ekto",
  "enculer",
  "enema",
  "erection",
  "erotic",
  "erotism",
  "esqua",
  "essohbee",
  "ethical slut",
  "evl",
  "excrement",
  "exkwew",
  "extacy",
  "extasy",
  "f u c k",
  "f u c k e",
  "f u c k e r",
  "f u k",
  "f*ck",
  "f-u-c-k",
  "f.u.c.k",
  "f_u_c_k",
  "facefucker",
  "fack",
  "faeces",
  "faen",
  "fag",
  "fag1t",
  "fagbag",
  "faget",
  "fagfucker",
  "fagg",
  "fagg1t",
  "fagged",
  "fagging",
  "faggit",
  "faggitt",
  "faggot",
  "faggotcock",
  "faggs",
  "fagit",
  "fagot",
  "fagots",
  "fags",
  "fagt",
  "fagtard",
  "fagz",
  "faig",
  "faigs",
  "faigt",
  "fanculo",
  "fannybandit",
  "fannyflaps",
  "fannyfucker",
  "fanyy",
  "fartknocker",
  "fassyhole",
  "fastfuck",
  "fatfuck",
  "fatfucker",
  "fatso",
  "fck",
  "fckcum",
  "fckd",
  "fcuk",
  "fcuker",
  "fcuking",
  "fecal",
  "feck",
  "fecker",
  "feg",
  "felatio",
  "felch",
  "felcher",
  "felching",
  "fellate",
  "fellatio",
  "feltch",
  "feltcher",
  "feltching",
  "female squirting",
  "femalesquirtin",
  "femalesquirting",
  "femdom",
  "fetish",
  "figging",
  "fingerbang",
  "fingerfood",
  "fingerfuck",
  "fingerfucked",
  "fingerfucker",
  "fingerfuckers",
  "fingerfucking",
  "fingerfucks",
  "fingering",
  "fisted",
  "fister",
  "fistfuck",
  "fistfucked",
  "fistfucker",
  "fistfuckers",
  "fistfucking",
  "fistfuckings",
  "fistfucks",
  "fisting",
  "fisty",
  "fitt",
  "flamer",
  "flasher",
  "flikker",
  "flipping the bird",
  "flogthelog",
  "floo",
  "floozy",
  "flydie",
  "flydye",
  "foad",
  "fondle",
  "foobar",
  "fook",
  "fooker",
  "foot fetish",
  "footaction",
  "footfetish",
  "footfuck",
  "footfucker",
  "footjob",
  "footlicker",
  "footstar",
  "foreskin",
  "forni",
  "fornicate",
  "fotze",
  "fourtwenty",
  "freakfuck",
  "freakyfucker",
  "freefuck",
  "freex",
  "frigg",
  "frigga",
  "frigger",
  "frotting",
  "fucck",
  "fuck",
  "fuck-tard",
  "fucka",
  "fuckable",
  "fuckass",
  "fuckbag",
  "fuckbitch",
  "fuckbook",
  "fuckboy",
  "fuckbrain",
  "fuckbuddy",
  "fuckbutt",
  "fuckd",
  "fucked",
  "fuckedup",
  "fucker",
  "fuckers",
  "fuckersucker",
  "fuckface",
  "fuckfest",
  "fuckfreak",
  "fuckfriend",
  "fuckhead",
  "fuckheads",
  "fuckher",
  "fuckhole",
  "fuckin",
  "fuckina",
  "fucking",
  "fuckingbitch",
  "fuckings",
  "fuckingshitmotherfucker",
  "fuckinnuts",
  "fuckinright",
  "fuckit",
  "fuckknob",
  "fuckme",
  "fuckmeat",
  "fuckmehard",
  "fuckmonkey",
  "fuckn",
  "fucknugget",
  "fucknut",
  "fucknuts",
  "fucknutt",
  "fucknutz",
  "fuckoff",
  "fuckpig",
  "fuckpuppet",
  "fuckr",
  "fucks",
  "fuckstick",
  "fucktard",
  "fucktards",
  "fucktoy",
  "fucktrophy",
  "fuckup",
  "fuckwad",
  "fuckwhit",
  "fuckwhore",
  "fuckwit",
  "fuckwitt",
  "fuckyomama",
  "fuckyou",
  "fudge packer",
  "fudgepacker",
  "fugly",
  "fuk",
  "fukah",
  "fuken",
  "fuker",
  "fukin",
  "fuking",
  "fukk",
  "fukkah",
  "fukken",
  "fukker",
  "fukkin",
  "fukking",
  "fuks",
  "fuktard",
  "fuktards",
  "fukwhit",
  "fukwit",
  "funfuck",
  "futanari",
  "futanary",
  "futkretzn",
  "fuuck",
  "fux",
  "fux0r",
  "fuxor",
  "fvck",
  "fvk",
  "fxck",
  "g-spot",
  "g00k",
  "gang bang",
  "gangbang",
  "gangbanged",
  "gangbanger",
  "gangbangs",
  "gassyass",
  "gator bait",
  "gatorbait",
  "gay sex",
  "gayass",
  "gaybob",
  "gayboy",
  "gaydo",
  "gaygirl",
  "gaymuthafuckinwhore",
  "gays",
  "gaysex",
  "gaytard",
  "gaywad",
  "gayz",
  "geezer",
  "geni",
  "genital",
  "genitals",
  "getiton",
  "gey",
  "gfy",
  "ghay",
  "ghey",
  "giant cock",
  "gigolo",
  "ginzo",
  "ginzos",
  "gippo",
  "gippos",
  "gipps",
  "girl on",
  "girl on top",
  "girls gone wild",
  "givehead",
  "glans",
  "glazeddonut",
  "goatcx",
  "goatse",
  "god dammit",
  "god damn",
  "god damnit",
  "god-dam",
  "god-damned",
  "godam",
  "godammit",
  "godamn",
  "godamnit",
  "goddam",
  "goddamit",
  "goddamm",
  "goddammit",
  "goddamn",
  "goddamned",
  "goddamnes",
  "goddamnit",
  "goddamnmuthafucker",
  "godsdamn",
  "gokkun",
  "golden shower",
  "goldenshower",
  "golliwog",
  "golliwogs",
  "gonad",
  "gonads",
  "gonorrehea",
  "gonzagas",
  "goo girl",
  "goodpoop",
  "gook",
  "gook eye",
  "gook eyes",
  "gookeye",
  "gookeyes",
  "gookies",
  "gooks",
  "gooky",
  "goras",
  "goregasm",
  "gotohell",
  "goy",
  "goyim",
  "greaseball",
  "greaseballs",
  "groe",
  "groid",
  "groids",
  "grope",
  "grostulation",
  "group sex",
  "gspot",
  "gstring",
  "gtfo",
  "gub",
  "gubba",
  "gubbas",
  "gubs",
  "guiena",
  "guineas",
  "guizi",
  "guro",
  "gwailo",
  "gwailos",
  "gweilo",
  "gweilos",
  "gyopo",
  "gyopos",
  "gyp",
  "gyped",
  "gypo",
  "gypos",
  "gypp",
  "gypped",
  "gyppie",
  "gyppies",
  "gyppo",
  "gyppos",
  "gyppy",
  "gyppys",
  "gypsys",
  "h o m",
  "h00r",
  "h0m0",
  "h0mo",
  "h0re",
  "h4x0r",
  "hadjis",
  "hairyback",
  "hairybacks",
  "hajis",
  "hajji",
  "hajjis",
  "half breed",
  "half caste",
  "halfbreed",
  "halfcaste",
  "hamas",
  "hamflap",
  "hand job",
  "handjob",
  "haole",
  "haoles",
  "hapa",
  "hardcoresex",
  "hardon",
  "headfuck",
  "hebes",
  "heeb",
  "heebs",
  "hells",
  "helvete",
  "hentai",
  "heroin",
  "herp",
  "herpes",
  "herpy",
  "heshe",
  "hijacking",
  "hillbillies",
  "hillbilly",
  "hindoo",
  "hiscock",
  "hitler",
  "hitlerism",
  "hitlerist",
  "hobag",
  "hodgie",
  "hoer",
  "hoes",
  "holestuffer",
  "hom0",
  "homo",
  "homobangers",
  "homodumbshit",
  "homoey",
  "honger",
  "honkers",
  "honkey",
  "honkeys",
  "honkie",
  "honkies",
  "honky",
  "hooch",
  "hookers",
  "hoor",
  "hoore",
  "hootch",
  "hooter",
  "hooters",
  "hore",
  "hori",
  "horis",
  "hork",
  "horndawg",
  "horndog",
  "horney",
  "horniest",
  "horny",
  "horseshit",
  "hosejob",
  "hoser",
  "hot carl",
  "hot chick",
  "hotcarl",
  "hotdamn",
  "hotpussy",
  "hotsex",
  "hottotrot",
  "how to kill",
  "how to murder",
  "howtokill",
  "howtomurdep",
  "huevon",
  "huge fat",
  "hugefat",
  "hummer",
  "humped",
  "humper",
  "humpher",
  "humphim",
  "humpin",
  "humping",
  "hussy",
  "hustler",
  "hymen",
  "hymie",
  "hymies",
  "iblowu",
  "ikes",
  "ikey",
  "ikeymo",
  "ikeymos",
  "ikwe",
  "illegals",
  "incest",
  "indon",
  "indons",
  "injun",
  "injuns",
  "insest",
  "intercourse",
  "intheass",
  "inthebuff",
  "israels",
  "j3rk0ff",
  "jack off",
  "jack-off",
  "jackass",
  "jackhole",
  "jackoff",
  "jackshit",
  "jacktheripper",
  "jail bait",
  "jailbait",
  "jap",
  "japcrap",
  "japie",
  "japies",
  "japs",
  "jebus",
  "jelly donut",
  "jerk off",
  "jerk-off",
  "jerk0ff",
  "jerked",
  "jerkoff",
  "jerries",
  "jewboy",
  "jewed",
  "jewess",
  "jiga",
  "jigaboo",
  "jigaboos",
  "jigarooni",
  "jigaroonis",
  "jigg",
  "jigga",
  "jiggabo",
  "jiggaboo",
  "jiggabos",
  "jiggas",
  "jigger",
  "jiggerboo",
  "jiggers",
  "jiggs",
  "jigs",
  "jihad",
  "jijjiboo",
  "jijjiboos",
  "jimfish",
  "jisim",
  "jism",
  "jiss",
  "jiz",
  "jizim",
  "jizin",
  "jizjuice",
  "jizm",
  "jizn",
  "jizz",
  "jizzd",
  "jizzed",
  "jizzim",
  "jizzin",
  "jizzn",
  "jizzum",
  "jugg",
  "juggs",
  "jungle bunnies",
  "jungle bunny",
  "junglebunny",
  "junkie",
  "junky",
  "kacap",
  "kacapas",
  "kacaps",
  "kaffer",
  "kaffir",
  "kaffre",
  "kafir",
  "kanake",
  "kanker",
  "katsap",
  "katsaps",
  "kawk",
  "khokhol",
  "khokhols",
  "kigger",
  "kike",
  "kikes",
  "kimchis",
  "kinbaku",
  "kink",
  "kinkster",
  "kinkyjesus",
  "kissass",
  "kiunt",
  "kkk",
  "klan",
  "klansman",
  "klansmen",
  "klanswoman",
  "klanswomen",
  "klootzak",
  "knobbing",
  "knobead",
  "knobed",
  "knobend",
  "knobhead",
  "knobjocky",
  "knobjokey",
  "knobz",
  "knockers",
  "knulle",
  "kondum",
  "kondums",
  "kooch",
  "kooches",
  "koon",
  "kootch",
  "krap",
  "krappy",
  "kraut",
  "krauts",
  "kuffar",
  "kuk",
  "kuksuger",
  "kum",
  "kumbubble",
  "kumbullbe",
  "kumer",
  "kummer",
  "kumming",
  "kums",
  "kunilingus",
  "kunnilingus",
  "kunt",
  "kunts",
  "kurac",
  "kurwa",
  "kushi",
  "kushis",
  "kusi",
  "kwai lo",
  "kwai los",
  "kwif",
  "kyke",
  "kykes",
  "kyopo",
  "kyopos",
  "kyrpa",
  "labia",
  "lapdance",
  "leather restraint",
  "leather straight",
  "leatherrestraint",
  "lebos",
  "lemon party",
  "lemonparty",
  "leper",
  "lesbain",
  "lesbayn",
  "lesbin",
  "lesbo",
  "lesbos",
  "lez",
  "lezbe",
  "lezbefriends",
  "lezbian",
  "lezbians",
  "lezbo",
  "lezbos",
  "lezz",
  "lezzian",
  "lezzie",
  "lezzies",
  "lezzo",
  "lezzy",
  "libido",
  "licker",
  "licking",
  "lickme",
  "lilniglet",
  "limey",
  "limpdick",
  "limy",
  "lingerie",
  "lipshits",
  "lipshitz",
  "livesex",
  "loadedgun",
  "lolita",
  "lovebone",
  "lovegoo",
  "lovegun",
  "lovejuice",
  "lovemuscle",
  "lovepistol",
  "loverocket",
  "lowlife",
  "lsd",
  "lubejob",
  "lubra",
  "luckycammeltoe",
  "lugan",
  "lugans",
  "lusting",
  "lusty",
  "m-fucking",
  "m0f0",
  "m0fo",
  "m45terbate",
  "ma5terb8",
  "ma5terbate",
  "mabuno",
  "mabunos",
  "macaca",
  "macacas",
  "mafugly",
  "magicwand",
  "mahbuno",
  "mahbunos",
  "make me come",
  "makemecome",
  "makemecum",
  "male squirting",
  "mamhoon",
  "manhater",
  "manpaste",
  "maricon",
  "maricón",
  "marijuana",
  "masochist",
  "masokist",
  "massterbait",
  "masstrbait",
  "masstrbate",
  "mastabate",
  "mastabater",
  "master-bate",
  "masterb8",
  "masterbaiter",
  "masterbat",
  "masterbat3",
  "masterbate",
  "masterbates",
  "masterbating",
  "masterbation",
  "masterbations",
  "masterblaster",
  "mastrabator",
  "masturbat",
  "masturbate",
  "masturbating",
  "masturbation",
  "mattressprincess",
  "mau mau",
  "mau maus",
  "maumau",
  "maumaus",
  "mcfagget",
  "meatbeatter",
  "meatrack",
  "menage",
  "merd",
  "mgger",
  "mggor",
  "mibun",
  "mickeyfinn",
  "mideast",
  "mierda",
  "milf",
  "mindfuck",
  "minge",
  "minger",
  "mo-fo",
  "mockey",
  "mockie",
  "mocky",
  "mof0",
  "mofo",
  "moky",
  "molest",
  "molestation",
  "molester",
  "molestor",
  "moneyshot",
  "mong",
  "monkleigh",
  "moolie",
  "moon cricket",
  "moon crickets",
  "mooncricket",
  "mooncrickets",
  "moskal",
  "moskals",
  "moslem",
  "mosshead",
  "motha fucker",
  "motha fuker",
  "motha fukkah",
  "motha fukker",
  "mothafuck",
  "mothafucka",
  "mothafuckas",
  "mothafuckaz",
  "mothafucked",
  "mothafucker",
  "mothafuckers",
  "mothafuckin",
  "mothafucking",
  "mothafuckings",
  "mothafucks",
  "mother fucker",
  "mother fukah",
  "mother fuker",
  "mother fukkah",
  "mother fukker",
  "mother-fucker",
  "motherfuck",
  "motherfucka",
  "motherfucked",
  "motherfucker",
  "motherfuckers",
  "motherfuckin",
  "motherfucking",
  "motherfuckings",
  "motherfuckka",
  "motherfucks",
  "motherfvcker",
  "motherlovebone",
  "mothrfucker",
  "mouliewop",
  "mound of venus",
  "moundofvenus",
  "mr hands",
  "mrhands",
  "mtherfucker",
  "mthrfuck",
  "mthrfucker",
  "mthrfucking",
  "mtrfck",
  "mtrfuck",
  "mtrfucker",
  "muff",
  "muff diver",
  "muffdive",
  "muffdiver",
  "muffdiving",
  "muffindiver",
  "mufflikcer",
  "muffpuff",
  "muie",
  "mulatto",
  "mulkku",
  "muncher",
  "munging",
  "munt",
  "munter",
  "muschi",
  "mutha fucker",
  "mutha fukah",
  "mutha fuker",
  "mutha fukkah",
  "mutha fukker",
  "muthafecker",
  "muthafuckaz",
  "muthafucker",
  "muthafuckker",
  "muther",
  "mutherfucker",
  "mutherfucking",
  "muthrfucking",
  "mzungu",
  "mzungus",
  "n1gga",
  "n1gger",
  "n1gr",
  "nads",
  "nambla",
  "nastt",
  "nastybitch",
  "nastyho",
  "nastyslut",
  "nastywhore",
  "nawashi",
  "nazi",
  "nazis",
  "nazism",
  "necro",
  "needthedick",
  "negres",
  "negress",
  "negro",
  "negroes",
  "negroid",
  "negros",
  "neonazi",
  "nepesaurio",
  "nig",
  "nig nog",
  "niga",
  "nigar",
  "nigars",
  "nigas",
  "nigers",
  "nigette",
  "nigettes",
  "nigg",
  "nigg3r",
  "nigg4h",
  "nigga",
  "niggah",
  "niggahs",
  "niggar",
  "niggaracci",
  "niggard",
  "niggarded",
  "niggarding",
  "niggardliness",
  "niggardlinesss",
  "niggardly",
  "niggards",
  "niggars",
  "niggas",
  "niggaz",
  "nigger",
  "niggerhead",
  "niggerhole",
  "niggers",
  "niggle",
  "niggled",
  "niggles",
  "nigglings",
  "niggor",
  "niggress",
  "niggresses",
  "nigguh",
  "nigguhs",
  "niggur",
  "niggurs",
  "niglet",
  "nignog",
  "nigor",
  "nigors",
  "nigr",
  "nigra",
  "nigras",
  "nigre",
  "nigres",
  "nigress",
  "nigs",
  "nigur",
  "niiger",
  "niigr",
  "nimphomania",
  "ninny",
  "nipple",
  "nipplering",
  "nipples",
  "nips",
  "nittit",
  "nlgger",
  "nlggor",
  "nob",
  "nob jokey",
  "nobhead",
  "nobjocky",
  "nobjokey",
  "nofuckingway",
  "nog",
  "nookey",
  "nookie",
  "nooky",
  "nooner",
  "nsfw",
  "nsfw images",
  "nudger",
  "nudie",
  "nudies",
  "numbnuts",
  "nut sack",
  "nutbutter",
  "nutfucker",
  "nutsack",
  "nutten",
  "nympho",
  "nymphomania",
  "octopussy",
  "omorashi",
  "one cup two girls",
  "one guy",
  "one guy one jar",
  "one jar",
  "ontherag",
  "orafis",
  "orga",
  "orgasim",
  "orgasim;",
  "orgasims",
  "orgasm",
  "orgasmic",
  "orgasms",
  "orgasum",
  "orgies",
  "orgy",
  "oriface",
  "orifiss",
  "orospu",
  "osama",
  "ovum",
  "ovums",
  "p e n i s",
  "p i s",
  "p u s s y",
  "p.u.s.s.y.",
  "p0rn",
  "packi",
  "packy",
  "paedophile",
  "paki",
  "pakie",
  "pakis",
  "paky",
  "palesimian",
  "pancake face",
  "pancake faces",
  "panooch",
  "pansies",
  "panti",
  "pantie",
  "panties",
  "panty",
  "paska",
  "payo",
  "pcp",
  "pearlnecklace",
  "pecker",
  "peckerhead",
  "peckerwood",
  "pedo",
  "pedobear",
  "pedophile",
  "pedophilia",
  "pedophiliac",
  "peeenus",
  "peeenusss",
  "peehole",
  "peenus",
  "peepee",
  "peepshow",
  "peepshpw",
  "pegging",
  "peinus",
  "pen1s",
  "penas",
  "pendejo",
  "pendy",
  "penetrate",
  "penetration",
  "peni5",
  "penial",
  "penile",
  "penis",
  "penis-breath",
  "penises",
  "penisfucker",
  "penisland",
  "penislick",
  "penislicker",
  "penispuffer",
  "penthouse",
  "penus",
  "penuus",
  "perse",
  "perv",
  "perversion",
  "peyote",
  "phalli",
  "phallic",
  "phone sex",
  "phonesex",
  "phuck",
  "phuk",
  "phuked",
  "phuker",
  "phuking",
  "phukked",
  "phukker",
  "phukking",
  "phuks",
  "phungky",
  "phuq",
  "pi55",
  "picaninny",
  "piccaninny",
  "picka",
  "pickaninnies",
  "pickaninny",
  "piece of shit",
  "pieceofshit",
  "piefke",
  "piefkes",
  "pierdol",
  "pigfucker",
  "piker",
  "pikey",
  "piky",
  "pillowbiter",
  "pillu",
  "pimmel",
  "pimp",
  "pimped",
  "pimper",
  "pimpis",
  "pimpjuic",
  "pimpjuice",
  "pimpsimp",
  "pindick",
  "pinko",
  "pis",
  "pises",
  "pisin",
  "pising",
  "pisof",
  "piss",
  "piss pig",
  "piss-off",
  "pissed",
  "pisser",
  "pissers",
  "pisses",
  "pissflap",
  "pissflaps",
  "pisshead",
  "pissin",
  "pissing",
  "pissoff",
  "pisspig",
  "pizda",
  "playboy",
  "playgirl",
  "pleasure chest",
  "pleasurechest",
  "pocha",
  "pochas",
  "pocho",
  "pochos",
  "pocketpool",
  "pohm",
  "pohms",
  "polac",
  "polack",
  "polacks",
  "pole smoker",
  "polesmoker",
  "pollocks",
  "pommie grant",
  "pommie grants",
  "pommy",
  "ponyplay",
  "poof",
  "poon",
  "poonani",
  "poonany",
  "poontang",
  "poontsee",
  "poop chute",
  "poopchute",
  "pooper",
  "pooperscooper",
  "pooping",
  "poorwhitetrash",
  "popimp",
  "porch monkey",
  "porch monkies",
  "porchmonkey",
  "porn",
  "pornflick",
  "pornking",
  "porno",
  "pornography",
  "pornos",
  "pornprincess",
  "pound town",
  "poundtown",
  "pplicker",
  "pr0n",
  "pr1c",
  "pr1ck",
  "pr1k",
  "prairie nigger",
  "prairie niggers",
  "preteen",
  "pric",
  "prickhead",
  "pricks",
  "prig",
  "prince albert piercing",
  "pron",
  "prostitute",
  "pthc",
  "pu55i",
  "pu55y",
  "pube",
  "pubes",
  "pubic",
  "pubiclice",
  "pubis",
  "pudboy",
  "pudd",
  "puddboy",
  "punani",
  "punanny",
  "punany",
  "punkass",
  "punky",
  "puntang",
  "purinapricness",
  "pusies",
  "puss",
  "pusse",
  "pussee",
  "pussi",
  "pussie",
  "pussies",
  "pussy",
  "pussy claat",
  "pussy clart",
  "pussycat",
  "pussyclaat",
  "pussyclart",
  "pussydestroyer",
  "pussyeater",
  "pussyfart",
  "pussyfuck",
  "pussyfucker",
  "pussyhole",
  "pussylicker",
  "pussylicking",
  "pussylips",
  "pussylover",
  "pussypalace",
  "pussypounder",
  "pussys",
  "pusy",
  "puta",
  "putang ina",
  "putang-ina",
  "putangina",
  "puto",
  "puuke",
  "puuker",
  "qahbeh",
  "quashie",
  "queaf",
  "queef",
  "queerhole",
  "queero",
  "queers",
  "queerz",
  "quickie",
  "quicky",
  "quiff",
  "quim",
  "qweers",
  "qweerz",
  "qweir",
  "r-tard",
  "r-tards",
  "r5e",
  "ra8s",
  "raghead",
  "ragheads",
  "rape",
  "raped",
  "raper",
  "raping",
  "rapist",
  "rasclart",
  "rasclat",
  "rassclart",
  "rautenberg",
  "rearend",
  "rearentry",
  "recktum",
  "rectal",
  "rectum",
  "rectus",
  "redleg",
  "redlegs",
  "redlight",
  "redskin",
  "redskins",
  "reefer",
  "reestie",
  "reetard",
  "renob",
  "rentafuck",
  "rere",
  "retard",
  "retarded",
  "retards",
  "retardz",
  "reverse cowgirl",
  "reversecowgirl",
  "rimjaw",
  "rimjob",
  "rimming",
  "ritard",
  "rosebuds",
  "rosy palm",
  "rosy palm and her 5 sisters",
  "rosypalm",
  "rosypalmandher5sisters",
  "rosypalmandherefivesisters",
  "round eyes",
  "roundeye",
  "rtard",
  "rtards",
  "rumprammer",
  "ruski",
  "russki",
  "russkie",
  "rusty trombone",
  "rustytrombone",
  "s h i t",
  "s hit",
  "s&m",
  "s-h-1-t",
  "s-h-i-t",
  "s-o-b",
  "s.h.i.t.",
  "s.o.b.",
  "s0b",
  "s_h_i_t",
  "sadis",
  "sadism",
  "sadist",
  "sadom",
  "sambo",
  "sambos",
  "samckdaddy",
  "sand nigger",
  "sand niggers",
  "sandm",
  "sandnigger",
  "sausagequeen",
  "scag",
  "scallywag",
  "scank",
  "scantily",
  "scat",
  "scheiss",
  "schizo",
  "schlampe",
  "schlong",
  "schmuck",
  "schvartse",
  "schvartsen",
  "schwartze",
  "schwartzen",
  "scissoring",
  "screwyou",
  "scroat",
  "scrog",
  "scrote",
  "scrotum",
  "scrud",
  "seduce",
  "semen",
  "seppo",
  "seppos",
  "septics",
  "sex",
  "sexcam",
  "sexed",
  "sexfarm",
  "sexhound",
  "sexhouse",
  "sexi",
  "sexing",
  "sexkitten",
  "sexo",
  "sexpot",
  "sexslave",
  "sextogo",
  "sextoy",
  "sextoys",
  "sexually",
  "sexwhore",
  "sexx",
  "sexxi",
  "sexxx",
  "sexxxi",
  "sexxxy",
  "sexxy",
  "sexymoma",
  "sexyslim",
  "sh!+",
  "sh!t",
  "sh1t",
  "sh1ter",
  "sh1ts",
  "sh1tter",
  "sh1tz",
  "shagger",
  "shaggin",
  "shagging",
  "shamedame",
  "sharmuta",
  "sharmute",
  "shat",
  "shav",
  "shaved beaver",
  "shaved pussy",
  "shavedbeaver",
  "shavedpussy",
  "shawtypimp",
  "sheeney",
  "shemale",
  "shhit",
  "shi+",
  "shibari",
  "shibary",
  "shinola",
  "shipal",
  "shit",
  "shit ass",
  "shit-ass",
  "shit-bag",
  "shit-bagger",
  "shit-brain",
  "shit-breath",
  "shit-cunt",
  "shit-dick",
  "shit-eating",
  "shit-face",
  "shit-faced",
  "shit-fit",
  "shit-head",
  "shit-heel",
  "shit-hole",
  "shit-house",
  "shit-load",
  "shit-pot",
  "shit-spitter",
  "shit-stain",
  "shitass",
  "shitbag",
  "shitbagger",
  "shitblimp",
  "shitbrain",
  "shitbreath",
  "shitcan",
  "shitcunt",
  "shitdick",
  "shite",
  "shiteater",
  "shiteating",
  "shited",
  "shitey",
  "shitface",
  "shitfaced",
  "shitfit",
  "shitforbrains",
  "shitfuck",
  "shitfucker",
  "shitfull",
  "shithapens",
  "shithappens",
  "shithead",
  "shitheel",
  "shithole",
  "shithouse",
  "shiting",
  "shitings",
  "shitlist",
  "shitload",
  "shitola",
  "shitoutofluck",
  "shitpot",
  "shits",
  "shitspitter",
  "shitstain",
  "shitt",
  "shitted",
  "shitter",
  "shitters",
  "shittiest",
  "shitting",
  "shittings",
  "shitty",
  "shity",
  "shitz",
  "shiz",
  "shiznit",
  "shortfuck",
  "shylock",
  "shylocks",
  "shyt",
  "shyte",
  "shytty",
  "shyty",
  "simp",
  "sixsixsix",
  "sixtynine",
  "sixtyniner",
  "skag",
  "skanck",
  "skankbitch",
  "skankee",
  "skankey",
  "skankfuck",
  "skanks",
  "skankwhore",
  "skanky",
  "skankybitch",
  "skankywhore",
  "skinflute",
  "skribz",
  "skrote",
  "skrotum",
  "skullfuck",
  "skum",
  "skumbag",
  "skurwysyn",
  "skwa",
  "skwe",
  "slag",
  "slanteye",
  "slanty",
  "slapper",
  "sleezeball",
  "slideitin",
  "slimeball",
  "slimebucket",
  "slopehead",
  "slopeheads",
  "sloper",
  "slopers",
  "slopey",
  "slopeys",
  "slopies",
  "slopy",
  "slut",
  "slutbag",
  "slutbucket",
  "slutdumper",
  "slutkiss",
  "sluts",
  "slutt",
  "slutting",
  "slutty",
  "slutwear",
  "slutwhore",
  "slutz",
  "smackthemonkey",
  "smeg",
  "smegma",
  "smut",
  "smutty",
  "snatchpatch",
  "sniggered",
  "sniggering",
  "sniggers",
  "snowback",
  "snowballing",
  "snownigger",
  "snuff",
  "socksucker",
  "sodom",
  "sodomise",
  "sodomite",
  "sodomize",
  "sodomy",
  "son of a bitch",
  "son of a whore",
  "son-of-a-bitch",
  "son-of-a-whore",
  "sonofabitch",
  "sonofbitch",
  "sooties",
  "souse",
  "soused",
  "soyboy",
  "spac",
  "spaghettibender",
  "spaghettinigger",
  "spank",
  "spankthemonkey",
  "spastic",
  "spearchucker",
  "spearchuckers",
  "sperm",
  "spermacide",
  "spermbag",
  "spermhearder",
  "spermherder",
  "sphencter",
  "spic",
  "spick",
  "spicks",
  "spics",
  "spierdalaj",
  "spig",
  "spigotty",
  "spik",
  "spiks",
  "splittail",
  "splooge",
  "spludge",
  "spooge",
  "spread legs",
  "spreadeagle",
  "spunk",
  "spunky",
  "sqeh",
  "squareheads",
  "squaw",
  "squinty",
  "squirting",
  "stfu",
  "stiffy",
  "stoned",
  "strap on",
  "strapon",
  "strappado",
  "strip club",
  "stripclub",
  "stroking",
  "stuinties",
  "stupidfuck",
  "stupidfucker",
  "style doggy",
  "suckdick",
  "sucked",
  "sucking",
  "suckme",
  "suckmyass",
  "suckmydick",
  "suckmytit",
  "suckoff",
  "suicide girl",
  "suicide girls",
  "suicidegirl",
  "suicidegirls",
  "suka",
  "sultrywoman",
  "sultrywomen",
  "sumofabiatch",
  "swallower",
  "swalow",
  "swamp guinea",
  "swamp guineas",
  "swastika",
  "syphilis",
  "t i t",
  "t i ts",
  "t1t",
  "t1tt1e5",
  "t1tties",
  "tacohead",
  "tacoheads",
  "taff",
  "tar babies",
  "tar baby",
  "tarbaby",
  "tard",
  "tastemy",
  "tawdry",
  "tea bagging",
  "teabagging",
  "teat",
  "teets",
  "teez",
  "terd",
  "teste",
  "testee",
  "testes",
  "testical",
  "testicle",
  "testicles",
  "testis",
  "thicklip",
  "thicklips",
  "thirdeye",
  "thirdleg",
  "threesome",
  "threeway",
  "throating",
  "thumbzilla",
  "thundercunt",
  "tig ol bitties",
  "tig old bitties",
  "tight white",
  "timber nigger",
  "timber niggers",
  "timbernigger",
  "titbitnipply",
  "titfuck",
  "titfucker",
  "titfuckin",
  "titjob",
  "titlicker",
  "titlover",
  "tits",
  "titt",
  "tittie",
  "tittie5",
  "tittiefucker",
  "titties",
  "tittis",
  "titty",
  "tittyfuck",
  "tittyfucker",
  "tittys",
  "tittywank",
  "titwank",
  "tity",
  "to murder",
  "tongethruster",
  "tongue in a",
  "tongueina",
  "tonguethrust",
  "tonguetramp",
  "topless",
  "tortur",
  "torture",
  "tosser",
  "towel head",
  "towel heads",
  "towelhead",
  "tr00n",
  "tr00ns",
  "trailertrash",
  "trannie",
  "tranny",
  "transsexual",
  "transvestite",
  "tribadism",
  "trois",
  "troon",
  "troons",
  "tub girl",
  "tubgirl",
  "tuckahoe",
  "tunneloflove",
  "turd burgler",
  "turnon",
  "tw4t",
  "twat",
  "twathead",
  "twatlips",
  "twats",
  "twatty",
  "twatwaffle",
  "two girls one cup",
  "twobitwhore",
  "twunt",
  "twunter",
  "udge packer",
  "ukrop",
  "unclefucker",
  "unfuckable",
  "upskirt",
  "uptheass",
  "upthebutt",
  "urethra play",
  "urethraplay",
  "urophilia",
  "ussys",
  "v a g i n a",
  "v14gra",
  "v1gra",
  "v4gra",
  "va-j-j",
  "va1jina",
  "vag",
  "vag1na",
  "vagiina",
  "vaj1na",
  "vajina",
  "valium",
  "venus mound",
  "vgra",
  "vibrater",
  "vibrator",
  "vigra",
  "violet wand",
  "virginbreaker",
  "vittu",
  "vixen",
  "vjayjay",
  "vorarephilia",
  "voyeurweb",
  "voyuer",
  "vullva",
  "vulva",
  "w00se",
  "w0p",
  "wab",
  "wank",
  "wanker",
  "wanking",
  "wanky",
  "waysted",
  "weenie",
  "weewee",
  "welcher",
  "wench",
  "wetb",
  "wetback",
  "wetbacks",
  "wetdream",
  "wetspot",
  "wh00r",
  "wh0re",
  "wh0reface",
  "whacker",
  "whash",
  "whigger",
  "whiggers",
  "whiskeydick",
  "whiskydick",
  "white power",
  "white trash",
  "whitenigger",
  "whitepower",
  "whitetrash",
  "whiteys",
  "whities",
  "whoar",
  "whoralicious",
  "whore",
  "whorealicious",
  "whorebag",
  "whored",
  "whoreface",
  "whorefucker",
  "whorehopper",
  "whorehouse",
  "whores",
  "whoring",
  "wichser",
  "wigga",
  "wiggas",
  "wigger",
  "wiggers",
  "willies",
  "williewanker",
  "wog",
  "wogs",
  "woose",
  "wop",
  "worldsex",
  "wrapping men",
  "wrinkled starfish",
  "wtf",
  "wuss",
  "wuzzie",
  "x-rated",
  "x-rated2g1c",
  "xkwe",
  "xtc",
  "xx",
  "xxx",
  "xxxxxx",
  "yaoi",
  "yarpie",
  "yarpies",
  "yellowman",
  "yellowshowers",
  "yid",
  "yids",
  "yiffy",
  "yobbo",
  "yourboobs",
  "yourpenis",
  "yourtits",
  "zabourah",
  "zigabo",
  "zigabos",
  "zipperhead",
  "zipperheads",
  "zoophile",
  "zoophilia",
  "🖕"
];

/**
 * Curated English profanity terms used by `createEnglishProfanityValidator`.
 */
export const PROFANITY_WORDS_EN: readonly string[] = Object.freeze(WORDS_EN);

/** Source metadata for `PROFANITY_WORDS_EN`. */
export const PROFANITY_WORDS_EN_SOURCE =
  "https://github.com/zautumnz/profane-words/blob/master/words.json";

/** SPDX-style shorthand for upstream list license. */
export const PROFANITY_WORDS_EN_LICENSE = "WTFPL";

/** Number of words in the curated list. */
export const PROFANITY_WORDS_EN_COUNT = PROFANITY_WORDS_EN.length;

/**
 * Names, places and common words that contain a word on the list, which `createEnglishProfanityValidator` lets
 * through: `scunthorpe`, `dickson`, `kirkland`. Measured by `scripts/measure-profanity.mjs` from openly licensed data:
 * ONS baby names for England and Wales (Open Government Licence v3.0), US census surnames (public domain), GeoNames
 * places (CC BY 4.0) and Webster's dictionary (public domain). Anything made of a listed word and English words or
 * affixes (`klansman`) is left out, and so is anything that looks like a slur or reads as crude (`niggli`,
 * `bitchfield`). Pass it as `allowlist` when you build your own validator from the list.
 */
// BEGIN GENERATED ALLOWLIST (node scripts/measure-profanity.mjs --write)
const ALLOWLIST_EN: string[] = [
  "aanislag", "abadiadegoias", "abeeda", "aberargie", "abimbola", "ackland", "acocks", "adamcik", "addicks",
  "adegoke", "adikeyh", "adrectal", "agramunt", "agrope", "aguafriadegoias", "aguaslindasdegoias", "aguiniga",
  "aholelei", "ainazi", "aixlesbains", "ajigasawa", "akatsuka", "akdiken", "akshit", "alanazi", "alcanhoes",
  "alchochoden", "almochoden", "alppikyla", "altoparaisodegoias", "alugan", "ambosexous", "amchoor", "amphoesikhiu",
  "amuntai", "andernoslesbains", "angiospastic", "angiosperm", "anopubic", "anorectal", "antemingent", "antigropelos",
  "apapantilla", "aparecidadegoiania", "aphorism", "apocha", "apocholic", "aprosexia", "aqtoghay", "archisperm",
  "archwench", "arenysdemunt", "areolet", "arnspiger", "arosuka", "arshakunti", "arshith", "asenovgrad", "asexually",
  "ashby-cum-fenby", "ashitkovo", "ashkenazi", "askland", "asmuth", "aspermia", "aspermic", "aspermont", "assmann",
  "assmanship", "astrashytski", "asuka", "asyllabia", "atlimeyaya", "atwater", "auchincloch", "auchincloss",
  "auckland", "aughey", "augurous", "aukland", "austendike", "authorish", "authorism", "autojigger", "autosexing",
  "avagrace", "avagray", "avanigadda", "ayira", "ayresquay", "ayvagrace", "azhoor", "aziskagorne", "babeship",
  "babesiasis", "babicenadsvitavou", "babokoon", "bacacay", "backboned", "backslapper", "badike", "bahapal",
  "baikunthpur", "bainslesbains", "baishizhen", "baishizhou", "baklan", "balaruclesbains", "banigan", "banklane",
  "bannigan", "bardonecchia", "bareboned", "bargecchia", "bargiel", "bascayir", "bassman", "bayir",
  "bedwastrethomasandmachen", "beighey", "belavistadegoias", "bellendir", "bellezza", "bellsdyke", "beniganim",
  "beniganj", "bequimao", "beribboned", "berkland", "beslagic", "besmut", "besnuff", "besqaraghay", "bestialize",
  "beycayiri", "bhawanigarh", "bieneman", "billigheimingenheim", "billinghay", "bilovicenadsvitavou", "bircheshead",
  "birkland", "bisexed", "bisexually", "bismuth", "bismutite", "bismutoplagionite", "bismutosmaltite",
  "bismutosphaerite", "blacklance", "blacklane", "blagoevgrad", "blankumsee", "blesbok", "bloodsucking", "bochechky",
  "bochenek", "bochenski", "bocher", "bochette", "bodupal", "bogande", "bogandinskiy", "bogangar", "bogans", "bogany",
  "bolayir", "bomdespacho", "bomdila", "bomjardimdegoias", "bomjesusdegoias", "bonaguro", "bondager", "bonedog",
  "bonhuntwater", "boquim", "boscage", "boschee", "boschen", "boschert", "boscherville", "boschetti", "boschetto",
  "botevgrad", "botlhapatlou", "bottmingen", "boughey", "boumerdas", "bourbonnelesbains", "boussysaintantoine",
  "branigan", "brannigan", "breekums", "breinigsville", "brereton-cum-smethwick", "brezovanadsvitavou", "bricklane",
  "bridegod", "brightwater", "bromoform", "bronchoadenitis", "bronchoesophagoscopy", "brondyke", "brushite", "bruski",
  "bruslaguna", "buckland", "budhapanka", "buggerru", "buikwe", "buildingless", "bulborectal", "bulhoes",
  "bullwhacker", "buritidegoias", "burkland", "bushwhacker", "bussysaintgeorges", "cacabelos", "cacace", "cacador",
  "cacadu", "cacahoatan", "cacahuatal", "cacahuatepec", "cacak", "cacal", "cacam", "cacanindin", "cacanthrax",
  "cacao", "cacapava", "cacas", "cacatachi", "cacate", "cacatian", "cacaulandia", "cachoeiradegoias", "cackerel",
  "cacospermia", "cajigal", "cajigas", "calimquim", "callabiana", "cambolesbains", "cammocky", "campestredegoias",
  "campoalegredegoias", "campolimpodegoias", "canadadegomez", "caputo", "carbonera", "carbonero", "carlosama",
  "carmosino", "carposperm", "cartsdyke", "casalecchio", "cashapampa", "cassman", "cawkwell", "cayirbasi",
  "cayirdere", "cayirhan", "cayirkent", "cayirli", "cayirova", "cazzola", "ccuntuma", "cecchi", "cedegolo",
  "cellardyke", "cergypontoise", "chamas", "chapa", "charbonniereslesbains", "chardon", "charlesbourg",
  "chateauneufdupape", "chattahoochee", "chava", "chavda", "chave", "chavi", "chavkin", "chavornay", "chavous",
  "chavoya", "chavuma", "chavutapalem", "chavy", "checchi", "cheektowaga", "chells", "cherpak", "cherpu", "chesher",
  "chhapar", "chimbudike", "chimdike", "chinampadegorostiza", "chinca", "chinch", "chincloth", "chincoteague",
  "chincough", "chingalpa", "chingas", "chinnachintakunta", "chiquimitio", "chiquimula", "chiquimulilla", "chodecz",
  "chodel", "chorisepalous", "chorisis", "chorism", "chorkowka", "chorlton-cum-hardy", "chorney", "chorny",
  "chrysosperm", "chuga", "chugg", "chugh", "chugur", "chuguyevka", "chujiang", "chummer", "cislago", "cisterniga",
  "clanabogan", "clansmanship", "claramunt", "claydike", "clehonger", "cliffordchambersandmilcote", "clitheroe",
  "closefisted", "clubfisted", "coatdyke", "cocainization", "cocainize", "cocainomania", "cocalzinhodegoias",
  "cockscomb", "cocksfoot", "cocksford", "cocksgreen", "cockshead", "cockshoot", "cockshot", "cockshut", "cockshy",
  "cockspur", "cockstone", "cockstreet", "cocksure", "cockyard", "coelosperm", "cohoes", "colecchi", "colesbourne",
  "colfack", "collecchio", "compenetrate", "compenetration", "condiddle", "congroid", "contestee", "copenetrate",
  "coprophiliac", "coquimatlan", "coquimbite", "coquimbo", "corumbadegoias", "cosamaloapan", "cosniga", "cotylopubic",
  "counterdike", "crawforddyke", "criminger", "crindledyke", "cummerbund", "cummings", "cummins", "cunigan",
  "cunnien", "cuntan", "cuntis", "cutwater", "cystospastic", "dacunto", "dadhapatna", "dagostini", "dagostino",
  "daguro", "dalchork", "damerdjog", "damunt", "danilovgrad", "danlugan", "dargie", "darkland", "dashitou", "decklan",
  "degoede", "degoey", "degollado", "degolyer", "degon", "degood", "degoorn", "degorge", "degori", "degoti",
  "dehorney", "deklan", "denazify", "denigrate", "denigration", "despisingly", "desquamation", "desquamative",
  "desquamatory", "dhamas", "dicklant", "dickmann", "dickshill", "dickson", "diddlebury", "diddler", "didouche",
  "dieciochodemarzo", "dignazio", "dignelesbains", "dikegrave", "dikelocephalid", "dikeman", "dikembe", "dikenafai",
  "diker", "dikes", "diketo", "dikshitpur", "dimitrovgrad", "dinglebird", "dingledangle", "dingleden", "dingler",
  "dingleton", "dingley", "dininny", "dinslage", "discage", "dismutation", "dispermic", "dispermy",
  "divinopolisdegoias", "divonnelesbains", "dockland", "dogdyke", "dokshytsy", "donaghey", "donigala", "donigan",
  "donvillelesbains", "doubravicenadsvitavou", "dowdyke", "drumchork", "drumuie", "duckwife", "dumbiedykes",
  "dunigan", "dunnigan", "dupability", "dupable", "dupaix", "dupaquier", "dupar", "dupas", "dupatta", "dupaty",
  "dupaul", "dupax", "dupay", "dykebar", "dykehead", "dykehopper", "dykema", "dykens", "dyker", "dykesfield",
  "dykeside", "eastwater", "eastwenatcheebench", "eaudike", "eaudyke", "ebenemael", "ecchinswell", "echoer",
  "eckland", "eclampsia", "edlesborough", "eichelkraut", "eisiminger", "ejidogogorronexhaciendadegogorron",
  "ejidosanjosexilatzen", "ekland", "ektodynamorphic", "ektor", "elcocks", "elkland", "elkrapids", "ellesborough",
  "ellingstring", "eminger", "emmingen", "emminger", "endosperm", "enemark", "enemawira", "enghienlesbains",
  "engstringerquartier", "ensminger", "enterosyphilis", "entsminger", "entzminger", "ependyma", "ependyme",
  "ependymitis", "ependymoma", "ependytes", "epipubic", "epipubis", "epispastic", "episperm", "epocha", "equimodal",
  "equimolar", "equimolecular", "equimomental", "equimultiple", "erpskwerps", "eskenazi", "esmegrace", "espigadilla",
  "espigao", "esquamate", "esquamulose", "esquenazi", "esquimalt", "essexite", "etchujima", "etwatwa",
  "euclidesdacunhapaulista", "evagrace", "evauxlesbains", "eveslage", "evianlesbains", "excrementary",
  "excrementitial", "excrementitious", "excrementive", "exosperm", "exsputory", "fackelman", "fackeltanz", "facklam",
  "fackler", "fackley", "fackrell", "faenor", "faenza", "faiga", "faige", "faigle", "faigy", "falkland", "fanhoes",
  "farmos", "faulkland", "featherpate", "fecalith", "fecaloid", "fecke", "feckner", "fecko", "fegghayes", "fellation",
  "fendykes", "figpecker", "fikes", "finigan", "finnigan", "fisherpeople", "fiskum", "fisterra", "flaxwench",
  "flickinger", "floresdegoias", "flowerpecker", "flumdiddle", "flummadiddle", "flummydiddle", "flushdyke",
  "folkland", "fondler", "fondlesome", "fontanezuranegresine", "fontanigorda", "fontecchio", "fookes", "fooks",
  "forgeslesbains", "forgy", "fornicated", "fosdyke", "fotheringhay", "fraccionamientocarlossalinasdegortari",
  "fraccionamientoyclubdegolflosencinos", "frankland", "freismuth", "frigge", "friggle", "fuksa", "fulgurous",
  "gameleiradegoias", "ganigan", "garchinganderalz", "garniga", "gasekhaolelo", "gassman", "gatadegorgos", "gaydon",
  "gaydos", "gaysome", "gaystreet", "gazzaniga", "gedneydyke", "geissospermin", "georgy", "gevorgyan", "ghayl",
  "ghayra", "ghayzah", "gheyzaniyeh", "giannecchini", "gilberdyke", "gioiosamarea", "glushitsa", "gobbledygook",
  "godego", "gonadial", "gonadotropic", "gonadotropin", "gonaduct", "gongheyong", "goodyke", "gorash",
  "goraswietejmagorzaty", "goraswietejmalgorzaty", "gornjismrtici", "gorrakunta", "grahamsdyke", "gravigrade",
  "greektown", "grenoble", "greouxlesbains", "grigoras", "groebe", "groebming", "groebner", "groebzig", "groedig",
  "groeger", "groehler", "groeibstadt", "groen", "groendyke", "groeper", "groepper", "groerlach", "groes",
  "groesfaen", "groet", "groezinger", "gropello", "gropeni", "groper", "grosskummerfeld", "gruenkraut", "grunkraut",
  "guaranidegoias", "gubbals", "gubser", "gubskaya", "guizieres", "gumminger", "gundupalaiyam", "gurovich",
  "guroymak", "gymnosperm", "gyorgy", "haenigsen", "hajiganj", "hajishah", "hajjiabad", "hajjibehzad", "hajjikhademi",
  "hajjilar", "hajjiqushan", "hajjiyar", "hamasa", "hamdouche", "hammerdal", "hammerdress", "hamrynadsazavou",
  "hanigan", "hanigsen", "hannigan", "hapalote", "hapao", "hapara", "hapaxanthous", "hardfisted", "harmost",
  "harshit", "hashitta", "hashizume", "haslag", "hassman", "hatsukaichi", "heartwater", "heeba", "heebner", "heikes",
  "hellship", "hellskitchen", "hellstrom", "hematospermia", "hemerdon", "hemiekton", "hemospastic", "hemospermia",
  "henhussy", "henigan", "hennigan", "hennigar", "hennigsdorf", "heredosyphilis", "heroicacaborca", "herpel",
  "herpen", "herpestine", "herpetic", "herpetiform", "herpetism", "herpetography", "herpetoid", "herpetologic",
  "herpetologist", "herpetology", "herpetomonad", "herpetophobia", "herpetotomist", "herpetotomy", "herpich",
  "herpin", "herpolhode", "herpst", "herrschingamammersee", "hieneman", "highamdykes", "higherpertwood",
  "higherpoynton", "higherprestacott", "hikes", "hilldyke", "hinigaran", "hinnershitz", "hiratsuka", "hiscocks",
  "hockwold-cum-wilton", "hoenigsberg", "hoerauf", "hoerbranz", "hoerby", "hoerchler", "hoerde", "hoerger", "hoeri",
  "hoerl", "hoerman", "hoernefors", "hoernemann", "hoerner", "hoernesite", "hoernig", "hoerning", "hoernitz",
  "hoernke", "hoernsheim", "hoerr", "hoersching", "hoerselgau", "hoerst", "hoertendorf", "hoerter", "hoerth",
  "hoertz", "hoeryong", "hoesch", "hoese", "hoesing", "hoesley", "hoesli", "hoesly", "hoesman", "hoestreet",
  "hofacker", "hofecker", "hoffacker", "hoffecker", "honigsberg", "honigsessen", "hoochinoo", "hoora", "hooria",
  "hooriya", "hoormann", "hoorn", "horishni", "horismology", "horist", "horka", "horkesley", "horkey", "horki",
  "horkman", "horkstow", "horky", "horneycommon", "hornyak", "hornybar", "hornyhanded", "hornyhead", "hornyvadicov",
  "horton-cum-studley", "howdendyke", "hradecnadsvitavou", "hsukalat", "huamancaca", "hughey", "hukuntsi",
  "hulshizer", "humbugger", "humbuggery", "hummera", "hummerbeck", "hummersknott", "hummert", "hummocky", "humpert",
  "humphery", "hygroexpansivity", "hymeneal", "hymenean", "hymenial", "hymenicolar", "hymeniferous", "hymeniophore",
  "hymenium", "hymenogeny", "hymenoid", "hymenomycetal", "hymenomycete", "hymenomycetoid", "hymenomycetous",
  "hymenophore", "hymenophorum", "hymenophyllaceous", "hymenopter", "hymenotomy", "hyperprosexia", "hypnosperm",
  "hypochondria", "hypochondrium", "hypochondry", "hypochordal", "hypoprosexia", "ibiakuntokokpo", "idiospastic",
  "iliopubic", "imbimbo", "immerd", "impenetrate", "impenetration", "impubic", "inawashiro", "incrash", "inflamer",
  "infrabestial", "inohymenitic", "interpenetrate", "interpenetration", "interpubic", "intrarectal",
  "ipirangadegoias", "ironfisted", "ischiopubic", "ischiopubis", "ischiorectal", "ishiguro", "ishitha", "ishitsuka",
  "ishizu", "islagrace", "islagrey", "israelsen", "israelson", "ithyphallic", "itsukaichi", "ivaylovgrad",
  "jackassflat", "jackassification", "janiga", "jaquima", "jarnigan", "jenema", "jennigs", "jernigan",
  "jesuscarranzaranchodejesus", "jigamaree", "jigani", "jigar", "jiggerman", "jigget", "jiggle", "jiggumbob", "jiggy",
  "jihadia", "jijiga", "joaquim", "johnigan", "journigan", "jueneman", "kachug", "kachujan", "kadupandak",
  "kamatsuka", "kanaker", "karpochori", "kassman", "kawka", "kayirma", "kelklan", "kenema", "kenigsberg", "kerchug",
  "kewaskum", "keystoned", "khapa", "khodzhamaston", "khokholskiy", "kingsdyke", "kirchheimunterteck", "kirkland",
  "kirovgrad", "klana", "klander", "klang", "klanjec", "klank", "klann", "klepacki", "klondyke", "klusty",
  "knigsmacker", "knipple", "knips", "koeneman", "koenigs", "koenigslutter", "kokoon", "kolchugino", "komuniga",
  "konigs", "konigslutter", "konopacki", "koonawarra", "koonce", "koondoola", "koone", "koongal", "koonimedu",
  "koons", "koonthalloor", "koonts", "koontz", "koonz", "kootcha", "kopacki", "kopaska", "kranjskagora", "krape",
  "krapf", "krapina", "krapinske", "krapivinskiy", "krapivna", "krapkowice", "krapp", "krasnokumskoye", "krautbauer",
  "krauter", "krauth", "krautkramer", "krautkremer", "krautter", "kremenchug", "krepuskagezatelep", "krimminger",
  "krumovgrad", "krupicka", "kruskie", "kshitij", "kueneman", "kumertau", "kummerer", "kummerfeld", "kummerow",
  "kummersbruck", "kumsal", "kumsi", "kunigal", "kuntaur", "kunten", "kunting", "kuntsevo", "kuntz", "kurwai",
  "kushikino", "kushima", "kushimoto", "kushin", "kushion", "kushiro", "kusiak", "kusic", "kusik", "kusilek",
  "kusimansel", "kusinski", "kuslukcayiri", "kyker", "labeed", "labiak", "labial", "labianca", "labianco", "labiate",
  "lacapellelesboulogne", "laisterdyke", "lamaloulesbains", "lamerd", "langshyttan", "lanigan", "lanigay", "lannigan",
  "lapillus", "lapinigan", "lapoladegordon", "lareole", "largie", "larklands", "laspenas", "lassman", "lasswade",
  "lawkland", "leboscrogerenroumois", "lechuguilla", "ledecnadsazavou", "legrope", "lemonetierlesbains", "lenigar",
  "lepera", "lepere", "leperrayenyvelines", "leperreon", "leperreuxsurmarne", "leperrier", "lepertre", "leptosperm",
  "lesbois", "lesbons", "lesborgesdelcamp", "leskovecprikrskem", "lespignan", "lestroisbassins", "lestroislucs",
  "levokumskoye", "lezzeno", "lichinga", "lienemann", "lifshits", "lifshitz", "lightwater", "likes", "lileperrot",
  "lillingstonedayrell", "lipochondroma", "lipochori", "lithosperm", "littlebosullow", "livshits", "llanllugan",
  "llechfaen", "llithfaen", "llysfaen", "locklan", "longendyke", "lonquimay", "lopacki", "lorgies", "losamates",
  "loslagos", "loughbrickland", "lowerprincesquarter", "lubraniec", "lubrano", "lubrant", "lugano", "lugansk",
  "luganville", "lughaye", "luxeuillesbains", "lyminge", "lymphopenial", "maccacari", "machinga", "machodeagua",
  "mackintoshite", "macnutt", "madhapar", "madikwe", "mahapatra", "mahboob", "mahoor", "mahorney",
  "maidstonedistrict", "maiziereslagrandeparoisse", "mangaysu", "mangorasso", "manigan", "manigat", "manigault",
  "maputo", "margie", "mariconda", "markland", "markovgrad", "marmose", "marshite", "mascagni", "massanutten",
  "massman", "matsukawa", "mcconnaughay", "mcconoughey", "mcgonigal", "mchugo", "mckoon", "mcmanigal", "mcnutt",
  "measboroughdike", "mecchi", "mechraa", "meguro", "mehboob", "menaged", "menager", "menisperm", "menslage",
  "merdan", "merdes", "merdey", "merdi", "merdrignac", "merdzavan", "merkland", "merslesbains", "mesorectal",
  "mesorectum", "mesosperm", "metamorphoser", "metasperm", "mexticacan", "middlesboro", "miejskagorka", "mikes",
  "milesquare", "milfield", "milfoil", "milfontes", "milford", "milfort", "mimmocky", "mimosodegoias", "mingee",
  "mingelen", "minges", "minnigaff", "mirjhapar", "mitsukaido", "mittegroefehn", "mkushi", "mlakaprikranju",
  "mofopefoluwa", "mohapatra", "mokshith", "molugan", "monazine", "monazite", "mondego", "mondorflesbains", "moniga",
  "monkland", "monosperm", "montealegredegoias", "montecchia", "montecchio", "montelargoraseccion", "montenegro",
  "montescaglioso", "montesclarosdegoias", "montrondlesbains", "morroagudodegoias", "moskala", "moskalenki",
  "moskalenko", "moskalenky", "moskalik", "moskalski", "moskaluk", "moskwa", "mountgayshamrock", "mughayyir",
  "multivibrator", "munomerdelpeco", "muntaha", "muntanyola", "muntaqim", "muntasir", "muntaz", "munte", "munti",
  "muntjac", "muntlix", "muntner", "muntok", "munton", "munts", "muntz", "mussysurseine", "muthersbaugh",
  "myelosyphilis", "namboongan", "namkoong", "nardecchia", "nazia", "nazifa", "naziha", "nazilli", "nazim", "nazir",
  "nazish", "nearmost", "nedumbassery", "neftekumsk", "negresti", "negroni", "negroponte", "nekton", "nerislesbains",
  "nesslage", "netherpadley", "netherpeover", "netherpoppleton", "neurosyphilis", "ngurore", "nickerpecker",
  "niederbronnlesbains", "nigaglioni", "nigam", "nigatu", "nigori", "nikesh", "nikshith", "ninacaca", "nincompoopery",
  "ninnyhammer", "ninnyship", "ninnywatch", "nipplewort", "nishitokorozawa", "nishitokyo", "nonsmutting", "nordike",
  "nordyke", "norgyugh", "northdyke", "northdykes", "novagrace", "novagradiska", "novagranada", "novaiguacudegoias",
  "novigrad", "novogurovskiy", "novosamarka", "nuevagranada", "nummerdor", "nupaky", "nutpecker", "nwadike",
  "nwankwo", "oaklan", "oberengstringen", "ochavo", "ochodeenero", "oermingen", "ogeulesbains", "oghenemaro",
  "okland", "okushiri", "oligospermia", "oliviagrace", "omchug", "omofolarin", "oosperm", "opdyke", "orgyia",
  "osamah", "ossendyke", "ostrovumacochy", "ostrovumare", "otsuka", "ouroverdedegoias", "outeat", "outwatch",
  "outwater", "overfondle", "overlusty", "ovotestis", "oxpecker", "ozendyke", "pachyhymenia", "pachyhymenic",
  "pachymenia", "pachymenic", "pachymeningitic", "pachymeningitis", "pachymeninx", "packie", "packingham",
  "packington", "paguroid", "palaciosdegoda", "palestinadegoias", "palmeirasdegoias",
  "palosamarillospalosamarillosyebucivi", "panalesjamaicacanones", "panigrahi", "pansexism", "panspermia",
  "panspermic", "panspermism", "panspermist", "panspermy", "pantiasau", "panticeu", "pantier", "pantig", "pantijan",
  "pantile", "pantiling", "pantin", "pantisawa", "pantisocracy", "pantisocrat", "pantitlan", "pantybuarth",
  "pantycaws", "pantycrug", "pantydwr", "pantyffridd", "pantyffynnon", "pantygelli", "pantygraig", "pantyllyn",
  "pantymwyn", "pantypwdyn", "pantyrathro", "pantyrawel", "pantyrhiw", "pantywaist", "papikyan", "papillulate",
  "papillule", "paprika", "parachodeverduzco", "pararectal", "parasyphilis", "parkhamash", "parkland", "parklane",
  "parkrapids", "parthenosperm", "pascagoula", "paskal", "paskar", "passman", "patroon", "patroonship", "peacocky",
  "pecchi", "pellecchia", "pellezzano", "pelvigraph", "pelvirectal", "penasanchez", "penaschatas", "penasco",
  "penasdesanpedro", "penasquitos", "pendyala", "penigar", "penilee", "penistone", "pennigsehl", "penthouselike",
  "peripenial", "perirectal", "perisperm", "peruski", "petitt", "petrolinadegoias", "pettitt", "pfaender", "pfister",
  "phacochoere", "phacochoeroid", "phallin", "phallism", "phallist", "phallitis", "phenazine", "phenospermic",
  "phenospermy", "phikwe", "phlebosclerosis", "phlebostasia", "phlebostasis", "phlebostenosis", "phlebostrepsis",
  "phosphorism", "phukamyao", "phuket", "phukhiao", "phukhuong", "phukradueng", "phuquoc", "phuquy", "pianiga",
  "pickaback", "pickable", "pickage", "pickar", "pickaway", "pickax", "piernigas", "pikermi", "pikeroad", "pikes",
  "pilardegoias", "pilikwe", "pilluana", "piloerection", "pimperlimpimp", "pimperne", "pinchfisted", "pinegrove",
  "pinkos", "pinkowski", "pirayiri", "pirchingamtraubenberg", "pittwater", "placuntitis", "placuntoma", "planklane",
  "plombiereslesbains", "pochade", "pochahuizco", "pochalcatl", "pochampalli", "pochard", "pochatko", "pochayiv",
  "pochayna", "pochop", "pochota", "pochotillo", "pochotitan", "podkumskiy", "podosperm", "pokunt", "polaca",
  "polacca", "polacco", "polacek", "polach", "polaco", "polacre", "polihajji", "poltroon", "polychoerany",
  "polyspermia", "polyspermic", "polyspermy", "ponteatressa", "pontecchio", "pontfaen", "porgy", "poricinadsazavou",
  "porlezza", "porrectus", "postpubescent", "poteat", "potiskum", "powdike", "praepubis", "pravokumskoye", "prenoble",
  "prepubescent", "prickseam", "prickshot", "prickspur", "prikazy", "prikhodko", "prikro", "prikryl", "prikubanskiy",
  "princestown", "protovum", "pruski", "pseudophallic", "pseudosperm", "pseudosyphilis", "pseudovum", "psorosperm",
  "psychoorganic", "psychosexually", "pteridosperm", "pubescence", "pubescency", "puborectalis", "pucacaca",
  "pudupalayam", "pushchavodytsya", "putois", "putol", "putorti", "pyospermia", "pyrenematous", "pyshchug",
  "qasemabadegorji", "qingshizui", "queersome", "quilomboquiaputo", "quimbango", "quimbaya", "quimbele", "quimbundo",
  "quimby", "quime", "quimiac", "quimiag", "quimicas", "quimichis", "quimili", "quimistan", "quimoh", "quimper",
  "quimpo", "quimson", "quinquim", "quintanasdegormaz", "quintroon", "rabocheostrovsk", "raheeb", "raikes",
  "rammingen", "ramminger", "ranchodeguadalupe", "raniganj", "rannigal", "rapacki", "raspanti", "rassman",
  "ravenstonedale", "rawboned", "rayirth", "rearmost", "rebecchi", "recchia", "recchio", "rectalgia", "reddicks",
  "reneman", "renigar", "renobato", "resquare", "retromingent", "retropubic", "retrorectal", "rettenschoess",
  "rheeboc", "rheebok", "rhodosperm", "rhomboganoid", "rhosaman", "riachodesantana", "riachodesantoantonio",
  "ridinglea", "rikesh", "ringboned", "ringsmuth", "rionegro", "rishit", "ritardando", "roccacanavese",
  "roccacanterano", "rochelezbeaupre", "rockland", "rockrapids", "rollicking", "rominger", "rosamae", "rosamai",
  "rosamaria", "rosamay", "rospigliosi", "ruckland", "rudniknadsanem", "rummingen", "rushiti", "ruskifilvarky",
  "ruskikomarivtsi", "ruskikrstur", "ruskin", "russkinskiye", "russkiy", "sacropubic", "sacrorectal", "sagurong",
  "saintcharlesborromee", "saintdenislesbourg", "saintemariedegosse", "saintgeorgeslesbains", "saintgermerdefly",
  "saintgervaislesbains", "saintgervaislestroisclochers", "saintlaurentdupape", "saintmauricedegourdans",
  "saintpaultroischateaux", "sainttrojanlesbains", "salinslesbains", "salkelddykes", "sandman", "sandmeier",
  "sandmire", "sanestebandegormaz", "sangiorgiodellepertiche", "sanjosexicohtencatl", "santaanazicatecoyan",
  "santabarbaradegoias", "santacruzdegoias", "santafedegoias", "santahelenadegoias", "santarosadegoias",
  "santaterezadegoias", "santaterezinhadegoias", "santoantoniodegoias", "saofranciscodegoias", "saputo", "saraguro",
  "sarcosperm", "sassman", "sauerkraut", "saukrapids", "scagglethorpe", "scaggs", "scaglia", "scagliola",
  "scagliolist", "scaglione", "scagliotti", "scagnelli", "scagnello", "scarnecchia", "sceneman", "scheneman",
  "schildkraut", "schinkel", "schleper", "schmucker", "schoder", "schoeneman", "schoer", "schoessler", "schoessow",
  "schoor", "schorisse", "schork", "schueneman", "schug", "schwartzenberge", "schwartzer", "scopulate", "scotsdike",
  "scrapper", "scroger", "scrogg", "scrogham", "scrogum", "scrudato", "scummy", "scunthorpe", "seacunny", "seadyke",
  "sebtbnigarfett", "secchia", "seduceable", "seducee", "seducement", "seducer", "seguro", "seilebost", "semerdjian",
  "semihorny", "seniga", "sequim", "sermaizelesbains", "sexifid", "sexillion", "sexiped", "sexipolar", "sexisyllabic",
  "sexisyllable", "sexitubercular", "sexivalence", "sexivalency", "sexivalent", "sexological", "sexologist",
  "sexology", "seyidsadiq", "shamas", "shammocky", "shankland", "shapable", "shapaja", "shapard", "shardonay",
  "shardonnay", "shawinigan", "shawnigan", "shebesta", "shells", "shenanigan", "sheneman", "sherpa", "sherpur",
  "shimshit", "shita", "shither", "shitkino", "shitlu", "shittah", "shitterton", "shittim", "shittu", "shituo",
  "shivajinagar", "shiza", "shizhai", "shizhi", "shizhong", "shizi", "shizuishan", "shizuka", "shizukuishi",
  "shizunai", "shizuoka", "shoer", "shoes", "shoor", "shooters", "shorkot", "shugurovo", "shuthonger", "shyti",
  "shytle", "siercklesbains", "sierzputowski", "sikes", "silecchia", "simeonovgrad", "siquima", "sirghaya",
  "sitampiky", "skagen", "skager", "skaggs", "skagway", "skeldyke", "skoonplaas", "skrapar", "skrapits", "skwara",
  "skwarek", "skweres", "slaga", "slagel", "slager", "slagg", "slagh", "slagle", "slagman", "slagowski", "slagter",
  "slammocky", "slepicka", "slicking", "slummocky", "smegal", "smego", "smerdel", "smerdon", "smutch", "smutek",
  "smutko", "smutny", "smutproof", "smuts", "smutted", "smutter", "smuttily", "smuttiness", "smutz", "snigs",
  "snipsnapsnorum", "snuffbox", "snuffcolored", "snuffer", "snuffle", "snuffliness", "snuffling", "snuffman",
  "soccherpaianecasanarsie", "soemmerda", "somerdale", "sommerda", "sousek", "souser", "spasticity", "specker",
  "sperfslage", "sperma", "spermatovum", "spermezeu", "spermidine", "spermiducal", "spermiduct", "spermigerous",
  "spermine", "spermiogenesis", "spermoblast", "spermocarp", "spermocenter", "spermoderm", "spermoduct",
  "spermogenesis", "spermogenous", "spermogone", "spermogoniferous", "spermogonium", "spermogonous", "spermologer",
  "spermological", "spermologist", "spermology", "spermolysis", "spermolytic", "spermophile", "spermophiline",
  "spermophore", "spermophorium", "spermophyte", "spermophytic", "spermosphere", "spermotheca", "spermotoxin",
  "spermous", "spermoviduct", "spigarelli", "spigel", "spigener", "spiggle", "spiggoty", "spight", "spigler",
  "spigner", "spignet", "spigno", "spigot", "spiker", "spillum", "sprik", "spunkily", "squawk", "squiffed",
  "squiffer", "squiffy", "squimmidge", "srivaikuntam", "steatin", "steatite", "steatitic", "steatocele",
  "steatogenous", "steatolysis", "steatolytic", "steatoma", "steatopathic", "steatopyga", "steatopygia",
  "steatopygic", "steatopygous", "steatosis", "steets", "stegeslag", "stickland", "stikes", "stitt", "stockland",
  "stonedamp", "stonepecker", "stonhamaspal", "stopless", "stow-cum-quy", "stricklan", "stroisch", "subpubescent",
  "subpubic", "sukabumi", "sukacai", "sukadana", "sukagawa", "sukahriz", "sukaina", "sukalski", "sukamaju",
  "sukamakmue", "sukamulia", "sukanagara", "sukaraja", "sukarama", "sukasada", "sukasari", "sukawati", "sukawening",
  "sukayama", "sukayna", "sukhokumsk", "sukoon", "summerdale", "suniga", "sunkland", "suprapubic", "sussexinlet",
  "sussexite", "susticacan", "sutton-cum-lound", "svetlanadsazavou", "swank", "swanky", "swarajism", "sweenie",
  "sweetwater", "swierklaniec", "swierklany", "swiggart", "swingdingle", "sychavka", "tachingamsee", "takushi",
  "tamazuladegordiano", "tanagroid", "tanigawa", "taquaraldegoias", "tarbogan", "tarradiddle", "taskage", "tayir",
  "teataster", "teatatupeninsula", "teatatusouth", "teate", "teatfish", "teath", "teaticket", "teatime", "teatina",
  "teatino", "teatlike", "teatling", "teatman", "teator", "teatreegully", "teats", "tecacahuaco", "tecchiena",
  "tedstonedelamere", "teetsel", "tenemasa", "tenemaza", "tercislesbains", "teresinadegoias", "terezopolisdegoias",
  "termonfeckin", "thapa", "theopantism", "thermopenetration", "thesheddings", "thesquare", "thizylesbourgs",
  "thononlesbains", "thorkelson", "thorndike", "thorney", "thorny", "threecocks", "thromboangiitis", "thumper",
  "thymene", "tidingless", "tightfisted", "tigroid", "tilney-cum-islington", "timberhonger", "tinabogan", "tinigao",
  "tipaskan", "titter", "tittle", "tittup", "tlusty", "tolarampurwamotalkekurwamathia", "tomislavgrad", "tommerdahl",
  "topolovgrad", "torfaen", "torghay", "tourinneslagrosse", "transmutability", "transmutable", "transmutably",
  "transmutation", "transmutative", "transmutatory", "transmute", "transmuting", "transmutive", "transmutual",
  "traslovslage", "trecchina", "treslagoas", "treworgy", "trichode", "trinkums", "trismegist", "trochodendraceous",
  "troisdorf", "troise", "troisi", "troispistoles", "troisponts", "troisrivieres", "troissereux", "troistorrents",
  "troisvierges", "tropacocaine", "trophosperm", "tschumper", "tshitereke", "tshituni", "tsukabaru", "tsukada",
  "tsukamoto", "tsukawaki", "tuikwerd", "tukums", "turnipseed", "turnpiker", "twatchel", "twatt", "twitterboned",
  "tynecnadsazavou", "tzucacab", "uchkoprik", "uebelhoer", "ufackl", "uncarboned", "undefecated", "underpacking",
  "underthroating", "undespising", "undiked", "undouched", "unfondled", "ungropeable", "unisexed", "unisexually",
  "unpenetrated", "unprostituted", "unribboned", "unseduced", "unterengstringen", "unthumped", "updike", "updyke",
  "upperhellsgate", "upperprincesquarter", "urethropenile", "urethrorectal", "ushitsu", "ushytsya", "uskumrukoey",
  "uskumrukoy", "vagabondage", "vagharshapat", "vagrance", "vagrancy", "vagrant", "vagrate", "vajgurore", "valathoor",
  "valdegovia", "valdepenas", "vallfogonadebalaguer", "vallfogonaderiucorb", "valparaisodegoias", "valslesbains",
  "vandike", "vandyke", "vanhoorebeke", "varaklani", "vasospastic", "vazhapadi", "vecchi", "veeneman", "vehslage",
  "veintiochodemayo", "velezzo", "vellezzo", "venema", "venigalla", "verdecchia", "verkhoshizhemye", "verlezza",
  "vernetlesbains", "verschoore", "vesicopubic", "vesicorectal", "viagram", "viagrande", "viagraph",
  "vieuxboucaulesbains", "vigrass", "vikesa", "vikesh", "villanuevadegomez", "villanuevadegormaz", "villarmosa",
  "villeneuvelesbouloc", "vittum", "vittuone", "vixenlike", "voglans", "wachsmuth", "wadifukin", "waheeb", "wanigan",
  "warddykes", "warmerdam", "washdyke", "waskaganish", "wassman", "wassmuth", "wattlesborough", "weakland",
  "weathercocky", "weatherproof", "wegierskagorka", "welchert", "wellesbourne", "wenchang", "wenchlike", "wennigsen",
  "westdyke", "westwater", "westwatford", "wetbird", "whaleboned", "whashton", "whitkirklaneend", "whitler",
  "whorish", "whoriskey", "wickland", "wicklane", "wiemerslage", "wiggam", "wiggan", "wiggaton", "wighay",
  "wilcockson", "willcockson", "willesborough", "winegrower", "winegrowing", "winterdykes", "withindoors",
  "woodpecker", "woosehill", "wulfeck", "wussler", "wussow", "wusstig", "wychavon", "xhoris", "yaniga", "yashitinin",
  "yokosuka", "yoshitomi", "yoshizumi", "yverdonlesbains", "zaamslag", "zahoor", "zamboanga", "zamboanguita",
  "zapantis", "zdarnadsazavou", "zecchin", "zelenokumsk", "zemstroist", "zgarnadsazavou", "zhamashi", "zhansugurov",
  "zhemchug", "zimentwater", "zolezzi", "zrucnadsazavou", "zuniga", "zvenigorod", "zygmunt", "zygosperm",
];
// END GENERATED ALLOWLIST
export const PROFANITY_ALLOWLIST_EN: readonly string[] = Object.freeze(ALLOWLIST_EN);

/**
 * Create a profanity validator preloaded with the curated English word list and its allowlist.
 *
 * This keeps core `namespace-guard` zero-dependency while offering
 * a ready-to-use policy for teams that want quick defaults. An `allowlist` you pass is added to
 * `PROFANITY_ALLOWLIST_EN`.
 */
export function createEnglishProfanityValidator(
  options?: ProfanityValidatorOptions
): NamespaceValidator {
  return createProfanityValidator(PROFANITY_WORDS_EN, {
    ...options,
    allowlist: [...PROFANITY_ALLOWLIST_EN, ...(options?.allowlist ?? [])],
  });
}
